import {test,expect} from '@playwright/test';
test('实际判分更正保留旧评估上下文，页面可查询新旧版本且原作答不变',async({page,context})=>{
  let etag='';async function call(path:string,body?:unknown){const r=await context.request.fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'X-Learning-Request':'1','If-Match':etag,'Idempotency-Key':crypto.randomUUID()},...(body===undefined?{}:{data:body})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json();}
  await call('/auth/register',{userName:'context-ui-'+Date.now(),password:'assessment-browser-private-2026'});const s=await call('/students',{name:'评估上下文界面验收'});
  const d=await call('/content/fixture',{});await call(`/content/drafts/${d.id}:review`,{});const p=await call(`/content/drafts/${d.id}/preview`);const release=await call(`/content/drafts/${d.id}:publish`,{previewHash:p.hash});await call(`/students/${s.id}/content/${release.id}:bind`,{});
  const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date());const plan=await call(`/students/${s.id}/plans/${day}:generate`,{});const catalog=JSON.parse(release.payload);const q=catalog.questions[0];
  const t=await call(`/plans/${plan.id}/tasks`,{title:'固定评估测试题',minutes:5,resourceRef:'本地验收',type:'Practice',questionId:q.id});const view=await call(`/students/${s.id}/plans/${day}`);await call(`/plans/${plan.id}:publish`,{previewHash:view.revision.inputHash,confirmWarnings:true});await call(`/tasks/${t.id}:transition`,{status:'InProgress'});const session=await call(`/tasks/${t.id}/sessions`,{});const attempt=(await call(`/sessions/${session.sessionId}/attempts`,{clientSubmissionId:crypto.randomUUID(),answer:'999'})).attempt;
  await expect.poll(async()=> (await call(`/students/${s.id}/mastery`)).pending).toBe(0);const old=await call(`/students/${s.id}/assessment-contexts`);expect(old.contexts[0]).toMatchObject({activationStatus:'Active',admissionStatus:'Eligible',mappingSource:'FixedContainer'});
  await page.goto('/');await page.getByRole('button',{name:/证据与复习/}).click();const history=page.getByRole('region',{name:'评估版本记录'});await expect(history.getByText('当前生效 · 1 条评估上下文')).toBeVisible();await expect(history.getByText(/按正式题目规则评估 · 固定映射版本/)).toBeVisible();
  const grade={result:'Correct',reason:'实际参考答案核对后的更正',steps:[]};const preview=await call(`/attempts/${attempt.id}/grading-preview`,grade);await call(`/attempts/${attempt.id}/grading-revisions`,{...grade,previewHash:preview.previewHash});await expect.poll(async()=> (await call(`/students/${s.id}/mastery`)).pending).toBe(0);const revocations=await call(`/students/${s.id}/evidence-revocations`);expect(revocations.total).toBe(1);const current=await call(`/students/${s.id}/assessment-contexts`);expect(current.contexts[0].gradingRevisionId).not.toBe(old.contexts[0].gradingRevisionId);
  await page.getByRole('button',{name:'刷新后台结果',exact:true}).click();await expect(page.getByRole('region',{name:'证据撤销记录'}).getByText('已撤销 1 条历史证据')).toBeVisible();await expect(history.getByLabel('选择评估版本（最近50版）').locator('option')).toHaveCount(3);await history.getByLabel('选择评估版本（最近50版）').selectOption(old.generation.id);await expect(history.getByText('历史保留 · 1 条评估上下文')).toBeVisible();await history.locator('summary').filter({hasText:'核对本条版本引用'}).click();await expect(history.getByText('判分修订：'+old.contexts[0].gradingRevisionId,{exact:true})).toBeVisible();
  const exported=await call(`/students/${s.id}/export`);expect(exported.attempts.find((a:any)=>a.id===attempt.id)).toEqual(attempt);expect(exported.assessmentContexts).toHaveLength(2);expect(exported.evidenceRevocations).toHaveLength(1);expect(exported.assessmentContexts.find((c:any)=>c.id===old.contexts[0].id).activationStatus).toBe('Retired');
  expect(exported.consumerReceipts).toHaveLength(2);expect(exported.backgroundJobs).toHaveLength(2);expect(exported.consumerReceipts.map((r:any)=>r.generationId)).toContain(old.generation.id);
  expect(exported.domainEvents.filter((e:any)=>e.eventType==='AssessmentApplied')).toHaveLength(2);for(const receipt of exported.consumerReceipts){expect(receipt.domainEventId).toBe(receipt.eventId);expect(exported.domainEvents.some((e:any)=>e.id===receipt.domainEventId && e.dispatchTarget==='assessment/1')).toBeTruthy();}
  await page.getByRole('button',{name:/辅助建库/}).click();const jobs=page.getByRole('region',{name:'后台任务保护'});await jobs.getByRole('button',{name:'刷新后台任务'}).click();await expect(jobs.getByRole('heading',{name:'学习评估 · 已完成'})).toHaveCount(2);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
