import {test,expect} from '@playwright/test';
test.skip(!process.env.CANDIDATE_REVIEW_USER,'由隔离实际接口验收提供正式发布与原始候选');
test('候选审核展示固定测量题，要求真实依据，过期保存保留编辑与原输出',async({page})=>{
  await page.goto('/');await page.getByLabel('家长用户名').fill(process.env.CANDIDATE_REVIEW_USER!);await page.getByLabel('家长密码').fill(process.env.CANDIDATE_REVIEW_PASSWORD!);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('button',{name:/辅助建库/}).click();
  const region=page.getByRole('region',{name:'候选逐项审核'}),id=process.env.CANDIDATE_REVIEW_ID!,second=process.env.CANDIDATE_REVIEW_SECOND!;
  const rows=await page.evaluate(async()=>await(await fetch('/api/v1/builder')).json());const original=rows.candidates.find((c:any)=>c.id===id),other=rows.candidates.find((c:any)=>c.id===second);
  await region.locator('.content-row').filter({has:page.getByRole('heading',{name:original.name,exact:true})}).getByRole('button',{name:'核对此候选'}).click();
  const current=region.getByRole('article',{name:'当前候选核对'});await expect(current.getByText('创建时固定正式内容第 1 版',{exact:true})).toBeVisible();await expect(current.locator('blockquote')).toContainText('<img');await expect(current.locator('img')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__candidateInjected)).toBeUndefined();await expect(current.getByRole('button',{name:'接受为新草稿'})).toBeDisabled();await expect(current.getByRole('button',{name:'拒绝',exact:true})).toBeDisabled();
  await current.getByText('相近能力与支持题目（模拟排序）',{exact:true}).click();await expect(current.getByText(/支持测量题目/).first()).toBeVisible();await expect(current.getByText('不同测量目标的对照题',{exact:true}).first()).toBeVisible();
  await current.getByLabel('候选名称').fill('家长校正的一层括号能力');await current.getByLabel('可测行为',{exact:true}).fill('独立计算一层括号内的加减，再进行除法');await current.getByLabel('能力边界',{exact:true}).fill('不含嵌套或数量关系建模');const reason='已逐项核对原片段、固定正式测量题和不同目标对照，接受为待审草稿。';await current.getByLabel('本次审核依据').fill(reason);
  await page.evaluate(async()=>{const state=await fetch('/api/v1/me');const response=await fetch('/api/v1/students',{method:'POST',headers:{'Content-Type':'application/json','X-Learning-Request':'1','If-Match':state.headers.get('etag')!,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({name:'另一页修改造成过期'})});if(response.status!==201)throw new Error('真实另一页写入未成功');});
  const rejected=page.waitForResponse(r=>r.url().endsWith(`/builder/candidates/${id}:decide`)&&r.request().method()==='POST');await current.getByRole('button',{name:'接受为新草稿'}).click();expect((await rejected).status()).toBe(412);await expect(current.getByLabel('候选名称')).toHaveValue('家长校正的一层括号能力');await expect(current.getByLabel('本次审核依据')).toHaveValue(reason);
  await current.getByRole('button',{name:'重新读取此候选'}).click();await expect(current.getByLabel('本次审核依据')).toHaveValue('');await current.getByLabel('候选名称').fill('家长校正的一层括号能力');await current.getByLabel('可测行为',{exact:true}).fill('独立计算一层括号内的加减，再进行除法');await current.getByLabel('能力边界',{exact:true}).fill('不含嵌套或数量关系建模');await current.getByLabel('本次审核依据').fill(reason);
  const saved=page.waitForResponse(r=>r.url().endsWith(`/builder/candidates/${id}:decide`)&&r.request().method()==='POST');await current.getByRole('button',{name:'接受为新草稿'}).click();const response=await saved;expect(response.status()).toBe(200);expect(response.request().postDataJSON().reason).toBe(reason);const record=await response.json();expect(record.name).toBe(original.name);expect(record.protocolPayload).toBe(original.protocolPayload);expect(record.reviewReason).toBe(reason);await expect(current.getByText('审核依据：'+reason,{exact:true})).toBeVisible();await expect(current.getByRole('button',{name:'继续编辑审核草稿'})).toBeVisible();
  await current.screenshot({path:'../../test-results/candidate-review-tablet.png'});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await current.screenshot({path:'../../test-results/candidate-review-phone.png'});
  await region.locator('.content-row').filter({has:page.getByRole('heading',{name:other.name,exact:true})}).getByRole('button',{name:'核对此候选'}).click();await current.getByLabel('本次审核依据').fill('明确拒绝：尚无足够独立测量支持，需要补充来源。');await current.getByRole('button',{name:'拒绝',exact:true}).click();await expect(current.getByText('审核依据：明确拒绝：尚无足够独立测量支持，需要补充来源。',{exact:true})).toBeVisible();
});
