import {test,expect} from '@playwright/test';
test('独立资源映射草稿保留来源、拒绝过期保存并通过真实审核发布',async({page,context})=>{
 let etag='';async function call(path:string,body?:unknown,method=body===undefined?'GET':'POST'){const r=await context.request.fetch('/api/v1'+path,{method,headers:{'X-Learning-Request':'1','If-Match':etag,'Idempotency-Key':crypto.randomUUID()},...(body===undefined?{}:{data:body})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json()}
 await call('/auth/register',{userName:'independent-ui-'+Date.now(),password:'independent-browser-private-2026'});const student=await call('/students',{name:'独立映射页面验收'}),f=await call('/content/fixture',{});await call(`/content/drafts/${f.id}:review`,{});const p=await call(`/content/drafts/${f.id}/preview`),original=await call(`/content/drafts/${f.id}:publish`,{previewHash:p.hash});await call(`/students/${student.id}/content/${original.id}:bind`,{});
 const cat=JSON.parse(original.payload),source=await call('/content/drafts',{title:'可编辑的独立映射来源',catalog:cat});await page.goto('/');await page.getByRole('button',{name:/内容与发布/}).click();const work=page.getByRole('region',{name:'独立映射草稿'});await work.getByText('建立一版映射草稿',{exact:true}).click();await work.getByLabel('独立映射来源').selectOption(source.id);await work.getByLabel('映射使用的正式能力库').selectOption(original.id);await work.getByLabel('查找映射对象').fill(cat.resources[0].title);await work.getByRole('radio',{name:'资源 · '+cat.resources[0].title,exact:true}).check();await work.getByRole('button',{name:'载入原映射',exact:true}).click();await expect(work.getByLabel('草稿教学覆盖权重')).toHaveValue('1');
 const reason='核对原资源覆盖 <script>window.__independentUnsafe=1</script>';await work.getByLabel('映射维护依据').fill(reason);await work.getByLabel('草稿教学覆盖权重').fill('0');await work.getByRole('button',{name:'保存独立映射草稿',exact:true}).click();await expect(work.getByRole('alert')).toContainText('课时/资源至少关联一个覆盖能力');expect((await call('/content/mapping-sets')).total).toBe(0);await expect(work.getByLabel('映射维护依据')).toHaveValue(reason);
 await work.getByLabel('草稿教学覆盖权重').fill('0.42');const newer=await call(`/content/drafts/${source.id}`,{title:source.title,catalog:cat},'PUT');await call('/content/mapping-sets');await work.getByRole('button',{name:'保存独立映射草稿',exact:true}).click();await expect(work.getByRole('alert')).toContainText('来源草稿已变化');await expect(work.getByLabel('草稿教学覆盖权重')).toHaveValue('0.42');expect((await call('/content/mapping-sets')).total).toBe(0);
 await work.getByRole('button',{name:'载入原映射',exact:true}).click();await work.getByLabel('草稿教学覆盖权重').fill('0.42');await work.getByLabel('映射维护依据').fill(reason);await work.getByRole('button',{name:'保存独立映射草稿',exact:true}).click();await expect(work.getByText('独立映射草稿已保存，尚未审核、发布或改变学生绑定。',{exact:true})).toBeVisible();const list=await call('/content/mapping-sets'),id=list.sets[0].setRevisionId,saved=await call('/content/mapping-sets/'+id);expect(saved.source.sourceDraftVersion).toBe(newer.version);expect(saved.source.reason).toBe(reason);expect(saved.set.reviewStatus).toBe('Draft');expect(saved.set.contentReviewRecordId).toBeNull();expect(saved.items[0].coverageWeight).toBe(.42);expect((await call('/students'))[0].activeReleaseId).toBe(original.id);expect(await page.evaluate(()=> (window as any).__independentUnsafe)).toBeUndefined();
 const row=page.locator('.content-row').filter({has:page.getByRole('heading',{name:saved.draft.title,exact:true})});await row.getByRole('button',{name:'审核答案与映射后发布',exact:true}).click();await expect.poll(async()=> (await call('/content/mapping-sets/'+id)).set.reviewStatus).toBe('ReviewedCatalog');const content=await call('/content'),newRelease=content.releases.find((r:any)=>r.id!==original.id),bindings=await call(`/content/releases/${newRelease.id}/mapping-sets`);expect(bindings.bindings.find((b:any)=>b.ownerType==='Resource'&&b.ownerId===cat.resources[0].id).setRevisionId).toBe(id);expect(content.releases.find((r:any)=>r.id===original.id).payload).toBe(original.payload);expect((await call('/students'))[0].activeReleaseId).toBe(original.id);
 await work.getByText('已保存的独立映射',{exact:true}).click();await work.getByRole('button',{name:'查看这版映射',exact:true}).click();await expect(work.getByText('已完成整份内容审核',{exact:false})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'test-results/independent-mapping-mobile.png',fullPage:true});
});
