import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
test('家长页面取消受控排队重建，保留依据后明确恢复原目标',async({page,context})=>{
  async function call(path:string,body?:unknown){const r=await context.request.fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'X-Learning-Request':'1','Idempotency-Key':randomUUID()},...(body===undefined?{}:{data:body})});expect(r.ok()).toBeTruthy();return r.json();}
  await call('/auth/register',{userName:'cancel-ui-'+Date.now(),password:'private-local-ui-2026'});const me=await call('/me'),student=await call('/students',{name:'取消重建界面受控验收'});
  const id=randomUUID(),job=randomUUID(),target=randomUUID();const payload=JSON.stringify({version:'assessment-rebuild/1',inputMode:'LatestCommittedUnderLock',familyId:me.family.id,studentId:student.id,requestedBy:me.actor.accountId,targetGenerationId:target,timeZone:student.timeZone,inputVersion:'assessment-input/2',evidenceRule:'evidence/1.1',masteryModel:'mastery/1.1',reviewRule:'review/1',baseGenerationId:null,baseInputHash:null,baseCursor:null});const hash=createHash('sha256').update(payload).digest('hex');
  // Explicit future-queued fixture keeps the browser cancellation deterministic; no fake execution or result.
  execFileSync('/opt/homebrew/opt/postgresql@16/bin/psql',['-At','-v','ON_ERROR_STOP=1','-c',`BEGIN; INSERT INTO "BackgroundJob" ("Id","FamilyId","CreatedAt","Type","StudentId","TargetGenerationId","InputRef","IdempotencyKey","InputPayload","InputHash","Status","AttemptCount","MaxAttempts","RetryRound","NextRunAt","LeaseSeconds","HeartbeatSeconds") VALUES ('${job}','${me.family.id}',clock_timestamp(),'AssessmentRebuild','${student.id}','${target}','${id}','cancel-ui:${job}','${payload}','${hash}','Queued',0,4,0,clock_timestamp()+interval '1 hour',30,5); INSERT INTO "AssessmentRebuildRequest" ("Id","FamilyId","CreatedAt","StudentId","JobId","RequestedBy","TargetGenerationId","Snapshot","SnapshotHash","Reason") VALUES ('${id}','${me.family.id}',clock_timestamp(),'${student.id}','${job}','${me.actor.accountId}','${target}','${payload}','${hash}','受控页面未来队列'); COMMIT;`],{env:{...process.env,PGHOST:'127.0.0.1',PGPORT:'55432',PGUSER:process.env.USER,PGDATABASE:'learning'}});
  await page.goto('/');await page.getByRole('button',{name:/证据与复习/}).click();const panel=page.getByRole('region',{name:'后台评估重建'});await expect(panel.getByRole('button',{name:'取消重建'})).toBeVisible();page.once('dialog',d=>d.accept('页面实际取消依据'));await panel.getByRole('button',{name:'取消重建'}).click();await expect(panel.getByText('已取消重建，当前评估保留。',{exact:true})).toBeVisible();expect((await call(`/students/${student.id}/export`)).rebuildResults).toHaveLength(0);
  await page.getByRole('button',{name:/辅助建库/}).click();const jobs=page.getByRole('region',{name:'后台任务保护'});await jobs.getByRole('button',{name:'刷新后台任务'}).click();await expect(jobs.getByRole('heading',{name:'评估重建 · 已取消'})).toBeVisible();
  await page.getByRole('button',{name:/证据与复习/}).click();page.once('dialog',d=>d.accept('核对后明确恢复原记录'));await panel.getByRole('button',{name:'核对后恢复重建'}).click();await expect(panel.getByText('已完成并应用重建结果。结果回执已保存，可刷新评估版本记录查看。',{exact:true})).toBeVisible();const data=await call(`/students/${student.id}/export`);expect(data.rebuildResults[0].generationId).toBe(target);expect(data.rebuildRequests[0].snapshot).toBe(payload);expect(data.backgroundJobs[0].retryRound).toBe(1);expect(data.studentAudit.some((a:any)=>a.action==='BackgroundJobCancellationRequested'&&JSON.parse(a.details).reason==='页面实际取消依据')).toBeTruthy();
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
