import { test, expect } from '@playwright/test';
import { localDate } from '../src/api';
test('家长发布 → 平板作答 → 证据复习', async ({page})=>{
  const name='browser-'+Date.now();
  await page.goto('/');
  await page.getByRole('button',{name:'首次使用？创建家庭'}).click();
  await page.getByLabel('家长用户名').fill(name);
  await page.getByLabel('家长密码').fill('test-browser-private-2026');
  await page.getByRole('button',{name:'创建私有家庭'}).click();
  await page.getByLabel('孩子昵称').fill('小步同学');
  await page.getByRole('button',{name:'创建学生',exact:true}).click();
  await expect(page.getByRole('heading',{name:'先审核，再交给孩子'})).toBeVisible();
  await page.getByRole('button',{name:'创建混合运算样例'}).click();
  await page.getByRole('button',{name:'审核答案与映射后发布'}).click();
  await page.getByRole('button',{name:'绑定当前学生'}).click();
  await page.getByRole('button',{name:/进度与计划/}).click();
  await page.getByRole('combobox', {name:'课时',exact:true}).selectOption({label:'小熊购物 · 乘加、乘减'});
  await page.getByRole('button',{name:'确认今天学到这里'}).click();
  await page.getByRole('button',{name:'生成草稿',exact:true}).click();
  await page.getByRole('button',{name:'确认并发布'}).click();
  await page.getByRole('button',{name:/今日学习/}).click();
  await expect(page.getByRole('button',{name:'进入孩子模式 ↗'})).toBeEnabled();
  await page.screenshot({path:'../../test-results/today-tablet.png',fullPage:true});
  await page.evaluate(()=>(window as any).__parentDraftSentinel='parent-workspace');
  await page.getByRole('button',{name:'进入孩子模式 ↗'}).click();
  await expect(page.getByRole('button',{name:/内容与发布/})).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).__parentDraftSentinel)).toBeUndefined();
  await page.getByRole('button',{name:/开始学习/}).click();
  await page.getByLabel('你的答案').fill('999');
  await page.getByRole('button',{name:'提交答案',exact:true}).click();
  await expect(page.getByText('已保存。先看看思路，再试一次。')).toBeVisible();
  await page.screenshot({path:'../../test-results/answer-tablet.png',fullPage:true});
  await page.getByRole('button',{name:'完成这个任务 ✓'}).click();
  await expect(page.getByText('已完成',{exact:true}).first()).toBeVisible();
  await page.getByRole('button',{name:'返回家长登录'}).click();
  await page.getByLabel('家长用户名').fill(name);
  await page.getByLabel('家长密码').fill('test-browser-private-2026');
  await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('button',{name:/证据与复习/}).click();
  await expect(page.getByText('错题复习 · R1')).toBeVisible();
  await page.getByRole('button',{name:'查看依据'}).first().click();
  await expect(page.getByRole('heading',{name:'证据明细'})).toBeVisible();
  await page.getByRole('button',{name:/家庭设置/}).click();
  await page.getByLabel('昵称',{exact:true}).fill('另一位同学');
  await page.getByRole('button',{name:'创建',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'切换学生'})).toHaveValue(/.+/);
  await expect(page.getByRole('combobox',{name:'切换学生'}).locator('option:checked')).toHaveText('另一位同学');
  await page.getByRole('button',{name:'绑定当前学生'}).click();
  await page.getByRole('button',{name:/进度与计划/}).click();
  await expect(page.getByRole('combobox',{name:'课时',exact:true})).toBeEnabled();
  await expect(page.getByRole('combobox',{name:'课时',exact:true})).toHaveValue('');
  await page.getByRole('combobox',{name:'切换学生'}).selectOption({label:'小步同学'});
  await expect(page.getByRole('button',{name:'确认今天学到这里'})).toBeEnabled();
  await expect(page.getByRole('combobox',{name:'课时',exact:true}).locator('option:checked')).toHaveText('小熊购物 · 乘加、乘减');
  await page.getByLabel('要纠正的记录').selectOption({index:1});
  await page.getByRole('combobox',{name:'课时',exact:true}).selectOption({label:'买文具 · 除加、除减'});
  await page.getByLabel('更正说明').fill('核对作业后确认实际已学到买文具');
  await page.getByRole('button',{name:'按上方所选课时更正'}).click();
  await expect(page.getByRole('combobox',{name:'课时',exact:true}).locator('option:checked')).toHaveText('买文具 · 除加、除减');
  await page.getByText(/进度更正记录 · 1/).click();
  await expect(page.getByText('核对作业后确认实际已学到买文具',{exact:true})).toBeVisible();
});

test('AT37 题面中的脚本和标签以普通文字显示', async ({page,context})=>{
  let etag='';
  async function call(path:string,data?:unknown,method=data===undefined?'GET':'POST'){
    const response=await context.request.fetch('/api/v1'+path,{method,headers:{'X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':etag},...(data===undefined?{}:{data})});
    expect(response.ok()).toBeTruthy();etag=response.headers()['etag']||etag;return response.json();
  }
  await call('/auth/register',{userName:'escaping-'+Date.now(),password:'browser-private-test-2026'});
  const student=await call('/students',{name:'安全题面验收'});
  const draft=await call('/content/fixture',{}),catalog=JSON.parse(draft.payload);
  const payload='<script>window.__unsafe=1</script><img src="/__attack" onerror="window.__unsafe=1">';
  catalog.questions.forEach((q:any)=>{q.stem=payload;});
  await call('/content/drafts/'+draft.id,{title:'题面转义验收',catalog},'PUT');
  await call('/content/drafts/'+draft.id+':review',{});
  const preview=await call('/content/drafts/'+draft.id+'/preview');
  const release=await call('/content/drafts/'+draft.id+':publish',{previewHash:preview.hash});
  await call('/students/'+student.id+'/content/'+release.id+':bind',{});
  const date=localDate(student.timeZone);
  await call('/students/'+student.id+'/school-progress/'+date+'/'+catalog.lessons[0].id,{},'PUT');
  const revision=await call('/students/'+student.id+'/plans/'+date+':generate',{});
  await call('/plans/'+revision.id+':publish',{previewHash:revision.inputHash});
  await call('/students/'+student.id+'/child-sessions',{});
  await page.goto('/');await page.getByRole('button',{name:/开始学习/}).click();
  await expect(page.getByText(payload,{exact:true})).toBeVisible();
  await expect(page.locator('img[src="/__attack"]')).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).__unsafe)).toBeUndefined();
  await page.getByLabel('你的答案').fill('999');
  await page.getByRole('button',{name:'提交答案',exact:true}).click();
  await expect(page.getByText('已保存。先看看思路，再试一次。')).toBeVisible();
});

test('空白草稿补齐能力、测量题和资源后发布进入孩子学习',async({page})=>{
  const name='authoring-'+Date.now(),password='private-authoring-2026';
  await page.goto('/');await page.getByRole('button',{name:'首次使用？创建家庭'}).click();
  await page.getByLabel('家长用户名').fill(name);await page.getByLabel('家长密码').fill(password);await page.getByRole('button',{name:'创建私有家庭'}).click();
  await page.getByLabel('孩子昵称').fill('内容编辑验收');await page.getByRole('button',{name:'创建学生',exact:true}).click();
  await page.getByRole('button',{name:'新建空白内容草稿'}).click();
  await page.getByRole('button',{name:'新增独立能力'}).click();
  const kc=page.locator('[aria-label="能力 1"]');
  await kc.getByLabel('能力名称').fill('确定乘加运算顺序');
  await kc.getByLabel('独立可测行为').fill('独立先算乘法再算加法');
  await kc.getByLabel('测量边界与排除范围').fill('不含括号，表内乘法，不推断阅读能力');
  await page.getByRole('button',{name:'保存并退回待审核'}).click();
  await page.getByRole('button',{name:'审核答案与映射后发布'}).click();
  await expect(page.getByText(/没有经过审核的测量题/)).toBeVisible();
  await page.getByRole('button',{name:'编辑',exact:true}).click();
  await page.getByRole('button',{name:'新增测量题'}).click();
  const question=page.locator('[aria-label="题目 1"]');
  await question.getByLabel('题干',{exact:true}).fill('3 + 4 × 2 = ?');
  await question.getByLabel('参考答案').fill('11');await question.getByLabel('讲解说明').fill('先算4×2=8，再算3+8=11。');
  await question.getByLabel('提示内容').fill('先看一看哪一步是乘法。');
  await page.getByRole('button',{name:'新增讲解资源'}).click();
  const resource=page.locator('[aria-label="资源 1"]');
  await resource.getByLabel('资源名称').fill('乘加顺序纸笔示范');
  await resource.getByLabel('纸笔材料与执行说明').fill('准备纸笔，家长示范2+3×4，孩子圈出先算的步骤。');
  await page.getByRole('button',{name:'新增课时'}).click();
  await page.locator('[aria-label="课时 1"]').getByLabel('课时名称').fill('自编混合运算小练习');
  await expect(page.getByRole('button',{name:'审核答案与映射后发布'})).toBeDisabled();
  await page.screenshot({path:'../../test-results/content-editor-tablet.png',fullPage:true});
  await page.getByRole('button',{name:'保存并退回待审核'}).click();
  await page.getByRole('button',{name:'审核答案与映射后发布'}).click();
  await page.getByRole('button',{name:'绑定当前学生'}).click();
  await page.getByRole('button',{name:/进度与计划/}).click();
  await page.getByRole('combobox',{name:'课时',exact:true}).selectOption({label:'自编混合运算小练习'});
  await page.getByRole('button',{name:'确认今天学到这里'}).click();await page.getByRole('button',{name:'生成草稿',exact:true}).click();await page.getByRole('button',{name:'确认并发布'}).click();
  await page.getByRole('button',{name:/今日学习/}).click();await page.getByRole('button',{name:'进入孩子模式 ↗'}).click();await page.getByRole('button',{name:/开始学习/}).click();
  await expect(page.getByText('3 + 4 × 2 = ?',{exact:true})).toBeVisible();await page.getByLabel('你的答案').fill('11');await page.getByRole('button',{name:'提交答案',exact:true}).click();
  await expect(page.getByText('这次做对了！',{exact:true})).toBeVisible();await page.getByRole('button',{name:'完成这个任务 ✓'}).click();
  await page.getByRole('button',{name:'返回家长登录'}).click();await page.getByLabel('家长用户名').fill(name);await page.getByLabel('家长密码').fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await page.getByRole('button',{name:/内容与发布/}).click();await page.getByRole('button',{name:'创建新修订',exact:true}).click();await page.getByRole('button',{name:'编辑',exact:true}).click();
  await expect(page.locator('[aria-label="能力 1"]').getByLabel('独立可测行为')).toHaveAttribute('readonly','');
});

test('建库候选保留引用，审核草稿可继续编辑并发布',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'首次使用？创建家庭'}).click();
  await page.getByLabel('家长用户名').fill('builder-trace-'+Date.now());await page.getByLabel('家长密码').fill('private-builder-2026');await page.getByRole('button',{name:'创建私有家庭'}).click();
  await page.getByLabel('孩子昵称').fill('建库追溯验收');await page.getByRole('button',{name:'创建学生',exact:true}).click();
  await page.getByRole('button',{name:/辅助建库/}).click();
  const quote='有小括号时，先计算小括号里的加减，再计算除法。';
  await page.getByLabel('来源标题').fill('家长原创运算说明');await page.getByLabel('文本内容').fill(quote);await page.getByRole('button',{name:'保存来源'}).click();await page.getByRole('button',{name:'验证候选流程'}).click();
  await expect(async()=>{await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.getByRole('button',{name:'接受为新草稿'})).toBeVisible();}).toPass();
  await page.getByLabel('名称',{exact:true}).fill('先算小括号');await page.getByLabel('可测行为',{exact:true}).fill('独立计算一层小括号内的加减，再计算除法');await page.getByLabel('能力边界').fill('不含嵌套，不推断建模能力');
  await page.getByRole('button',{name:'接受为新草稿'}).click();await page.getByRole('button',{name:'查看引用与审核'}).click();
  const trace=page.getByRole('region',{name:'内容来源追溯'});
  // The named section may have an implicit region only when its accessible name is present.
  await expect(trace.getByText(quote,{exact:true})).toBeVisible();await expect(trace.getByText('家长原创运算说明',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'关闭记录'}).click();await page.getByRole('button',{name:'继续编辑审核草稿'}).click();await expect(page.getByRole('heading',{name:'编辑内容草稿'})).toBeVisible();
  await page.getByRole('button',{name:'新增测量题'}).click();const q=page.locator('[aria-label="题目 1"]');await q.getByLabel('题干',{exact:true}).fill('(8 + 4) ÷ 3 = ?');await q.getByLabel('参考答案').fill('4');await q.getByLabel('讲解说明').fill('先算8+4=12，再算12÷3=4。');
  await page.getByRole('button',{name:'新增课时'}).click();await page.locator('[aria-label="课时 1"]').getByLabel('课时名称').fill('原创小括号练习');await page.getByRole('button',{name:'保存并退回待审核'}).click();await page.getByRole('button',{name:'审核答案与映射后发布'}).click();
  await page.getByText('能力定义与来源',{exact:true}).click();await page.getByRole('button',{name:'查看能力来源'}).click();await expect(trace.getByText(quote,{exact:true})).toBeVisible();
});

test('家长安排步骤题并保留未观察步骤',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'首次使用？创建家庭'}).click();
  await page.getByLabel('家长用户名').fill('browser-steps-'+Date.now());await page.getByLabel('家长密码').fill('steps-browser-private-2026');await page.getByRole('button',{name:'创建私有家庭'}).click();
  await page.getByLabel('孩子昵称').fill('步骤同学');await page.getByRole('button',{name:'创建学生',exact:true}).click();
  await page.getByRole('button',{name:'创建混合运算样例'}).click();await expect(page.getByRole('button',{name:'审核答案与映射后发布'})).toBeVisible();
  await page.evaluate(async()=>{
    const response=await fetch('/api/v1/content');const content=await response.json();const draft=content.drafts[0];const catalog=JSON.parse(draft.payload);const q=catalog.questions[16];q.policy='ObservedSteps';q.type='MultiStep';q.mappings=[{kcId:catalog.kcs[8].id,role:'Primary',share:.5,mode:'StepObserved',step:'列式'},{kcId:catalog.kcs[0].id,role:'Secondary',share:.5,mode:'StepObserved',step:'运算顺序'}];
    const saved=await fetch('/api/v1/content/drafts/'+draft.id,{method:'PUT',headers:{'Content-Type':'application/json','X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':response.headers.get('etag')!},body:JSON.stringify({title:draft.title,catalog})});if(!saved.ok)throw new Error(await saved.text());
  });
  await page.getByRole('button',{name:/进度与计划/}).click();await page.getByRole('button',{name:/内容与发布/}).click();await page.getByRole('button',{name:'审核答案与映射后发布'}).click();await page.getByRole('button',{name:'绑定当前学生'}).click();
  await page.getByRole('button',{name:/进度与计划/}).click();await page.getByRole('button',{name:'生成草稿',exact:true}).click();
  await page.getByLabel('任务类型').selectOption('Practice');
  const choice=await page.getByLabel('计划版本题目').locator('option').filter({hasText:'家长观察步骤'}).first().getAttribute('value');
  await page.getByLabel('计划版本题目').selectOption(choice!);await page.getByLabel('追加必做任务').fill('观察列式过程');await page.getByLabel('分钟',{exact:true}).fill('5');await page.getByLabel('执行说明').fill('先在纸上列式，再写计算过程');await page.getByRole('button',{name:'加入草稿'}).click();
  await page.getByRole('button',{name:'确认并发布'}).click();await page.getByRole('button',{name:/今日学习/}).click();
  await page.getByRole('button',{name:/开始学习/}).click();await page.getByLabel('你的答案').fill('只完成了列式');await page.getByRole('button',{name:'提交答案',exact:true}).click();await page.getByRole('button',{name:'完成这个任务 ✓'}).click();
  await page.getByRole('button',{name:/证据与复习/}).click();await page.getByRole('button',{name:'查看题目并判分'}).click();
  await expect(page.getByRole('heading',{name:'核对题目与观察步骤'})).toBeVisible();await page.getByLabel('整题判分').selectOption('Partial');
  await page.getByLabel(/^列式 ·/).selectOption('Correct');await expect(page.getByLabel(/^运算顺序 ·/)).toHaveValue('Unknown');
  await page.getByLabel('判分依据').fill('纸上列式正确，计算没有观察到');await page.getByRole('button',{name:'预览判分影响'}).click();await expect(page.getByText('待确认 → 部分正确')).toBeVisible();await page.getByRole('button',{name:'确认更正并重算'}).click();
  await expect(page.getByRole('heading',{name:'核对题目与观察步骤'})).toHaveCount(0);await expect(page.getByText('第 1 次 · 部分正确')).toBeVisible();
});
