import {test,expect} from '@playwright/test';
test('连续在线作答保持当前评估版本，原证据与家长重建回执可核对',async({page,context})=>{
  let etag='';async function call(path:string,body?:unknown){const r=await context.request.fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'X-Learning-Request':'1','If-Match':etag,'Idempotency-Key':crypto.randomUUID()},...(body===undefined?{}:{data:body})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json();}
  await call('/auth/register',{userName:'online-ui-'+Date.now(),password:'online-browser-private-2026'});const student=await call('/students',{name:'在线追加界面验收'});
  const draft=await call('/content/fixture',{});await call(`/content/drafts/${draft.id}:review`,{});const preview=await call(`/content/drafts/${draft.id}/preview`);const release=await call(`/content/drafts/${draft.id}:publish`,{previewHash:preview.hash});await call(`/students/${student.id}/content/${release.id}:bind`,{});
  const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date());const plan=await call(`/students/${student.id}/plans/${day}:generate`,{});const questions=JSON.parse(release.payload).questions.slice(0,2);const tasks=[];
  for(const q of questions)tasks.push(await call(`/plans/${plan.id}/tasks`,{title:'连续在线题',minutes:5,resourceRef:'本地验收',type:'Practice',questionId:q.id}));
  const view=await call(`/students/${student.id}/plans/${day}`);await call(`/plans/${plan.id}:publish`,{previewHash:view.revision.inputHash,confirmWarnings:true});
  async function answer(index:number){await call(`/tasks/${tasks[index].id}:transition`,{status:'InProgress'});const session=await call(`/tasks/${tasks[index].id}/sessions`,{});await call(`/sessions/${session.sessionId}/attempts`,{clientSubmissionId:crypto.randomUUID(),answer:questions[index].answer});await expect.poll(async()=> (await call(`/students/${student.id}/mastery`)).pending).toBe(0);}
  await answer(0);const original=await call(`/students/${student.id}/export`);await page.goto('/');await page.getByRole('button',{name:/证据与复习/}).click();const history=page.getByRole('region',{name:'评估版本记录'});await expect(history.getByText('当前生效 · 1 条评估上下文')).toBeVisible();
  const rebuild=page.getByRole('region',{name:'后台评估重建'});await rebuild.getByLabel('重建依据').fill('核对连续作答前的评估');await rebuild.getByRole('button',{name:'提交后台重建'}).click();await expect(rebuild.getByText('已核对并复用已有评估。结果回执已保存，可刷新评估版本记录查看。',{exact:true})).toBeVisible();const before=await call(`/students/${student.id}/export`);
  await answer(1);await page.getByRole('button',{name:'刷新后台结果',exact:true}).click();await expect(history.getByText('当前生效 · 2 条评估上下文')).toBeVisible();await expect(history.getByLabel('选择评估版本（最近50版）').locator('option')).toHaveCount(2);
  const after=await call(`/students/${student.id}/export`);expect(after.generations).toHaveLength(1);expect(after.generations[0].id).toBe(original.generations[0].id);expect(after.generations[0].calculationMode).toBe('OnlineAppend');expect(after.generations[0].processedInputCount).toBe(1);expect(after.assessmentCheckpoints).toHaveLength(2);expect(after.assessmentContexts).toHaveLength(2);const sync=await call(`/students/${student.id}/assessment-consumption`);expect(sync.pendingModern).toBe(0);expect(sync.cursor.lastEventSequence).toBeGreaterThan(original.assessmentConsumerCursors[0].lastEventSequence);expect(sync.cursor.generationId).toBe(after.generations[0].id);const lastReceipt=after.consumerReceipts.find((r:any)=>r.id===sync.cursor.lastReceiptId);expect(lastReceipt.inputHash).toBe(sync.cursor.inputHash);const application=after.domainEvents.find((e:any)=>e.id===sync.cursor.lastAppliedEventId);const advance=JSON.parse(application.payload).data.consumption;expect(advance.priorSequence).toBe(original.assessmentConsumerCursors[0].lastEventSequence);expect(advance.newEventIds).toHaveLength(1);expect(advance.throughSequence).toBe(sync.cursor.lastEventSequence);
  for(const evidence of original.evidence)expect(after.evidence.find((e:any)=>e.id===evidence.id)).toEqual(evidence);for(const c of original.assessmentContexts)expect(after.assessmentContexts.find((x:any)=>x.id===c.id)).toEqual(c);
  expect(after.rebuildResults).toEqual(before.rebuildResults);expect(after.rebuildResults[0].checkpointId).toBe(original.assessmentCheckpoints[0].id);expect(after.rebuildResults[0].inputHash).not.toBe(after.generations[0].inputHash);for(const receipt of after.consumerReceipts){const checkpoint=after.assessmentCheckpoints.find((c:any)=>c.id===receipt.checkpointId);expect(checkpoint.inputHash).toBe(receipt.inputHash);expect(checkpoint.generationId).toBe(receipt.generationId);}
  const savedPlan=after.revisions.find((r:any)=>r.id===plan.id);expect(JSON.parse(savedPlan.projectionSnapshot).generationId).toBeNull();await page.getByRole('button',{name:/进度与计划/}).click();await expect(page.getByText('生成时尚无已完成评估，本版依据学校进度和家长目标安排。 已保存当时的评估依据。')).toBeVisible();await page.getByRole('button',{name:'重新生成草稿',exact:true}).click();await expect(page.getByText('本版依据生成时已同步的学习结果安排。 已保存当时的评估依据。')).toBeVisible();const currentPlan=await call(`/students/${student.id}/plans/${day}`);const captured=JSON.parse(currentPlan.revision.projectionSnapshot);expect(captured.generationId).toBe(after.generations[0].id);expect(captured.assessmentEventSequence).toBe(sync.cursor.lastEventSequence);const finalExport=await call(`/students/${student.id}/export`);expect(finalExport.revisions.find((r:any)=>r.id===plan.id).projectionSnapshot).toBe(savedPlan.projectionSnapshot);
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
