import {test,expect} from '@playwright/test';
import {localDate} from '../src/api';
test('真实原因调整可选任务，失败不伪装保存，固定任务保留',async({page,context})=>{
  let etag='';async function call(path:string,data?:unknown,method=data===undefined?'GET':'POST'){const r=await context.request.fetch('/api/v1'+path,{method,headers:{'X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':etag},...(data===undefined?{}:{data})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json();}
  await call('/auth/register',{userName:'adjust-ui-'+Date.now(),password:'adjust-private-ui-2026'});const s=await call('/students',{name:'调整界面验收'});const d=await call('/content/fixture',{});const catalog=JSON.parse(d.payload);await call('/content/drafts/'+d.id+':review',{});const p=await call('/content/drafts/'+d.id+'/preview');const r=await call('/content/drafts/'+d.id+':publish',{previewHash:p.hash});await call('/students/'+s.id+'/content/'+r.id+':bind',{});const today=localDate('Asia/Shanghai');await call('/students/'+s.id+'/school-progress/'+today+'/'+catalog.lessons[0].id,{},'PUT');let rev=await call('/students/'+s.id+'/plans/'+today+':generate',{});
  const mandatory=await call('/plans/'+rev.id+'/tasks',{title:'必须保留的学校作业',type:'Schoolwork',minutes:1,mandatory:true,resourceRef:'完成规定练习'});const completed=await call('/plans/'+rev.id+'/tasks',{title:'已完成纸笔活动',type:'Resource',minutes:1,mandatory:false,resourceRef:'示范一道原创题'});rev=(await call('/students/'+s.id+'/plans/'+today)).revision;await call('/plans/'+rev.id+':publish',{previewHash:rev.inputHash});await call('/tasks/'+completed.id+':transition',{status:'InProgress'});await call('/tasks/'+completed.id+':transition',{status:'Completed'});await call('/students/'+s.id+'/availability/'+today,{minutes:25,reserved:0},'PUT');await call('/students/'+s.id+'/plans/'+today+':generate',{});
  await page.goto('/');await page.getByRole('button',{name:/进度与计划/}).click();const rows=page.locator('.plan-panel .task-row');const count=await rows.count();const optional=rows.filter({has:page.getByRole('button',{name:'锁定',exact:true})}).first();const title=await optional.locator('h3').innerText();const row=rows.filter({has:page.getByRole('heading',{name:title,exact:true})}).first();
  await expect(row.getByRole('button',{name:'锁定',exact:true})).toBeDisabled();await page.getByLabel('本次计划调整原因').fill('这项练习先保留，避免重生成时丢失');await row.getByRole('button',{name:'锁定',exact:true}).click();await expect(row.getByRole('button',{name:'解除锁定',exact:true})).toBeVisible();
  await page.getByLabel('本次计划调整原因').fill('先解锁，准备减少可选练习');await expect(row.getByRole('button',{name:'移除可选任务',exact:true})).toBeDisabled();
  await page.route('**/api/v1/plans/*:adjust',async route=>route.continue({headers:{...route.request().headers(),'if-match':'"0"'}}),{times:1});await row.getByRole('button',{name:'解除锁定',exact:true}).click();await expect(page.getByText('数据已更新，请刷新后重新确认。',{exact:true})).toBeVisible();await expect(row.getByRole('button',{name:'解除锁定',exact:true})).toBeVisible();await expect(rows).toHaveCount(count);
  await row.getByRole('button',{name:'解除锁定',exact:true}).click();await expect(row.getByRole('button',{name:'锁定',exact:true})).toBeVisible();await page.getByLabel('本次计划调整原因').fill('今天学校作业较多，减少这项可选练习');await row.getByRole('button',{name:'移除可选任务',exact:true}).click();await expect(rows).toHaveCount(count-1);
  await page.getByLabel('本次计划调整原因').fill('确认固定任务仍保留');await expect(rows.filter({has:page.getByRole('heading',{name:'必须保留的学校作业',exact:true})}).getByRole('button',{name:'移除可选任务',exact:true})).toBeDisabled();await expect(rows.filter({has:page.getByRole('heading',{name:'已完成纸笔活动',exact:true})}).getByRole('button',{name:'移除可选任务',exact:true})).toBeDisabled();
  const result=await call('/students/'+s.id+'/plans/'+today);expect(result.tasks.some((t:any)=>t.id===mandatory.id&&t.mandatory)).toBeTruthy();expect(result.tasks.some((t:any)=>t.id===completed.id&&t.status==='Completed')).toBeTruthy();
  const openedVersion=etag;const ids=result.tasks.map((t:any)=>t.id).reverse();await call('/plans/'+result.revision.id+':adjust',{taskIds:ids,lockedIds:result.tasks.filter((t:any)=>t.locked).map((t:any)=>t.id),reason:'另一页面调整最新顺序'});const newerVersion=etag;expect(newerVersion).not.toBe(openedVersion);
  const poll=await page.waitForResponse(r=>r.url().endsWith('/api/v1/operations')&&r.status()===200&&r.headers()['etag']===newerVersion);await poll.finished();
  await page.getByLabel('本次计划调整原因').fill('旧页面尝试改变锁定');const staleRequest=page.waitForRequest(r=>r.url().endsWith(':adjust')&&r.method()==='POST');await rows.filter({has:page.getByRole('button',{name:'锁定',exact:true})}).first().getByRole('button',{name:'锁定',exact:true}).click();expect((await staleRequest).headers()['if-match']).toBe(openedVersion);await expect(page.getByText('数据已更新，请刷新后重新确认。',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'刷新当前计划',exact:true}).click();await expect(async()=>expect(await rows.locator('h3').allTextContents()).toEqual(result.tasks.map((t:any)=>t.title).reverse())).toPass();
  await page.screenshot({path:'../../test-results/plan-adjustment-tablet.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'../../test-results/plan-adjustment-phone.png',fullPage:true});
});
