import {test,expect} from '@playwright/test';

test('资源页面修改创建新修订，审核发布后保留旧资源快照',async({page,context})=>{
  let etag='';
  async function call(path:string,body?:unknown){
    const response=await context.request.fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':etag},...(body===undefined?{}:{data:body})});
    expect(response.ok()).toBeTruthy();etag=response.headers()['etag']||etag;return response.json();
  }
  await call('/auth/register',{userName:'resource-ui-'+Date.now(),password:'resource-private-browser-2026'});
  await call('/students',{name:'资源修订界面验收'});
  const fixture=await call('/content/fixture',{});const catalog=JSON.parse(fixture.payload);const r=catalog.resources[0];catalog.mappingCoverage=[{ownerType:'Resource',ownerId:r.id,kcId:r.kcIds[0],role:'Primary',evidenceMode:'None',step:null,evidenceShare:0,coverageWeight:.37,sourceSetRevisionId:null,origin:'Explicit'}];const draft=await call('/content/drafts',{title:'带明确资源覆盖权重的草稿',catalog});
  await call('/content/drafts/'+draft.id+':review',{});
  const preview=await call('/content/drafts/'+draft.id+'/preview');
  const old=await call('/content/drafts/'+draft.id+':publish',{previewHash:preview.hash});
  const original=JSON.parse(old.payload).resources[0];
  await page.goto('/');
  await page.getByRole('button',{name:/内容与发布/}).click();
  await page.getByRole('button',{name:'创建新修订',exact:true}).click();
  await page.locator('.content-row').filter({has:page.getByRole('heading',{name:'带明确资源覆盖权重的草稿 · 修订',exact:true})}).getByRole('button',{name:'编辑',exact:true}).click();
  const editor=page.getByRole('region',{name:'内容草稿编辑器'});
  const resource=editor.locator('[aria-label="资源 1"]');
  const instruction='核对纸笔讲解步骤 <script>window.__resourceUnsafe=1</script>';
  await resource.getByLabel('纸笔材料与执行说明').fill(instruction);
  await resource.getByLabel('预计分钟').fill('12');
  await expect(resource.getByLabel('教学覆盖权重').first()).toHaveValue('0.37');
  await expect(resource.getByText(/继承既有映射权重/).first()).toBeVisible();
  await resource.getByLabel('教学覆盖权重').first().fill('0.42');
  await editor.getByRole('button',{name:'保存并退回待审核'}).click();
  await expect(page.getByText('草稿已保存，需要重新审核。',{exact:true})).toBeVisible();
  const saved=(await call('/content')).drafts.find((d:any)=>d.title==='带明确资源覆盖权重的草稿 · 修订');
  const coverage=JSON.parse(saved.payload).mappingCoverage.find((x:any)=>x.ownerType==='Resource'&&x.ownerId===r.id&&x.kcId===r.kcIds[0]);
  expect(coverage).toMatchObject({coverageWeight:.42,origin:'Explicit',sourceSetRevisionId:null});
  const changed=JSON.parse(saved.payload).resources[0];
  expect(changed.id).toBe(original.id);expect(changed.revisionId).not.toBe(original.revisionId);
  expect(changed.paperReference).toBe(instruction);expect(changed.minutes).toBe(12);
  const revisedRow=page.locator('.content-row').filter({has:page.getByRole('heading',{name:'带明确资源覆盖权重的草稿 · 修订',exact:true})});
  await revisedRow.getByRole('button',{name:'查看待审映射',exact:true}).click();
  const pending=page.getByRole('region',{name:'待审映射预览'});
  await expect(pending.getByRole('button',{name:'下一页待审映射'})).toBeEnabled();
  await pending.getByRole('button',{name:'下一页待审映射'}).click();
  await expect(pending.getByText(/教学覆盖：0.42 · 作答证据份额：0/)).toBeVisible();
  await revisedRow.getByRole('button',{name:'审核答案与映射后发布',exact:true}).click();
  await expect(page.getByText('内容已发布，可以绑定学生。',{exact:true})).toBeVisible();
  const releases=(await call('/content')).releases;
  expect(releases).toHaveLength(2);expect(releases.find((r:any)=>r.id===old.id).payload).toBe(old.payload);
  const newer=releases.find((r:any)=>r.id!==old.id);expect(JSON.parse(newer.payload).resources[0]).toEqual(changed);
  const mappings=await call('/content/releases/'+newer.id+'/mapping-sets');
  const binding=mappings.bindings.find((b:any)=>b.ownerType==='Resource'&&b.ownerId===r.id);
  expect(mappings.items.find((i:any)=>i.setRevisionId===binding.setRevisionId&&i.kcId===r.kcIds[0]).coverageWeight).toBe(.42);
  expect(await page.evaluate(()=>(window as any).__resourceUnsafe)).toBeUndefined();
  // A later family read must not replace the version captured when editing began.
  const sourceRow=page.locator('.content-row').filter({has:page.getByRole('heading',{name:fixture.title,exact:true})});
  await sourceRow.getByRole('button',{name:'编辑',exact:true}).click();
  await editor.locator('[aria-label="资源 1"]').getByLabel('资源名称').fill('保留过期编辑的本地修改');
  await call('/students',{name:'另一页面的版本修改'});
  await sourceRow.getByRole('button',{name:'查看审核记录',exact:true}).click();
  await expect(page.getByRole('region',{name:'完整内容审核记录'}).getByText('尚无独立审核快照。旧版本的历史审核内容未补造。')).toBeVisible();
  await editor.getByRole('button',{name:'保存并退回待审核'}).click();
  await expect(page.getByRole('alert')).toContainText('数据已更新');
  await expect(editor.locator('[aria-label="资源 1"]').getByLabel('资源名称')).toHaveValue('保留过期编辑的本地修改');
  const unchanged=(await call('/content')).drafts.find((d:any)=>d.id===fixture.id);
  expect(unchanged.payload).toBe(fixture.payload);expect(unchanged.version).toBe(fixture.version);
  await editor.getByRole('button',{name:'取消',exact:true}).click();
});
