import {test,expect} from '@playwright/test';
test('家长真实核对目标变化、保留或采用实际目标，并重新安排原目标',async({page,context})=>{
  test.skip(!process.env.REVIEW_CONFIRM_STUDENT,'隔离确认验收 --browser 提供真实作答与映射更正');
  const sid=process.env.REVIEW_CONFIRM_STUDENT!,actual=process.env.REVIEW_CONFIRM_ACTUAL!,original=process.env.REVIEW_CONFIRM_ORIGINAL!;let etag='';
  async function call(path:string,body?:unknown){const r=await context.request.fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':etag},...(body===undefined?{}:{data:body})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json();}
  await call('/auth/login',{userName:process.env.REVIEW_CONFIRM_USERNAME,password:process.env.REVIEW_CONFIRM_PASSWORD});await page.goto('/');await page.getByLabel('切换学生').selectOption(sid);await page.getByRole('button',{name:/证据与复习/}).click();const card=page.getByRole('region',{name:'复习目标变化确认'});
  await expect(card.getByText(/原任务和历史结果保留/)).toBeVisible();const before=await call('/students/'+sid+'/export');
  async function settle(adopted:boolean){await expect.poll(async()=>{const m=await call('/students/'+sid+'/mastery');if(m.pending)return 'Pending';const rows=await call('/students/'+sid+'/reviews');expect(rows.find((r:any)=>r.targetId===original).stage).toBe('R1');return rows.find((r:any)=>r.targetId===actual).stage;}).toBe(adopted?'LowFrequency':'R1');}
  await card.getByRole('button',{name:'重新核对选择'}).click();await card.getByLabel('处理选择').selectOption('KeepOriginal');await card.getByLabel('家长确认依据').fill('浏览器实际核对：先保留原目标');await card.getByRole('button',{name:'预览目标确认影响'}).click();await expect(card.getByText(/原目标继续保持待复习/)).toBeVisible();await card.getByRole('button',{name:'确认选择并后台重算'}).click();await expect(card.getByText('依据：浏览器实际核对：先保留原目标',{exact:true})).toBeVisible();await settle(false);
  await card.getByRole('button',{name:'重新核对选择'}).click();await card.getByLabel('处理选择').selectOption('AdoptMeasuredTarget');await card.getByLabel('实际测量目标',{exact:true}).selectOption(actual);await card.getByLabel('家长确认依据').fill('浏览器实际核对：本次按有效映射目标复测');await card.getByRole('button',{name:'预览目标确认影响'}).click();await expect(card.getByText(/不转移掌握度/).last()).toBeVisible();await card.getByRole('button',{name:'确认选择并后台重算'}).click();await expect(card.getByText('依据：浏览器实际核对：本次按有效映射目标复测',{exact:true})).toBeVisible();await settle(true);await expect(page.getByText(/还有 \d+ 条结果正在后台处理/)).not.toBeVisible();
  const after=await call('/students/'+sid+'/export');expect(after.tasks).toEqual(before.tasks);expect(after.attempts).toEqual(before.attempts);expect(after.gradings).toEqual(before.gradings);expect(after.reviewTargetConfirmations.slice(0,before.reviewTargetConfirmations.length)).toEqual(before.reviewTargetConfirmations);expect(after.reviewTargetConfirmations.length).toBe(before.reviewTargetConfirmations.length+2);
  await card.screenshot({path:'test-results/review-target-panel-tablet.png'});await page.screenshot({path:'test-results/review-target-tablet.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await expect(card.getByRole('button',{name:'去安排明日复习'})).toBeVisible();await card.screenshot({path:'test-results/review-target-panel-phone.png'});await page.screenshot({path:'test-results/review-target-phone.png',fullPage:true});
  await card.getByRole('button',{name:'去安排明日复习'}).click();const tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+1);await expect(page.getByLabel('计划日期')).toHaveValue(tomorrow.toISOString().slice(0,10));await page.getByRole('button',{name:/^(重新)?生成草稿$/}).click();await expect(page.getByRole('button',{name:'确认并发布',exact:true})).toBeVisible();await page.getByRole('button',{name:'确认并发布',exact:true}).click();await expect.poll(async()=>{const s=await call('/students/'+sid+'/export');return s.revisions.filter((r:any)=>r.status==='Published').length;}).toBeGreaterThan(before.revisions.filter((r:any)=>r.status==='Published').length);
});
