import {test,expect} from '@playwright/test';
import {localDate} from '../src/api';
test('往周日期导航和投入分期，窄屏可操作',async({page})=>{
  const today=localDate('Asia/Shanghai');const past=new Date(today+'T12:00:00Z');past.setUTCDate(past.getUTCDate()-10);const old=past.toISOString().slice(0,10);
  await page.goto('/');await page.getByRole('button',{name:'首次使用？创建家庭'}).click();await page.getByLabel('家长用户名').fill('weekly-ui-'+Date.now());await page.getByLabel('家长密码').fill('weekly-private-browser-2026');await page.getByRole('button',{name:'创建私有家庭'}).click();await page.getByLabel('孩子昵称').fill('往周界面验收');await page.getByRole('button',{name:'创建学生',exact:true}).click();await page.getByRole('button',{name:/每周回顾/}).click();
  await page.getByLabel('实际投入（分钟，家长填写）').fill('3.5');await page.getByRole('button',{name:'记录实际投入',exact:true}).click();await expect(page.getByText('所选一周已记录 1 天 · 日常维护 3.5 分钟 · 内容审核 0 分钟')).toBeVisible();
  await page.getByLabel('投入日期').fill(old);await page.getByLabel('投入类别').selectOption('ContentReview');await page.getByLabel('实际投入（分钟，家长填写）').fill('12');await page.getByRole('button',{name:'记录实际投入',exact:true}).click();
  await page.getByLabel('周报结束日期').fill(old);await page.getByRole('button',{name:'查看所选一周',exact:true}).click();await expect(page.getByText('所选一周已记录 1 天 · 日常维护 0 分钟 · 内容审核 12 分钟')).toBeVisible();await expect(page.getByText(/统计日期：.*至/)).toContainText(old);
  await page.getByRole('button',{name:'前一周',exact:true}).click();await expect(page.getByText('所选一周尚未记录投入，暂不能评价家长维护成本。')).toBeVisible();await page.getByRole('button',{name:'后一周',exact:true}).click();await expect(page.getByText('所选一周已记录 1 天 · 日常维护 0 分钟 · 内容审核 12 分钟')).toBeVisible();
  await page.screenshot({path:'../../test-results/weekly-report-tablet.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'../../test-results/weekly-report-phone.png',fullPage:true});
  await page.getByRole('button',{name:'返回最近一周',exact:true}).click();await expect(page.getByText('所选一周已记录 1 天 · 日常维护 3.5 分钟 · 内容审核 0 分钟')).toBeVisible();
});
test('周报任务与调整理由可回看且普通文字显示',async({page,context})=>{
  let etag='';async function call(path:string,data?:unknown,method=data===undefined?'GET':'POST'){const r=await context.request.fetch('/api/v1'+path,{method,headers:{'X-Learning-Request':'1','Idempotency-Key':crypto.randomUUID(),'If-Match':etag},...(data===undefined?{}:{data})});expect(r.ok()).toBeTruthy();etag=r.headers()['etag']||etag;return r.json();}
  await call('/auth/register',{userName:'weekly-reason-ui-'+Date.now(),password:'weekly-reason-private-2026'});const s=await call('/students',{name:'调整原因界面验收'});const draft=await call('/content/fixture',{});const catalog=JSON.parse(draft.payload);await call('/content/drafts/'+draft.id+':review',{});const preview=await call('/content/drafts/'+draft.id+'/preview');const release=await call('/content/drafts/'+draft.id+':publish',{previewHash:preview.hash});await call('/students/'+s.id+'/content/'+release.id+':bind',{});
  const today=localDate('Asia/Shanghai');await call('/students/'+s.id+'/school-progress/'+today+'/'+catalog.lessons[0].id,{},'PUT');const rev=await call('/students/'+s.id+'/plans/'+today+':generate',{});await call('/plans/'+rev.id+':publish',{previewHash:rev.inputHash});await call('/students/'+s.id+'/availability/'+today,{minutes:15,reserved:0},'PUT');const next=await call('/students/'+s.id+'/plans/'+today+':generate',{});const view=await call('/students/'+s.id+'/plans/'+today);const ids=view.tasks.map((t:any)=>t.id).reverse();const reason='家长调整顺序 <script>window.__unsafeWeekly=1</script>';const changed=await call('/plans/'+next.id+':adjust',{taskIds:ids,lockedIds:[],reason});await call('/plans/'+next.id+':publish',{previewHash:changed.inputHash});
  await page.goto('/');await page.getByRole('button',{name:/每周回顾/}).click();await page.getByText(/查看原始、最终及中间版本任务/).click();await expect(page.getByText(/最初计划/).first()).toBeVisible();await page.getByText('查看家长调整原因（1条）',{exact:true}).click();await expect(page.getByText(reason,{exact:false})).toBeVisible();expect(await page.evaluate(()=>(window as any).__unsafeWeekly)).toBeUndefined();await page.screenshot({path:'../../test-results/weekly-history-tablet.png',fullPage:true});
});
