using Learning;
using Microsoft.EntityFrameworkCore;
public static class AssessmentRebuildCases
{
    static void Check(bool yes,string error){if(!yes)throw new Exception(error);}
    static Database Open(Database db,bool crash=false){var b=new DbContextOptionsBuilder<Database>().UseNpgsql(db.Database.GetConnectionString());if(crash)b.AddInterceptors(new CrashBeforeCommit());return new(b.Options);}
    internal static async Task<AssessmentRebuildRequest> Seed(Database db)
    {
        await db.Database.MigrateAsync();var f=new Family();var a=new Account{FamilyId=f.Id,UserName=Environment.GetEnvironmentVariable("REBUILD_COMPAT_USER")??"rebuild-"+Guid.NewGuid(),PasswordHash=Security.Password(Environment.GetEnvironmentVariable("REBUILD_COMPAT_PASSWORD")??"isolated-rebuild-fixture")};var catalog=Content.Fixture();var release=new Release{FamilyId=f.Id,Payload=Json.Write(catalog),Hash=Content.Hash(Json.Write(catalog)),Number=1};var s=new Student{FamilyId=f.Id,ActiveReleaseId=release.Id,TimeZone="Asia/Shanghai"};db.AddRange(f,a,new FamilyMembership{FamilyId=f.Id,AccountId=a.Id,Roles="Parent"},release,s);await db.SaveChangesAsync();await Publishing.Register(db,release);await db.SaveChangesAsync();
        async Task Append(Question q,bool modern)
        {
            var t=new StudyTask{FamilyId=f.Id,StudentId=s.Id,ReleaseId=release.Id,QuestionId=q.Id};var session=new LearningSession{FamilyId=f.Id,StudentId=s.Id,TaskId=t.Id,ReleaseId=release.Id,QuestionId=q.Id};var attempt=new Attempt{FamilyId=f.Id,StudentId=s.Id,SessionId=session.Id,Number=1,ClientSubmissionId=Guid.NewGuid(),Answer="999",CreatedAt=new DateTimeOffset(2000,1,1,20,0,0,TimeSpan.Zero)};var grade=new Grading{FamilyId=f.Id,AttemptId=attempt.Id,Number=1,Result="Incorrect"};
            await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(f.Id);db.AddRange(t,session,attempt,grade);if(modern)await DomainEvents.Append(db,f.Id,s.Id,attempt.Id,"Attempt","AttemptSubmitted",new{attemptId=attempt.Id,gradingId=grade.Id},attempt.Id);else db.Add(new Outbox{FamilyId=f.Id,StudentId=s.Id,AttemptId=attempt.Id});await db.SaveChangesAsync();await tx.CommitAsync();
        }
        await Append(catalog.Questions[0],false);var actor=new Actor(Guid.NewGuid(),f.Id,a.Id,null,"Parent","Parent");AssessmentRebuildRequest r;
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(f.Id);r=await AssessmentRebuildJobs.Enqueue(db,actor,s.Id,"受控后台重建请求");await db.SaveChangesAsync();Check((await AssessmentRebuildJobs.Enqueue(db,actor,s.Id,"另一次相同活动请求")).Id==r.Id,"active request duplicated");await tx.CommitAsync();}
        var collision=new BackgroundJob{FamilyId=f.Id,StudentId=s.Id,TargetGenerationId=Guid.NewGuid(),Type=AssessmentRebuildJobs.Type,InputRef=Guid.NewGuid(),IdempotencyKey=Guid.NewGuid().ToString(),InputPayload="{}",InputHash=Content.Hash("{}")};db.Add(collision);try{await db.SaveChangesAsync();throw new Exception("two active student rebuild jobs accepted");}catch(DbUpdateException e){Check(e.InnerException is Npgsql.PostgresException p && p.SqlState=="23505","active rebuild uniqueness missing");db.ChangeTracker.Clear();}
        Check(!await db.Generations.AnyAsync() && !await db.Set<AssessmentRebuildResult>().AnyAsync(),"queued request claimed false completed result");await Append(catalog.Questions[1],true);var job=await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==r.JobId);job.LeaseSeconds=3;job.HeartbeatSeconds=1;await db.SaveChangesAsync();return r;
    }
    public static async Task Run(Database db,string mode)
    {
        if(mode=="rebuild-job-seed"){await Seed(db);return;}
        if(mode=="rebuild-job-crash"){await using var crash=Open(db,true);await AssessmentRebuildJobs.ProcessOne(crash);return;}
        if(mode=="rebuild-job-recover")
        {
            var r=await db.Set<AssessmentRebuildRequest>().SingleAsync();await using var a=Open(db);await using var b=Open(db);await Task.WhenAll(AssessmentRebuildJobs.ProcessOne(a),AssessmentRebuildJobs.ProcessOne(b));await Verify(db,r);Check(await db.Set<JobLeaseAttempt>().CountAsync(j=>j.Status=="LeaseExpired")==1,"crashed claim missing");Console.WriteLine("PASS 重建真正中断后等待实际租约到期，双消费者一份固定世代/结果/消费回执及旧领取");return;
        }
        var request=await Seed(db);await AssessmentRebuildJobs.ProcessOne(db);await Verify(db,request);var first=await db.Set<AssessmentRebuildResult>().SingleAsync();var actor=new Actor(Guid.NewGuid(),request.FamilyId,request.RequestedBy,null,"Parent","Parent");AssessmentRebuildRequest duplicate;
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(request.FamilyId);duplicate=await AssessmentRebuildJobs.Enqueue(db,actor,request.StudentId,"确认同输入重复核对");await db.SaveChangesAsync();await tx.CommitAsync();}await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();var reused=await db.Set<AssessmentRebuildResult>().SingleAsync(r=>r.RequestId==duplicate.Id);Check(reused.ReusedGeneration && reused.GenerationId==first.GenerationId && await db.Generations.CountAsync()==1 && await db.Evidence.CountAsync()==2,"same input rebuild added generation/evidence");Console.WriteLine("PASS 后台请求零假完成、活动请求复用、排队后新作答纳入原固定目标并逐事件回执；同输入新核对复用实际世代");
        var original=Json.Write(await db.Set<AssessmentRebuildResult>().OrderBy(r=>r.Id).ToArrayAsync());await AssessmentRebuildJobs.ProcessOne(db);Check(original==Json.Write(await db.Set<AssessmentRebuildResult>().OrderBy(r=>r.Id).ToArrayAsync()),"duplicate consumer rewrote result");
        try{await db.Set<AssessmentRebuildRequest>().Where(r=>r.Id==request.Id).ExecuteUpdateAsync(u=>u.SetProperty(r=>r.Reason,"修改"));throw new Exception("request modified");}catch(Npgsql.PostgresException e){Check(e.SqlState=="23514","immutable request missing");}
        try{await db.Set<AssessmentRebuildResult>().Where(r=>r.Id==first.Id).ExecuteUpdateAsync(u=>u.SetProperty(r=>r.Cursor,0));throw new Exception("result modified");}catch(Npgsql.PostgresException e){Check(e.SqlState=="23514","immutable result missing");}
        var learner=await db.Students.SingleAsync(s=>s.Id==request.StudentId);learner.TimeZone="UTC";await db.SaveChangesAsync();AssessmentRebuildRequest zoned;
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(request.FamilyId);zoned=await AssessmentRebuildJobs.Enqueue(db,actor,request.StudentId,"受控跨午夜时区核对");await db.SaveChangesAsync();await tx.CommitAsync();}await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();var zoneResult=await db.Set<AssessmentRebuildResult>().SingleAsync(r=>r.RequestId==zoned.Id);var changed=await db.Generations.SingleAsync(g=>g.Id==zoneResult.GenerationId);Check(!zoneResult.ReusedGeneration && changed.InputHash!=first.InputHash && changed.InputVersion==Assessment.InputHashVersion,"changed timezone reused old hash");Check(await db.Reviews.CountAsync(r=>r.GenerationId==first.GenerationId)==2 && await db.Reviews.CountAsync(r=>r.GenerationId==changed.Id)==2 && await db.Reviews.Where(r=>r.GenerationId==first.GenerationId).AllAsync(r=>r.DueDate==new DateOnly(2000,1,4)) && await db.Reviews.Where(r=>r.GenerationId==changed.Id).AllAsync(r=>r.DueDate==new DateOnly(2000,1,3)),"controlled midnight review date not rebuilt by timezone");Console.WriteLine("PASS 受控跨午夜输入：时区纳入明确摘要版本，不复用旧世代，复习日期按新时区重建且旧日程保留");
        async Task<AssessmentRebuildRequest> Queue(string reason)
        {
            await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(request.FamilyId);var r=await AssessmentRebuildJobs.Enqueue(db,actor,request.StudentId,reason);await db.SaveChangesAsync();await tx.CommitAsync();return r;
        }
        var staleZone=await Queue("受控排队后设置变化");learner=await db.Students.SingleAsync(s=>s.Id==request.StudentId);learner.TimeZone="Asia/Shanghai";await db.SaveChangesAsync();await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();var rejected=await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==staleZone.JobId);Check(rejected.Status=="Failed" && rejected.LastErrorCode=="REBUILD_STUDENT_CONFIG_CHANGED" && !await db.Set<AssessmentRebuildResult>().AnyAsync(r=>r.RequestId==staleZone.Id) && (await db.Students.SingleAsync()).ActiveGenerationId==changed.Id,"queued timezone change was silently applied");
        learner=await db.Students.SingleAsync();learner.TimeZone="UTC";await db.SaveChangesAsync();var denied=await Queue("受控排队后撤销家长权限");var membership=await db.Set<FamilyMembership>().SingleAsync();membership.Roles="";await db.SaveChangesAsync();await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();var stopped=await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==denied.JobId);Check(stopped.Status=="Failed" && stopped.LastErrorCode=="JOB_REQUESTER_FORBIDDEN" && !await db.Set<AssessmentRebuildResult>().AnyAsync(r=>r.RequestId==denied.Id),"revoked parent still applied result");
        membership=await db.Set<FamilyMembership>().SingleAsync();membership.Roles="Parent";stopped.Status="Queued";stopped.RetryRound=1;stopped.AttemptCount=0;await db.SaveChangesAsync();await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();stopped=await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==denied.JobId);Check(stopped.Status=="Failed" && stopped.LastErrorCode=="JOB_RETRY_AUTHORIZATION_MISSING" && !await db.Set<AssessmentRebuildResult>().AnyAsync(r=>r.RequestId==denied.Id),"retry without round authorization accepted");
        // Controlled persisted retry fixture; this exercises worker authorization, not the HTTP retry endpoint.
        stopped.Status="Queued";stopped.RetryRound=2;stopped.AttemptCount=0;db.Audits.Add(new(){FamilyId=denied.FamilyId,StudentId=denied.StudentId,ActorId=actor.Id,Action="AssessmentRebuildManualRetry",Details=Json.Write(new{requestId=denied.Id,jobId=denied.JobId,retryRound=2,targetGenerationId=denied.TargetGenerationId,snapshotHash=denied.SnapshotHash,reason="受控本轮授权恢复"})});await db.SaveChangesAsync();await AssessmentRebuildJobs.ProcessOne(db);db.ChangeTracker.Clear();var recovered=await db.Set<AssessmentRebuildResult>().SingleAsync(r=>r.RequestId==denied.Id);Check(recovered.GenerationId==changed.Id && recovered.ReusedGeneration && await db.Generations.CountAsync()==2 && await db.Set<ConsumerReceipt>().CountAsync()==2 && (await db.Set<AssessmentRebuildRequest>().SingleAsync(r=>r.Id==denied.Id)).TargetGenerationId==denied.TargetGenerationId,"authorized retry replaced original input or duplicated output");Console.WriteLine("PASS 排队后时区/家长权限变化零结果；缺少本轮授权停止，受控持久化授权沿原目标恢复且不重复证据");
        await db.Students.Where(s=>s.Id==request.StudentId).ExecuteDeleteAsync();Check(!await db.Set<AssessmentRebuildRequest>().AnyAsync() && !await db.Set<AssessmentRebuildResult>().AnyAsync() && !await db.Set<ConsumerReceipt>().AnyAsync() && !await db.Set<BackgroundJob>().AnyAsync(),"student deletion left job/private result");Console.WriteLine("PASS 请求和结果不可修改、重复消费不改原回执；学生删除清理请求/结果/评估任务及消费记录");
    }
    static async Task Verify(Database db,AssessmentRebuildRequest r)
    {
        db.ChangeTracker.Clear();var job=await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==r.JobId);var result=await db.Set<AssessmentRebuildResult>().SingleAsync(x=>x.RequestId==r.Id);var student=await db.Students.SingleAsync(s=>s.Id==r.StudentId);Check(job.Status=="Succeeded" && result.GenerationId==r.TargetGenerationId && student.ActiveGenerationId==r.TargetGenerationId && result.Cursor==await db.Attempts.MaxAsync(a=>a.Sequence),"fixed generation/catch-up result incomplete");Check(await db.Evidence.CountAsync()==2 && await db.Set<AssessmentContext>().CountAsync()==2 && await db.Set<ConsumerReceipt>().CountAsync()==2 && !await db.Outbox.AnyAsync(o=>o.ProcessedAt==null),"evidence/contexts/receipts partially committed");Check(await db.Set<JobLeaseAttempt>().CountAsync(a=>a.JobId==job.Id && a.Status=="Succeeded")==1 && await db.Set<DomainEvent>().AnyAsync(e=>e.Id==result.AppliedEventId && e.AggregateId==result.GenerationId),"applied event/claim missing");
    }
}
