using Learning;
using Microsoft.EntityFrameworkCore;
public static class AssessmentConsumptionCases
{
    static void Check(bool yes,string message){if(!yes)throw new Exception(message);}
    public static async Task Run(Database db,string mode)
    {
        if(mode=="cursor-crash"){await using var crash=new Database(new DbContextOptionsBuilder<Database>().UseNpgsql(db.Database.GetConnectionString()).AddInterceptors(new CrashBeforeCommit()).Options);await ProjectionWorker.ProcessOne(crash);return;}
        if(mode=="cursor-recover")
        {
            await using var a=BackgroundJobs.Open(db);await using var b=BackgroundJobs.Open(db);await Task.WhenAll(ProjectionWorker.ProcessOne(a),ProjectionWorker.ProcessOne(b));db.ChangeTracker.Clear();var recoveredCursor=await db.Set<AssessmentConsumerCursor>().SingleAsync();var applied=await db.Set<DomainEvent>().SingleAsync(e=>e.Id==recoveredCursor.LastAppliedEventId);var receipt=await db.Set<ConsumerReceipt>().SingleAsync(r=>r.Id==recoveredCursor.LastReceiptId);
            Check(await db.Generations.CountAsync()==1 && await db.Set<AssessmentCheckpoint>().CountAsync()==3 && await db.Evidence.CountAsync()==4 && await db.Set<ConsumerReceipt>().CountAsync()==4 && receipt.EventId==recoveredCursor.LastEventId && receipt.CheckpointId!=null,"recoveredCursor recovery did not atomically append exactly once");
            Check(await db.Set<DomainEvent>().CountAsync(e=>e.EventType=="AssessmentApplied")==3 && await db.Set<JobLeaseAttempt>().CountAsync(a=>a.Status=="LeaseExpired")==1,"recoveredCursor recovery lost actual application/expired attempt history");
            using var doc=System.Text.Json.JsonDocument.Parse(applied.Payload);var advance=Json.Read<ConsumptionAdvance>(doc.RootElement.GetProperty("data").GetProperty("consumption").GetRawText());Check(advance.PriorSequence!=null && advance.ThroughSequence==recoveredCursor.LastEventSequence && advance.NewEventIds.Length==1 && advance.VerifiedReceiptIds.SequenceEqual(new[]{receipt.Id}),"recoveredCursor result does not prove its actual boundary");Console.WriteLine("PASS 顺序追加真正中断后实际租约到期双消费者一次提交同世代/新状态/回执/应用事实及游标，旧领取保留");return;
        }
        await db.Database.MigrateAsync();var family=new Family();var catalog=Content.Fixture();var release=new Release{FamilyId=family.Id,Number=1,Payload=Json.Write(catalog),Hash=Content.Hash(Json.Write(catalog))};var student=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};db.AddRange(family,release,student);await db.SaveChangesAsync();await Publishing.Register(db,release);await db.SaveChangesAsync();var source=new List<Outbox>();var events=new List<DomainEvent>();var legacy=new List<Outbox>();
        async Task Append(int index,bool modern=true)
        {
            var question=catalog.Questions[index];var task=new StudyTask{FamilyId=family.Id,StudentId=student.Id,ReleaseId=release.Id,QuestionId=question.Id};var session=new LearningSession{FamilyId=family.Id,StudentId=student.Id,TaskId=task.Id,ReleaseId=release.Id,QuestionId=question.Id};var attempt=new Attempt{FamilyId=family.Id,StudentId=student.Id,SessionId=session.Id,Number=1,ClientSubmissionId=Guid.NewGuid()};var grade=new Grading{FamilyId=family.Id,AttemptId=attempt.Id,Number=1,Result="Correct"};
            await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);db.AddRange(task,session,attempt,grade);await db.SaveChangesAsync();
            if(modern){var e=await DomainEvents.Append(db,family.Id,student.Id,attempt.Id,"Attempt","AttemptSubmitted",new{attemptId=attempt.Id,gradingId=grade.Id},attempt.Id);events.Add(e);await db.SaveChangesAsync();source.Add(await db.Outbox.SingleAsync(o=>o.Id==e.Id));}
            else {var o=new Outbox{FamilyId=family.Id,StudentId=student.Id,AttemptId=attempt.Id};db.Add(o);await db.SaveChangesAsync();legacy.Add(o);}
            await tx.CommitAsync();
        }
        await Append(0,false);Check(await ProjectionWorker.Consume(db,legacy[0]),"legacy work not consumed");db.ChangeTracker.Clear();Check(!await db.Set<AssessmentConsumerCursor>().AnyAsync(),"legacy-only input invented a known sequence cursor");
        var historicalGeneration=(await db.Generations.SingleAsync()).Id;
        await Append(1);await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);await DomainEvents.Append(db,family.Id,student.Id,student.Id,"Student","ProgressChanged",new{reason="非评估事件真实序号间隔"});await db.SaveChangesAsync();await tx.RollbackAsync();}db.ChangeTracker.Clear();
        await Append(2);Check(events[1].EventSequence>events[0].EventSequence+1,"rollback did not leave a real sequence gap");
        Check(await ProjectionWorker.Consume(db,source[0]),"initial typed batch failed");db.ChangeTracker.Clear();var cursor=await db.Set<AssessmentConsumerCursor>().SingleAsync();var original=Json.Write(cursor);var firstApplied=await db.Set<DomainEvent>().SingleAsync(e=>e.Id==cursor.LastAppliedEventId);var firstBytes=Json.Write(firstApplied);using(var doc=System.Text.Json.JsonDocument.Parse(firstApplied.Payload)){var a=Json.Read<ConsumptionAdvance>(doc.RootElement.GetProperty("data").GetProperty("consumption").GetRawText());Check(a.PriorSequence==null && a.NewEventIds.SequenceEqual(events.Select(e=>e.Id)) && a.VerifiedEventIds.SequenceEqual(events.Select(e=>e.Id)) && a.ThroughSequence==events[^1].EventSequence && a.LegacyEventIds.Length==0,"first progress fabricated legacy order or changed deterministic source sequence");}
        Check(cursor.GenerationId==historicalGeneration && await db.Set<ConsumerReceipt>().CountAsync()==3 && cursor.LastEventId==events[^1].Id,"cursor not linked to actual coalesced result");
        Check(!await ProjectionWorker.Consume(db,source[1]),"coalesced duplicate executed");db.ChangeTracker.Clear();Check(Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync())==original,"duplicate changed cursor");
        var repaired=await db.Outbox.SingleAsync(o=>o.Id==source[0].Id);repaired.ProcessedAt=null;repaired.RetryRound=1;await db.SaveChangesAsync();Check(!await ProjectionWorker.Consume(db,repaired),"old marker repair executed");db.ChangeTracker.Clear();Check(Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync())==original && (await db.Outbox.SingleAsync(o=>o.Id==repaired.Id)).ProcessedAt!=null,"old marker repair advanced cursor");
        var invalidRepair=await db.Outbox.SingleAsync(o=>o.Id==source[0].Id);invalidRepair.DomainEventId=null;invalidRepair.ProcessedAt=null;invalidRepair.RetryRound++;await db.SaveChangesAsync();
        try{await ProjectionWorker.Consume(db,invalidRepair);throw new Exception("invalid original receipt repaired silently");}catch(ApiError error){Check(error.Code=="DOMAIN_EVENT_INVALID","wrong receipt repair error");}db.ChangeTracker.Clear();var stopped=await db.Set<BackgroundJob>().SingleAsync(j=>j.InputRef==invalidRepair.Id);Check(stopped.Status=="Failed" && stopped.LastErrorCode=="DOMAIN_EVENT_INVALID" && (await db.Outbox.SingleAsync(o=>o.Id==invalidRepair.Id)).Error=="DOMAIN_EVENT_INVALID" && Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync())==original,"invalid repair failed to persist terminal error or changed cursor");
        invalidRepair=await db.Outbox.SingleAsync(o=>o.Id==invalidRepair.Id);invalidRepair.DomainEventId=invalidRepair.Id;invalidRepair.RetryRound++;invalidRepair.Retries=0;invalidRepair.Error=null;await db.SaveChangesAsync();Check(!await ProjectionWorker.Consume(db,invalidRepair),"controlled restored receipt reran assessment");db.ChangeTracker.Clear();Check(Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync())==original,"restored receipt advanced cursor");
        Console.WriteLine("PASS 旧无序来源保留未知、不补游标；两条实际现代事件按服务器序号消费，回滚间隔合法，合并/重复/旧标记修复保留真实边界与原应用事实");
        // A later modern source after a known non-assessment event advances only the assessment stream.
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);await DomainEvents.Append(db,family.Id,student.Id,student.Id,"Student","ProgressChanged",new{reason="不消费为评估事件"});await db.SaveChangesAsync();await tx.CommitAsync();}
        await Append(3);await ProjectionJobs.Ensure(db);
        if(mode=="cursor-seed"){await db.Set<BackgroundJob>().Where(j=>j.Status=="Queued").ExecuteUpdateAsync(u=>u.SetProperty(j=>j.LeaseSeconds,3).SetProperty(j=>j.HeartbeatSeconds,1));return;}
        Check(await ProjectionWorker.Consume(db,source[^1]),"second typed batch failed");db.ChangeTracker.Clear();var next=await db.Set<AssessmentConsumerCursor>().SingleAsync();Check(next.Id==cursor.Id && next.LastEventSequence==events[^1].EventSequence && next.LastEventSequence>cursor.LastEventSequence && next.GenerationId==historicalGeneration && Json.Write(await db.Set<DomainEvent>().SingleAsync(e=>e.Id==firstApplied.Id))==firstBytes,"advance rewrote old application or generation");
        try{await db.Set<AssessmentConsumerCursor>().ExecuteUpdateAsync(u=>u.SetProperty(c=>c.UpdatedAt,DateTimeOffset.UtcNow));throw new Exception("cursor retouched without progress");}catch(Npgsql.PostgresException error){Check(error.SqlState=="23514","monotonic cursor guard missing");}
        Console.WriteLine("PASS 后续实际事件关联当次状态/回执/应用且只推进评估流，非评估事件未假消费；数据库拒绝重复/倒退更新");
        // Explicit missing-receipt fixture above the old cursor: history cannot be silently skipped.
        await Append(4);var gap=source[^1];gap.ProcessedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();await Append(5);var count=await db.Set<ConsumerReceipt>().CountAsync();var frozen=Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync());
        try{await ProjectionWorker.Consume(db,source[^1]);throw new Exception("missing ordered receipt skipped");}catch(ApiError error){Check(error.Code=="ASSESSMENT_CONSUMPTION_GAP","wrong missing receipt error");}db.ChangeTracker.Clear();Check(await db.Set<ConsumerReceipt>().CountAsync()==count && Json.Write(await db.Set<AssessmentConsumerCursor>().SingleAsync())==frozen && await db.Set<AssessmentCheckpoint>().CountAsync()==3,"gap committed new result or invented receipt");Console.WriteLine("PASS 受控无回执完成标记造成真实消费缺口时明确停止，零新状态/回执/游标，不以较大序号冒充完整处理");
        await db.Students.Where(s=>s.Id==student.Id).ExecuteDeleteAsync();Check(!await db.Set<AssessmentConsumerCursor>().AnyAsync() && !await db.Set<ConsumerReceipt>().AnyAsync(),"private cursor retained after student deletion");Console.WriteLine("PASS 学生删除清理自己的顺序进度和消费依据");
        // Controlled pre-upgrade compatibility fixture: actual state metadata and cursor are absent.
        db.ChangeTracker.Clear();source.Clear();events.Clear();legacy.Clear();student=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};db.Add(student);await db.SaveChangesAsync();await Append(0);
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);await Assessment.Rebuild(db,student);await tx.CommitAsync();}db.ChangeTracker.Clear();var savedState=await db.Set<AssessmentCheckpoint>().SingleAsync();await db.Set<AssessmentCheckpoint>().ExecuteDeleteAsync();db.ChangeTracker.Clear();db.Add(new AssessmentCheckpoint{FamilyId=family.Id,StudentId=student.Id,GenerationId=savedState.GenerationId,EngineVersion=savedState.EngineVersion,PrefixHash=savedState.PrefixHash,InputCount=savedState.InputCount,Payload=savedState.Payload,PayloadHash=savedState.PayloadHash});await db.SaveChangesAsync();
        Check(await ProjectionWorker.Consume(db,source[0]),"unknown state-header compatibility consumption failed");db.ChangeTracker.Clear();var oldReceipt=await db.Set<ConsumerReceipt>().SingleAsync();Check(oldReceipt.CheckpointId==null,"unknown old state metadata fabricated a checkpoint link");var receiptBytes=Json.Write(oldReceipt);var oldApplication=await db.Set<DomainEvent>().SingleAsync(e=>e.EventType=="AssessmentApplied");var appBytes=Json.Write(oldApplication);await db.Set<AssessmentConsumerCursor>().ExecuteDeleteAsync();db.ChangeTracker.Clear();
        await Append(1);Check(await ProjectionWorker.Consume(db,source[^1]),"cursor bootstrap from actual old application failed");db.ChangeTracker.Clear();var bridged=await db.Set<AssessmentConsumerCursor>().SingleAsync();var actual=await db.Set<DomainEvent>().SingleAsync(e=>e.Id==bridged.LastAppliedEventId);using(var doc=System.Text.Json.JsonDocument.Parse(actual.Payload)){var advance=Json.Read<ConsumptionAdvance>(doc.RootElement.GetProperty("data").GetProperty("consumption").GetRawText());Check(advance.PriorSequence==null && advance.VerifiedEventIds.Length==2 && advance.NewEventIds.Length==1,"bootstrap fabricated prior cursor or old processing");}
        Check(Json.Write(await db.Set<ConsumerReceipt>().SingleAsync(r=>r.Id==oldReceipt.Id))==receiptBytes && Json.Write(await db.Set<DomainEvent>().SingleAsync(e=>e.Id==oldApplication.Id))==appBytes && (await db.Set<AssessmentCheckpoint>().OrderBy(c=>c.InputCount).FirstAsync()).InputHash==null,"compatibility bridge rewrote old unknown state, receipt or actual application");Console.WriteLine("PASS 受控旧状态头/无游标夹具：以实际原应用事实验证旧无状态关联回执，新增输入时才建立边界，原未知字段/回执/事实字节不改");
        await db.Students.Where(s=>s.Id==student.Id).ExecuteDeleteAsync();

    }
}
