using Learning;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
public static class BuilderRetrievalPersistenceCases
{
    static void Check(bool value,string message){if(!value)throw new Exception(message);}
    public static async Task Run(Database db,string mode="builder-retrieval")
    {
        await db.Database.MigrateAsync();var family=new Family();var account=new Account{FamilyId=family.Id,UserName=Environment.GetEnvironmentVariable("RETRIEVAL_USER")??"retrieval-"+Guid.NewGuid(),PasswordHash=Security.Password(Environment.GetEnvironmentVariable("RETRIEVAL_PASSWORD")??"retrieval-isolated-password")};db.AddRange(family,account,new FamilyMembership{FamilyId=family.Id,AccountId=account.Id,Roles="Parent,ContentEditor,Publisher"});var actor=new Actor(account.Id,family.Id,account.Id,null,"Parent","Parent,ContentEditor,Publisher");var catalog=Content.Fixture();var draft=new ContentDraft{FamilyId=family.Id,Title="固定检索正式库受控审核夹具",Payload=Json.Write(catalog)};db.Add(draft);await db.SaveChangesAsync();await ContentReviews.Approve(db,actor,draft,new ContentReviewInput(draft.Version,"隔离检索夹具整份审核"));await db.SaveChangesAsync();var review=await ContentReviews.ForPublish(db,draft);var release=new Release{FamilyId=family.Id,Number=1,Payload=draft.Payload,Hash=Content.Hash(draft.Payload)};db.Add(release);await Publishing.Register(db,release,review);review.PublishedReleaseId=release.Id;review.PublishedMappingVersion="mapping-container/1";draft.Status="Published";await db.SaveChangesAsync();
        var text="独立计算混合运算，不能把应用建模当成计算能力。";var source=new Source{FamilyId=family.Id,Title="实际冻结检索来源",Text=text,Hash=Content.Hash(text)};var chunk=new Chunk{FamilyId=family.Id,SourceId=source.Id,Locator="段落1",Text=text};db.AddRange(source,chunk);await db.SaveChangesAsync();
        async Task<BuilderRun> Prepare(string input,BuilderModelConfiguration configuration)
        {
            var payload=Json.Write(configuration);var hash=Content.Hash(payload);var run=new BuilderRun{FamilyId=family.Id,SourceId=source.Id,LibraryReleaseId=release.Id,InputVersion=input,ModelConfigPayload=payload,ModelConfigHash=hash,InputHash=Content.Hash(source.Hash+":Mock:fixture/1:kc-candidate/1:"+input+":"+release.Hash+":"+hash)};db.Add(run);await db.SaveChangesAsync();return run;
        }
        var legacy=await Prepare("builder-input/3",new("builder-config/1","Mock","fixture/1","kc-candidate/1",Content.Hash(BuilderProtocol.Schema),new BuilderLimits()));var legacyOriginal=legacy.ModelConfigPayload;
        var frozen=BuilderConfiguration.Current(new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Builder:RetrievalTopK","2"}}).Build());var modern=await Prepare("builder-input/4",frozen);var original=modern.ModelConfigPayload;
        if(mode=="builder-retrieval-api-seed"){Console.WriteLine(Json.Write(new{userName=account.UserName,sourceId=source.Id,legacyId=legacy.Id,modernId=modern.Id,modernPayload=original,legacyPayload=legacyOriginal,kcCount=catalog.Kcs.Length}));return;}
        // The worker receives no current IConfiguration; the stored two-item profile controls the result.
        Check(BuilderConfiguration.Current(new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Builder:RetrievalTopK","1"}}).Build()).Retrieval!.TopK==1,"test current config missing");
        await Builder.ProcessOne(db,CancellationToken.None);await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();
        var oldCandidate=await db.Candidates.SingleAsync(c=>c.RunId==legacy.Id);var newCandidate=await db.Candidates.SingleAsync(c=>c.RunId==modern.Id);var newMatches=Json.Read<Match[]>(newCandidate.Matches);
        Check(newMatches.Length==2 && newMatches.All(m=>catalog.Kcs.Single(k=>k.Id==m.KCId).Type=="Procedure"),"saved two-item compatible-type retrieval not applied");Check(Json.Read<Match[]>(oldCandidate.Matches).Length==catalog.Kcs.Length,"old source-based ten-item result reinterpreted");Check((await db.BuilderRuns.SingleAsync(r=>r.Id==modern.Id)).ModelConfigPayload==original && (await db.BuilderRuns.SingleAsync(r=>r.Id==legacy.Id)).ModelConfigPayload==legacyOriginal,"run snapshots changed during processing");
        var oldBytes=Json.Write(oldCandidate);var newBytes=Json.Write(newCandidate);await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();Check(Json.Write(await db.Candidates.SingleAsync(c=>c.Id==oldCandidate.Id))==oldBytes && Json.Write(await db.Candidates.SingleAsync(c=>c.Id==newCandidate.Id))==newBytes,"repeated processing changed completed retrieval");Console.WriteLine("PASS 实际审核发布固定库经后台生成：新配置固定两项同类型结果，当前一项设置不替换原输入；旧配置保留原片段十项方式，重复处理原候选字节保持");
        Check(newMatches.All(m=>m.RetrievalEvidence?.KeywordPolicy==BuilderLexicalRetrieval.KeywordPolicy && m.RetrievalEvidence.FusionPolicy==BuilderLexicalRetrieval.FusionPolicy) && newMatches.Any(m=>m.RetrievalEvidence!.MatchedTerms.Length>0),"actual worker omitted lexical/fusion evidence");
        var profileTwo=await Prepare("builder-input/4",frozen with{Retrieval=frozen.Retrieval! with{Version="builder-retrieval/2",SubjectPolicy=null,GradePolicy=null,KeywordPolicy=null,FusionPolicy=null}});await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();var profileTwoCandidate=await db.Candidates.SingleAsync(c=>c.RunId==profileTwo.Id);Check(!profileTwoCandidate.Matches.Contains("retrievalEvidence") && Json.Read<Match[]>(profileTwoCandidate.Matches).Length==2,"stored retrieval/2 changed old ranking shape");Console.WriteLine("PASS 新关键词融合经实际后台保存命中依据；旧retrieval/2不增加关键词字段且沿用原两项排序");
        var bad=frozen with{Retrieval=frozen.Retrieval! with{Space="different-model-space"}};var invalid=await Prepare("builder-input/4",bad);await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();Check((await db.BuilderRuns.SingleAsync(r=>r.Id==invalid.Id)).Error=="BUILDER_CONFIGURATION_INVALID" && !await db.Candidates.AnyAsync(c=>c.RunId==invalid.Id) && !await db.Set<BuilderCall>().AnyAsync(c=>c.RunId==invalid.Id),"invalid frozen space called provider or produced results");Console.WriteLine("PASS 原配置空间矛盾在实际调用前明确失败，零候选/调用；不自动换成当前空间");
        var profileOne=await Prepare("builder-input/4",frozen with{Retrieval=frozen.Retrieval! with{Version="builder-retrieval/1",SubjectPolicy=null,GradePolicy=null,Aliases=null,KeywordPolicy=null,FusionPolicy=null}});await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();var profileOneCandidate=await db.Candidates.SingleAsync(c=>c.RunId==profileOne.Id);Check(!profileOneCandidate.Matches.Contains("matchedAliases") && Json.Read<Match[]>(profileOneCandidate.Matches).Length==2,"stored retrieval/1 gained alias metadata or changed fixed count");Console.WriteLine("PASS 原retrieval/1配置经实际后台仍保留原两项检索及旧JSON形状");
        // Controlled database fixture: accepted provenance, then a later alias after the run is frozen.
        var target=catalog.Kcs.Last(k=>k.Type=="Procedure");var second=catalog.Kcs.First(k=>k.Type=="Procedure" && k.Id!=target.Id);
        db.Attach(newCandidate);db.Attach(oldCandidate);newCandidate.ExistingKCId=target.Id;newCandidate.Status="Accepted";var firstAlias=new Alias{FamilyId=family.Id,KCId=target.Id,CandidateId=newCandidate.Id,Text=newCandidate.Name,Normalized=Retrieval.Normalize(newCandidate.Name),ReviewedBy=account.Id};db.Add(firstAlias);await db.SaveChangesAsync();
        var captured=await BuilderAliases.Capture(db,family.Id,catalog);Check(captured.Length==1 && captured[0].Id==firstAlias.Id,"capture lost reviewed provenance");
        Check((await BuilderAliases.Capture(db,Guid.NewGuid(),catalog)).Length==0 && (await BuilderAliases.Capture(db,family.Id,catalog with{Kcs=[]})).Length==0,"alias capture crossed family or fixed-library boundary");
        var aliasConfig=frozen with{Retrieval=frozen.Retrieval! with{Aliases=captured}};var aliased=await Prepare("builder-input/4",aliasConfig);var originalAliasPayload=aliased.ModelConfigPayload;
        oldCandidate.ExistingKCId=second.Id;oldCandidate.Status="Accepted";var later=new Alias{FamilyId=family.Id,KCId=second.Id,CandidateId=oldCandidate.Id,Text=newCandidate.Name,Normalized=Retrieval.Normalize(newCandidate.Name),ReviewedBy=account.Id};db.Add(later);await db.SaveChangesAsync();
        Check((await BuilderAliases.Capture(db,family.Id,catalog)).Length==2,"new run would miss later approved alias");
        await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();var actual=await db.Candidates.SingleAsync(c=>c.RunId==aliased.Id);var ranked=Json.Read<Match[]>(actual.Matches);Check(ranked[0].KCId==target.Id && ranked[0].MatchedAliases!.Single().Id==firstAlias.Id && ranked.All(m=>m.MatchedAliases!.All(a=>a.Id!=later.Id)),"worker loaded later alias or ignored frozen priority");Check((await db.BuilderRuns.SingleAsync(r=>r.Id==aliased.Id)).ModelConfigPayload==originalAliasPayload,"alias snapshot rewritten");
        Console.WriteLine("PASS 受控审核别名夹具经实际后台：固定别名优先列出，后增别名不进入原请求；原配置字节保持");
        var broken=await Prepare("builder-input/4",aliasConfig with{Retrieval=aliasConfig.Retrieval! with{TopK=3}});await db.Set<Alias>().Where(a=>a.Id==firstAlias.Id).ExecuteUpdateAsync(u=>u.SetProperty(a=>a.Text,"来源变化"));await Builder.ProcessOne(db,CancellationToken.None);db.ChangeTracker.Clear();Check((await db.BuilderRuns.SingleAsync(r=>r.Id==broken.Id)).Error=="BUILDER_ALIAS_SNAPSHOT_CHANGED" && !await db.Set<BuilderCall>().AnyAsync(c=>c.RunId==broken.Id) && !await db.Candidates.AnyAsync(c=>c.RunId==broken.Id),"changed alias called provider or silently replaced snapshot");Console.WriteLine("PASS 固定别名来源变化在调用前失败，零调用、零候选");
        await db.Families.Where(f=>f.Id==family.Id).ExecuteDeleteAsync();Check(!await db.Candidates.AnyAsync() && !await db.Set<Embedding>().AnyAsync() && !await db.Set<Alias>().AnyAsync() && !await db.Set<BuilderCall>().AnyAsync(),"family deletion retained retrieval facts");Console.WriteLine("PASS 家庭删除清理候选、空间及调用记录");
    }
}
