using Learning;
using Microsoft.EntityFrameworkCore;
public static class BuilderBudgetPersistenceCases
{
    static void Check(bool v,string message){if(!v)throw new Exception(message);}
    sealed class FixtureProvider(BuilderQuote quote,BuilderProviderResponse response,bool hold=false):IBuilderCandidateProvider
    {
        public int Calls;public TaskCompletionSource Started=new(TaskCreationOptions.RunContinuationsAsynchronously),Release=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public BuilderQuote Quote(BuilderProviderRequest request)=>quote;
        public async Task<BuilderProviderResponse> Generate(BuilderProviderRequest request,CancellationToken ct){Interlocked.Increment(ref Calls);Started.TrySetResult();if(hold)await Release.Task.WaitAsync(ct);return response;}
    }
    public static async Task Run(Database db)
    {
        await db.Database.MigrateAsync();
        async Task<(Family Family,BuilderRun[] Runs,Account Actor)> Setup(int concurrency=1)
        {
            var f=new Family();var a=new Account{FamilyId=f.Id,UserName="budget-fixture-"+Guid.NewGuid()};var source=new Source{FamilyId=f.Id,Title="受控预算夹具",Text="本地构造计费响应，不调用模型。",Hash="fixture"};var runs=Enumerable.Range(0,10).Select(_=>new BuilderRun{FamilyId=f.Id,SourceId=source.Id,InputHash=Guid.NewGuid().ToString()}).ToArray();db.AddRange(f,a,source,new BuilderBudgetPolicy{FamilyId=f.Id,DailyCostLimit=1,PerCallCostLimit=.7m,DailyTokenLimit=1000,PerCallTokenLimit=1000,MaxConcurrentCalls=concurrency});db.AddRange(runs);await db.SaveChangesAsync();return(f,runs,a);
        }
        var request=new BuilderProviderRequest([new(Guid.NewGuid(),"夹具")],BuilderProtocol.Schema);
        FixtureProvider Paid(decimal quote,long tokens,decimal? cost,long? input,long? output,bool hold=false)=>new(new(quote,tokens,"USD"),new("{}",cost==null?null:new(input,output,cost,"USD","Confirmed")),hold);
        async Task<string> Invoke(BuilderRun run,FixtureProvider provider){try{await new BuilderCallTracking(db,run,1,provider).Generate(request,CancellationToken.None);return "Returned";}catch(ApiError e){return e.Code;}}
        async Task<BuilderBudgetState> State(Guid family)=>await BuilderBudget.State(db,family,DateOnly.FromDateTime(DateTime.UtcNow));
        var scope=await Setup();var waiting=Paid(.7m,500,.3m,100,200,true);var running=Invoke(scope.Runs[0],waiting);await waiting.Started.Task.WaitAsync(TimeSpan.FromSeconds(10));var blocked=Paid(.7m,500,.2m,80,120);Check(await Invoke(scope.Runs[1],blocked)=="BUILDER_CONCURRENCY_LIMIT" && blocked.Calls==0,"concurrency gate started provider");waiting.Release.TrySetResult();Check(await running=="Returned","held provider failed");var state=await State(scope.Family.Id);Check(state.CostCommitted==.3m && state.TokensCommitted==300 && state.ActiveCalls==0,"unused reservation was not released on confirmed return");Check(await Invoke(scope.Runs[1],blocked)=="Returned" && blocked.Calls==1,"released concurrency slot unavailable");
        var money=Paid(.7m,100,.1m,1,1);Check(await Invoke(scope.Runs[2],money)=="BUILDER_DAILY_BUDGET_LIMIT" && money.Calls==0,"daily cost overbooked");var tokensOnly=Paid(.1m,600,.1m,1,1);Check(await Invoke(scope.Runs[3],tokensOnly)=="BUILDER_DAILY_BUDGET_LIMIT" && tokensOnly.Calls==0,"daily token overbooked");var single=Paid(.8m,1,.1m,1,1);Check(await Invoke(scope.Runs[4],single)=="BUILDER_CALL_BUDGET_LIMIT" && single.Calls==0,"per-call cap bypassed");Console.WriteLine("PASS 真实独立提交：并发名额、单次/每日费用及Token上限在提供者之前拒绝，明确返回释放余下预留");
        var unknown=Paid(.5m,500,null,null,null);Check(await Invoke(scope.Runs[5],unknown)=="Returned","unknown response rejected");var row=await db.Set<BuilderCall>().SingleAsync(c=>c.RunId==scope.Runs[5].Id);await db.Set<BuilderCall>().Where(c=>c.Id==row.Id).ExecuteUpdateAsync(u=>u.SetProperty(c=>c.BudgetDay,(DateOnly?)DateOnly.FromDateTime(DateTime.UtcNow).AddDays(-1)));state=await State(scope.Family.Id);Check(state.CostCommitted==1 && state.TokensCommitted==1000 && state.UnresolvedCalls==1,"unknown reservation released at day boundary");var extra=Paid(.000001m,1,0,0,0);Check(await Invoke(scope.Runs[6],extra)=="BUILDER_DAILY_BUDGET_LIMIT" && extra.Calls==0,"cross-day unknown allowed overbook");db.Add(new BuilderBudgetReconciliation{FamilyId=scope.Family.Id,CallId=row.Id,ActorId=scope.Actor.Id,ChargedCost=.1m,Currency="USD",InputTokens=10,OutputTokens=20,Reason="跨日夹具明确核对",ReceiptReference="controlled fixture"});await db.SaveChangesAsync();state=await State(scope.Family.Id);Check(state.CostCommitted==.5m && state.TokensCommitted==500 && state.UnresolvedCalls==0 && (await db.Set<BuilderCall>().AsNoTracking().SingleAsync(c=>c.Id==row.Id)).BillingStatus=="Unknown","reconciliation rewrote raw receipt or failed to release reservation");Console.WriteLine("PASS 显式跨日夹具：未知预留不随日期释放，追加人工核对后按原窗口结算且原调用未知事实不改");
        var legacy=new BuilderCall{FamilyId=scope.Family.Id,RunId=scope.Runs[7].Id,ExecutionId=Guid.NewGuid(),CallNumber=1,Status="Returned"};db.Add(legacy);await db.SaveChangesAsync();var priced=Paid(.1m,1,.1m,1,1);Check(await Invoke(scope.Runs[8],priced)=="BUILDER_USAGE_RECONCILIATION_REQUIRED" && priced.Calls==0,"unbounded old unknown treated as zero");Console.WriteLine("PASS 旧缺失预算且费用未知时拒绝有费用新调用，不补造原预留");
        var race=await Setup(2);var aProvider=Paid(.6m,100,.2m,11,22,true);var bProvider=Paid(.6m,100,.2m,11,22,true);var aTask=Invoke(race.Runs[0],aProvider);var bTask=Invoke(race.Runs[1],bProvider);await Task.WhenAny(aProvider.Started.Task,bProvider.Started.Task).WaitAsync(TimeSpan.FromSeconds(10));var deniedTask=await Task.WhenAny(aTask,bTask).WaitAsync(TimeSpan.FromSeconds(10));Check(await deniedTask=="BUILDER_DAILY_BUDGET_LIMIT","simultaneous reservation did not reject second spend");aProvider.Release.TrySetResult();bProvider.Release.TrySetResult();var results=await Task.WhenAll(aTask,bTask);Check(results.Count(x=>x=="Returned")==1 && aProvider.Calls+bProvider.Calls==1,"two competing reservations both called provider");Console.WriteLine("PASS 两个真实连接同时抢预算，名额允许2但费用仅够1时，仅一个提供者开始");
        var over=await Setup();var liar=Paid(.1m,10,.2m,2,3);Check(await Invoke(over.Runs[0],liar)=="Returned","overrun facts lost");state=await State(over.Family.Id);Check(state.CostCommitted==.2m && state.OverrunCalls==1,"overrun not retained");var free=new FixtureProvider(BuilderQuote.Local,new("{}",new(null,null,0,null,"LocalNoCharge")));Check(await Invoke(over.Runs[1],free)=="BUILDER_USAGE_RECONCILIATION_REQUIRED" && free.Calls==0,"overrun did not pause later calls");Console.WriteLine("PASS 超报价实际响应用量仍保存，后续调用暂停核对，不将超限费用裁成报价");
    }
}
