using Learning;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
public static class BuilderSemanticLedgerCases
{
    static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    sealed class Paused(bool failure=false):IBuilderSemanticProvider
    {
        public TaskCompletionSource Started {get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public TaskCompletionSource Release {get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public async Task<BuilderProviderResponse> Generate(BuilderSemanticInput input,CancellationToken ct){Started.TrySetResult();await Release.Task.WaitAsync(ct);if(failure)throw new IOException("Controlled provider returned no confirmed response");return new("{}",new(13,7,0,null,"LocalMeasured"),false);}
    }
    sealed class Never:IBuilderSemanticProvider{public int Calls;public Task<BuilderProviderResponse> Generate(BuilderSemanticInput input,CancellationToken ct){Calls++;throw new Exception("Denied invocation reached provider");}}
    static async Task Denied(Func<Task> action,string code){try{await action();throw new Exception("Expected denial: "+code);}catch(ApiError e){Check(e.Code==code,"Wrong denial "+e.Code);}}
    public static async Task Run(Database owner)
    {
        await owner.Database.MigrateAsync();var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Omlx:Model","controlled-semantic-model"}}).Build();await using var db=new Database(new DbContextOptionsBuilder<Database>().UseNpgsql(owner.Database.GetConnectionString()).Options,config);
        var (actor,p)=await BuilderSemanticPreparationCases.Seed(db);await db.Families.Where(f=>f.Id==actor.FamilyId).ExecuteUpdateAsync(u=>u.SetProperty(f=>f.OwnerAccountId,actor.AccountId));db.ChangeTracker.Clear();
        await using var lease=await BackgroundJobs.Claim(db,types:[BuilderSemanticJobs.Type],inputRef:p.Id)??throw new Exception("No preparation lease");var frozen=Json.Read<BuilderSemanticFrozenInput>(p.Snapshot);var input=Json.Read<BuilderSemanticInput>(frozen.ModelInputPayload);var model=BuilderSemanticJobs.ResolveLocal(frozen);
        var library=await db.Releases.SingleAsync(r=>r.Id==p.LibraryReleaseId);await Publishing.Register(db,library);var catalog=Json.Read<Catalog>(library.Payload);var draft=new ContentDraft{FamilyId=p.FamilyId,Title="Controlled shared-budget mapping fixture",Payload=library.Payload};db.Add(draft);await db.SaveChangesAsync();var question=catalog.Questions[0];var selection=new MappingOwnerSelection("Question",question.Id,question.RevisionId);
        var mapping=await MappingJobs.Enqueue(db,actor,new(draft.Id,library.Id,[selection],"LocalOmlx"));await db.SaveChangesAsync();await using var mappingLease=await BackgroundJobs.Claim(db,types:[MappingJobs.Type],inputRef:mapping.Id)??throw new Exception("No real mapping lease");var mappingFrozen=Json.Read<MappingFrozenInput>(mapping.Snapshot);var mappingModel=MappingJobs.ResolveLocal(mappingFrozen);var mappingInput=MappingModelProtocol.Capture(catalog,draft.Id,[selection],catalog.Kcs);var mappingNever=new NeverMapping();
        var paused=new Paused();var pending=new BuilderSemanticCallTracking(db,p,model,lease,paused).Generate(input,lease.Token);await paused.Started.Task.WaitAsync(TimeSpan.FromSeconds(8));
        await using(var writer=BackgroundJobs.Open(owner))using(var deadline=new CancellationTokenSource(TimeSpan.FromSeconds(3)))await using(var tx=await writer.Database.BeginTransactionAsync(deadline.Token)){await writer.Lock(p.FamilyId,deadline.Token);writer.Audits.Add(new(){FamilyId=p.FamilyId,Action="SemanticProviderConcurrentWrite",Details="provider is still waiting"});await writer.SaveChangesAsync(deadline.Token);await tx.CommitAsync(deadline.Token);}
        var never=new Never();await Denied(()=>new BuilderSemanticCallTracking(db,p,model,lease,never).Generate(input,lease.Token),"BUILDER_CONCURRENCY_LIMIT");Check(never.Calls==0,"Semantic concurrency denial still called provider");await Denied(()=>new MappingModelCallTracking(db,mapping,mappingModel,mappingLease,mappingNever).Generate(mappingInput,mappingLease.Token),"BUILDER_CONCURRENCY_LIMIT");Check(mappingNever.Calls==0,"Mapping bypassed active semantic slot");
        await using(var builder=BackgroundJobs.Open(owner)){var denied=new BuilderCall{FamilyId=p.FamilyId,RunId=p.RunId,ExecutionId=Guid.NewGuid(),AttemptNumber=1,CallNumber=1,Provider="Mock",Model="fixture/1",InputHash=Content.Hash("controlled shared slot")};Check(await BuilderBudget.Reserve(builder,denied,BuilderQuote.Local,CancellationToken.None)=="BUILDER_CONCURRENCY_LIMIT","Builder bypassed active semantic slot");}
        paused.Release.TrySetResult();var response=await pending;Check(!response.OutputComplete,"Truncated response changed");var call=await db.Set<BuilderSemanticCall>().AsNoTracking().SingleAsync(c=>c.PreparationId==p.Id && c.Status=="Returned");Check(call.InputTokens==13 && call.OutputTokens==7 && call.BudgetState=="Settled" && call.ErrorCode=="LOCAL_PROVIDER_OUTPUT_INCOMPLETE","Real truncated return/usage not independently saved");Check(call.InputPayload==frozen.ModelInputPayload && call.ModelConfigPayload==frozen.ModelConfigPayload,"Frozen call provenance lost");
        await using(var tx=await db.Database.BeginTransactionAsync()){db.Audits.Add(new(){FamilyId=p.FamilyId,Action="SemanticUncommittedBusinessResult",Details="controlled rollback"});await db.SaveChangesAsync();await tx.RollbackAsync();}db.ChangeTracker.Clear();Check(await db.Set<BuilderSemanticCall>().AnyAsync(c=>c.Id==call.Id && c.Status=="Returned") && !await db.Audits.AnyAsync(a=>a.Action=="SemanticUncommittedBusinessResult"),"Business rollback erased independent call");
        try{await db.Set<BuilderSemanticCall>().Where(c=>c.Id==call.Id).ExecuteUpdateAsync(u=>u.SetProperty(c=>c.InputTokens,(long?)999));throw new Exception("Returned usage rewritten");}catch(Npgsql.PostgresException e){Check(e.SqlState=="23514","Wrong original call protection");}
        var failure=new Paused(true);var unknown=new BuilderSemanticCallTracking(db,p,model,lease,failure).Generate(input,lease.Token);await failure.Started.Task.WaitAsync(TimeSpan.FromSeconds(8));failure.Release.TrySetResult();try{await unknown;throw new Exception("Unknown provider failure accepted");}catch(IOException){}
        var failed=await db.Set<BuilderSemanticCall>().AsNoTracking().SingleAsync(c=>c.PreparationId==p.Id && c.Status=="Failed");Check(failed.InputTokens==null && failed.OutputTokens==null && failed.ChargedCost==null && (await BuilderBudget.State(db,p.FamilyId,failed.BudgetDay)).ActiveCalls==1,"Unknown call fabricated zeros or released slot");
        await Denied(()=>new BuilderSemanticCallTracking(db,p,model,lease,never).Generate(input,lease.Token),"BUILDER_CONCURRENCY_LIMIT");
        await using(var tx=await db.Database.BeginTransactionAsync()){await Denied(()=>BuilderSemanticCallTracking.Reconcile(db,actor,failed.Id,new(false,null,null,"未确认结束","受控记录")),"RECONCILIATION_REQUIRED");await tx.RollbackAsync();}
        await using(var tx=await db.Database.BeginTransactionAsync()){await BuilderSemanticCallTracking.Reconcile(db,actor,failed.Id,new(true,null,null,"已观察受控失败任务结束","受控提供者已抛出异常并完成任务"));await db.SaveChangesAsync();await tx.CommitAsync();}
        db.ChangeTracker.Clear();Check((await BuilderBudget.State(db,p.FamilyId,failed.BudgetDay)).ActiveCalls==0 && (await db.Set<BuilderSemanticCall>().SingleAsync(c=>c.Id==failed.Id)).InputTokens==null,"Append reconciliation changed original unknown values");
        await using(var tx=await db.Database.BeginTransactionAsync()){await Denied(()=>BuilderSemanticCallTracking.Reconcile(db,actor,failed.Id,new(true,null,null,"重复","重复")),"CALL_ALREADY_RESOLVED");await tx.RollbackAsync();}
        try{await db.Set<BuilderSemanticReconciliation>().Where(r=>r.CallId==failed.Id).ExecuteUpdateAsync(u=>u.SetProperty(r=>r.Reason,"覆盖原依据"));throw new Exception("Reconciliation rewritten");}catch(Npgsql.PostgresException e){Check(e.SqlState=="23514","Wrong append-only decision protection");}
        var mappingPaused=new PausedMapping();var mappingPending=new MappingModelCallTracking(db,mapping,mappingModel,mappingLease,mappingPaused).Generate(mappingInput,mappingLease.Token);await mappingPaused.Started.Task.WaitAsync(TimeSpan.FromSeconds(8));await Denied(()=>new BuilderSemanticCallTracking(db,p,model,lease,never).Generate(input,lease.Token),"BUILDER_CONCURRENCY_LIMIT");mappingPaused.Release.TrySetResult();await mappingPending;
        // Reverse direction: a real durable Builder start holds the same shared slot.
        BuilderCall active=new(){FamilyId=p.FamilyId,RunId=p.RunId,ExecutionId=Guid.NewGuid(),AttemptNumber=1,CallNumber=1,Provider="Mock",Model="fixture/1",InputHash=Content.Hash("controlled active builder")};await using(var builder=BackgroundJobs.Open(owner))Check(await BuilderBudget.Reserve(builder,active,BuilderQuote.Local,CancellationToken.None)==null,"Could not reserve controlled builder start");await Denied(()=>new BuilderSemanticCallTracking(db,p,model,lease,never).Generate(input,lease.Token),"BUILDER_CONCURRENCY_LIMIT");
        Check(await db.Candidates.Where(c=>c.Id==p.CandidateId).Select(c=>c.Status).SingleAsync()=="Pending","Call ledger changed human review state");
        Console.WriteLine("PASS real PG semantic independent starts/returns/unknown failures and append-only owner reconciliation; two-way shared Builder and Mapping budget denial, no family lock during controlled provider wait, raw truncated usage retained across business rollback, original facts immutable; no actual model calls");
    }
    sealed class NeverMapping:IMappingModelProvider{public int Calls;public Task<BuilderProviderResponse> Generate(MappingModelInput input,CancellationToken ct){Calls++;throw new Exception("Denied mapping reached provider");}}
    sealed class PausedMapping:IMappingModelProvider
    {
        public TaskCompletionSource Started {get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public TaskCompletionSource Release {get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public async Task<BuilderProviderResponse> Generate(MappingModelInput input,CancellationToken ct){Started.TrySetResult();await Release.Task.WaitAsync(ct);return new("{}",new(5,3,0,null,"LocalMeasured"));}
    }
    sealed class Hang:IBuilderSemanticProvider{public async Task<BuilderProviderResponse> Generate(BuilderSemanticInput input,CancellationToken ct){await Task.Delay(Timeout.Infinite,ct);throw new Exception("Unreachable controlled provider");}}
    sealed class Complete:IBuilderSemanticProvider{public Task<BuilderProviderResponse> Generate(BuilderSemanticInput input,CancellationToken ct)=>Task.FromResult(new BuilderProviderResponse("{}",new(5,3,0,null,"LocalMeasured")));}
    public static async Task Crash(Database owner,string mode)
    {
        await owner.Database.MigrateAsync();var configuration=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Omlx:Model","controlled-semantic-model"}}).Build();await using var db=new Database(new DbContextOptionsBuilder<Database>().UseNpgsql(owner.Database.GetConnectionString()).Options,configuration);
        if(mode=="semantic-ledger-crash-seed"){var (seedActor,p)=await BuilderSemanticPreparationCases.Seed(db);await db.Families.Where(f=>f.Id==seedActor.FamilyId).ExecuteUpdateAsync(u=>u.SetProperty(f=>f.OwnerAccountId,seedActor.AccountId));await db.Set<BackgroundJob>().Where(j=>j.Id==p.JobId).ExecuteUpdateAsync(u=>u.SetProperty(j=>j.LeaseSeconds,3).SetProperty(j=>j.HeartbeatSeconds,1));Console.WriteLine("Seeded explicitly controlled in-process provider fixture; not actual model quality");return;}
        var preparation=await db.Set<BuilderSemanticPreparation>().AsNoTracking().SingleAsync();await using var lease=await BackgroundJobs.Claim(db,types:[BuilderSemanticJobs.Type],inputRef:preparation.Id)??throw new Exception("No actual expired semantic lease");var frozen=Json.Read<BuilderSemanticFrozenInput>(preparation.Snapshot);var input=Json.Read<BuilderSemanticInput>(frozen.ModelInputPayload);var model=BuilderSemanticJobs.ResolveLocal(frozen);
        if(mode=="semantic-ledger-crash"){await new BuilderSemanticCallTracking(db,preparation,model,lease,new Hang()).Generate(input,lease.Token);throw new Exception("Controlled provider unexpectedly finished");}
        Check(mode=="semantic-ledger-crash-check","Unknown crash mode");var before=await db.Set<BuilderSemanticCall>().AsNoTracking().SingleAsync();Check(before.Status=="Started" && before.InputTokens==null && before.OutputTokens==null && before.FinishedAt==null,"Killed process rewrote unknown start facts");
        var never=new Never();await Denied(()=>new BuilderSemanticCallTracking(db,preparation,model,lease,never).Generate(input,lease.Token),"BUILDER_CONCURRENCY_LIMIT");Check(never.Calls==0 && await db.Set<JobLeaseAttempt>().AnyAsync(a=>a.JobId==preparation.JobId && a.Status=="LeaseExpired"),"Replacement did not verify real expired lease or bypassed unknown call");
        var receipt=Environment.GetEnvironmentVariable("SEMANTIC_CRASH_RECEIPT")??throw new Exception("Actual observed process termination evidence required");var actor=new Actor(Guid.NewGuid(),preparation.FamilyId,preparation.RequestedBy,null,"Parent","Parent,ContentEditor");
        await using(var tx=await db.Database.BeginTransactionAsync()){await BuilderSemanticCallTracking.Reconcile(db,actor,before.Id,new(true,null,null,"Observed the entire controlled in-process provider process terminate; not external oMLX termination",receipt));await db.SaveChangesAsync();await tx.CommitAsync();}
        await new BuilderSemanticCallTracking(db,preparation,model,lease,new Complete()).Generate(input,lease.Token);db.ChangeTracker.Clear();var original=await db.Set<BuilderSemanticCall>().AsNoTracking().SingleAsync(c=>c.Id==before.Id);Check(Json.Write(original)==Json.Write(before),"Owner append rewrote original killed-process unknown facts");Check(await db.Set<BuilderSemanticCall>().CountAsync(c=>c.Status=="Returned")==1,"Confirmed controlled process termination did not allow independent replacement call");Console.WriteLine("PASS actual SIGKILL start survives real lease expiry, unknown slot denies replacement until observed in-process provider termination is appended; original null values/start/lease history retained, independent replacement returned; no external model calls");
    }

}
