using Learning;
using Microsoft.EntityFrameworkCore;
public static class IncrementalCheckpointCases
{
    static void Check(bool yes,string message){if(!yes)throw new Exception(message);}
    public static async Task Run(Database db,string mode="incremental-checkpoints")
    {
        if(mode=="incremental-crash"){await using var crash=new Database(new DbContextOptionsBuilder<Database>().UseNpgsql(db.Database.GetConnectionString()).AddInterceptors(new CrashBeforeCommit()).Options);await AssessmentRebuildJobs.ProcessOne(crash);return;}
        if(mode=="incremental-recover")
        {
            await using var a=BackgroundJobs.Open(db);await using var b=BackgroundJobs.Open(db);await Task.WhenAll(AssessmentRebuildJobs.ProcessOne(a),AssessmentRebuildJobs.ProcessOne(b));var request=await db.Set<AssessmentRebuildRequest>().SingleAsync();var studentRow=await db.Students.SingleAsync();var generation=await db.Generations.SingleAsync(g=>g.Id==studentRow.ActiveGenerationId);Check(generation.Id==request.TargetGenerationId && generation.CalculationMode=="IncrementalAppend" && generation.ProcessedInputCount==1 && generation.IncrementalBaseGenerationId!=null && await db.Generations.CountAsync()==2 && await db.Set<AssessmentCheckpoint>().CountAsync()==2,"incremental crash recovery lost fixed target or recomputed prefix");Check(await db.Set<JobLeaseAttempt>().CountAsync(a=>a.Status=="Succeeded")==1 && await db.Set<JobLeaseAttempt>().CountAsync(a=>a.Status=="LeaseExpired")==1 && await db.Set<AssessmentRebuildResult>().CountAsync()==1,"incremental result/claim recovery incomplete");Console.WriteLine("PASS 增量结果真正中断后旧世代/状态不动，实际租约到期双消费者沿固定目标仅计算1条后缀并提交一份状态/结果");return;
        }
        await db.Database.MigrateAsync();var family=new Family();var account=new Account{FamilyId=family.Id,UserName="incremental-"+Guid.NewGuid()};var catalog=Content.Fixture();var skill=catalog.Kcs[0];var group=Guid.NewGuid();catalog=catalog with{Questions=catalog.Questions.Take(3).Select(q=>q with{Mappings=[new(skill.Id)],Policy="SingleKC",Difficulty="Medium",VariantGroupId=group}).ToArray()};var release=new Release{FamilyId=family.Id,Number=1,Payload=Json.Write(catalog),Hash=Content.Hash(Json.Write(catalog))};var student=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};db.AddRange(family,account,new FamilyMembership{FamilyId=family.Id,AccountId=account.Id,Roles="Parent"},release,student);await db.SaveChangesAsync();await Publishing.Register(db,release);await db.SaveChangesAsync();
        var attempts=new List<Attempt>();var stamp=new DateTimeOffset(2026,1,1,8,0,0,TimeSpan.Zero);
        async Task Append(int index)
        {
            var question=catalog.Questions[index];var task=new StudyTask{FamilyId=family.Id,StudentId=student.Id,ReleaseId=release.Id,QuestionId=question.Id};var session=new LearningSession{FamilyId=family.Id,StudentId=student.Id,TaskId=task.Id,ReleaseId=release.Id,QuestionId=question.Id};var attempt=new Attempt{FamilyId=family.Id,StudentId=student.Id,SessionId=session.Id,Number=1,ClientSubmissionId=Guid.NewGuid(),CreatedAt=stamp.AddMinutes(index)};db.AddRange(task,session,attempt,new Grading{FamilyId=family.Id,AttemptId=attempt.Id,Number=1,Result="Correct"});await db.SaveChangesAsync();attempts.Add(attempt);
        }
        async Task<Generation> Rebuild(){await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);student=await db.Students.SingleAsync();await Assessment.Rebuild(db,student);await tx.CommitAsync();db.ChangeTracker.Clear();return await db.Generations.SingleAsync(g=>g.Id==student.ActiveGenerationId);}
        await Append(0);await Append(1);var first=await Rebuild();Check(first.CalculationMode=="FullStream" && first.ProcessedInputCount==2 && first.IncrementalBaseGenerationId==null,"first checkpoint did not record real full stream");var frozen=(await db.Set<AssessmentCheckpoint>().SingleAsync()).Payload;var original=Json.Write(await db.Evidence.OrderBy(e=>e.Id).ToArrayAsync());
        await Append(2);
        if(mode=="incremental-seed")
        {
            await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);var actor=new Actor(Guid.NewGuid(),family.Id,account.Id,null,"Parent","Parent");await AssessmentRebuildJobs.Enqueue(db,actor,student.Id,"受控真实增量中断任务");await db.SaveChangesAsync();await tx.CommitAsync();}
            await db.Set<BackgroundJob>().ExecuteUpdateAsync(u=>u.SetProperty(j=>j.LeaseSeconds,3).SetProperty(j=>j.HeartbeatSeconds,1));return;
        }
        var next=await Rebuild();Check(next.CalculationMode=="IncrementalAppend" && next.ProcessedInputCount==1 && next.IncrementalBaseGenerationId==first.Id,"append recomputed old prefix");var parts=await db.Evidence.Where(e=>e.GenerationId==next.Id).OrderBy(e=>e.OccurredAt).ToArrayAsync();Check(parts.Select(e=>e.Weight).SequenceEqual(new[]{1m,.8m,.2m}),"checkpoint lost variant cap");Check(original==Json.Write(await db.Evidence.Where(e=>e.GenerationId==first.Id).OrderBy(e=>e.Id).ToArrayAsync()) && frozen==(await db.Set<AssessmentCheckpoint>().SingleAsync(c=>c.GenerationId==first.Id)).Payload,"old evidence/checkpoint modified");Check(await db.Set<AssessmentContext>().CountAsync(c=>c.GenerationId==next.Id)==3 && parts.All(e=>db.Set<AssessmentContext>().Any(c=>c.Id==e.ContextId && c.GenerationId==next.Id && c.AttemptId==e.AttemptId)),"forked contexts point to old generation");await Rebuild();Check(await db.Generations.CountAsync()==2 && await db.Set<AssessmentCheckpoint>().CountAsync()==2,"identical inputs fabricated checkpoint");
        var grade=await db.Gradings.SingleAsync(g=>g.AttemptId==attempts[0].Id);var correction=new CorrectionBatch{FamilyId=family.Id,StudentId=student.Id,ReleaseId=release.Id,Cause="Grading",AffectedAttemptIds=Json.Write(new[]{attempts[0].Id}),SourceGradingRevisionId=grade.Id,Reason="受控释放同构限额",ConfirmedBy=account.Id};db.AddRange(correction,new Grading{FamilyId=family.Id,AttemptId=attempts[0].Id,Number=2,Result="Incorrect",CorrectionBatchId=correction.Id,Method="ParentConfirmed",GradedBy=account.Id});await db.SaveChangesAsync();var changed=await Rebuild();Check(changed.CalculationMode=="FullStreamChangedPrefix" && changed.ProcessedInputCount==3 && changed.IncrementalBaseGenerationId==null,"changed grading used stale prefix");parts=await db.Evidence.Where(e=>e.GenerationId==changed.Id).OrderBy(e=>e.OccurredAt).ToArrayAsync();Check(parts.Select(e=>e.Weight).SequenceEqual(new[]{1m,.8m,.8m}) && (await db.Masteries.SingleAsync(m=>m.GenerationId==changed.Id)).Beta==3m,"AT15 corrected downstream cap not rebuilt");Check(await db.Set<EvidenceRevocation>().AnyAsync(r=>r.CorrectionBatchId==correction.Id && r.ReplacementGenerationId==changed.Id),"rebase lost correction revocation");
        Console.WriteLine("PASS 真实持久状态：初次完整流、下一批仅算1条后缀、原状态/证据不改且新上下文引用闭合；相同输入复用，更正前缀改变完整重算并释放下游限额");
        try{await db.Set<AssessmentCheckpoint>().Where(c=>c.GenerationId==first.Id).ExecuteUpdateAsync(u=>u.SetProperty(c=>c.InputCount,99));throw new Exception("checkpoint changed");}catch(Npgsql.PostgresException ex){Check(ex.SqlState=="23514","immutable state trigger missing");}
        // Explicit corrupt-state insertion fixture; no production state or immutable original record is rewritten.
        var bad=new Generation{FamilyId=family.Id,StudentId=student.Id,InputHash="controlled-corrupt-checkpoint",InputVersion=Assessment.InputHashVersion,CalculationMode="FullStream",ProcessedInputCount=0,Status="Active"};var badPayload=new IncrementalAssessment(family.Id,student.Id,bad.Id,student.TimeZone).Freeze();db.AddRange(bad,new AssessmentCheckpoint{FamilyId=family.Id,StudentId=student.Id,GenerationId=bad.Id,EngineVersion=IncrementalAssessment.Version,InputCount=0,PrefixHash=new string('0',64),Payload=badPayload,PayloadHash=new string('0',64)});student=await db.Students.SingleAsync();student.ActiveGenerationId=bad.Id;changed=await db.Generations.SingleAsync(g=>g.Id==changed.Id);changed.Status="Retired";await db.SaveChangesAsync();var beforeFailure=await db.Generations.CountAsync();
        try{await Rebuild();throw new Exception("corrupt state silently rebuilt");}catch(ApiError ex){Check(ex.Code=="INCREMENTAL_STATE_INVALID","wrong corruption rejection");}db.ChangeTracker.Clear();Check(await db.Generations.CountAsync()==beforeFailure && (await db.Students.SingleAsync()).ActiveGenerationId==bad.Id,"failed state changed active pointer or committed result");Console.WriteLine("PASS 明确损坏状态夹具：摘要错误停止且不提交新世代/指针，不静默覆盖原状态");
        student=await db.Students.SingleAsync();await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);await Assessment.Rebuild(db,student,forceFull:true);await tx.CommitAsync();}db.ChangeTracker.Clear();var recovered=await db.Generations.SingleAsync(g=>g.Id==(db.Students.Single().ActiveGenerationId));Check(recovered.Id!=bad.Id && recovered.CalculationMode=="FullStream" && recovered.ProcessedInputCount==3 && recovered.IncrementalBaseGenerationId==null && (await db.Set<AssessmentCheckpoint>().SingleAsync(c=>c.GenerationId==bad.Id)).PayloadHash==new string('0',64),"explicit full source rebuild failed or overwrote corrupted historical state");Console.WriteLine("PASS 明确从原始记录完整重建可恢复，重新核对来源并保留原损坏状态，不静默覆盖历史");
        await db.Students.Where(s=>s.Id==student.Id).ExecuteDeleteAsync();Check(!await db.Generations.AnyAsync() && !await db.Set<AssessmentCheckpoint>().AnyAsync() && !await db.Evidence.AnyAsync(),"self-base FK prevented privacy deletion");Console.WriteLine("PASS 状态不可修改，学生删除清理全世代/增量基线链/状态与证据");
    }
}
