using Learning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
public static class PlanProjectionCases
{
    static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
    public static async Task Run(Database db)
    {
        await db.GetService<IMigrator>().MigrateAsync("20261003195858_AssessmentConsumptionCursor");var family=new Family();var catalog=Content.Fixture();var release=new Release{FamilyId=family.Id,Number=1,Payload=Json.Write(catalog),Hash=Content.Hash(Json.Write(catalog))};var student=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};var day=DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow,TimeZoneInfo.FindSystemTimeZoneById(student.TimeZone)).DateTime);var historicalPlan=new Plan{FamilyId=family.Id,StudentId=student.Id,Date=day.AddDays(-5)};
        db.AddRange(family,release,student,historicalPlan);await db.SaveChangesAsync();await Publishing.Register(db,release);await db.SaveChangesAsync();
        var legacyId=Guid.NewGuid();await db.Database.ExecuteSqlInterpolatedAsync($"""INSERT INTO "PlanRevisions" ("Id","FamilyId","CreatedAt","PlanId","ReleaseId","Number","Budget","Reserved","Overflow","Status","InputHash","Candidates","Warnings","RuleVersion") VALUES ({legacyId},{family.Id},clock_timestamp(),{historicalPlan.Id},{release.Id},1,30,0,0,'Published','legacy-projection-unknown','[]','[]','plan/2')""");
        async Task<string> LegacyBytes()=>await db.Database.SqlQueryRaw<string>("""SELECT (to_jsonb(r)-'ProjectionSnapshot'-'ProjectionSnapshotHash')::text AS "Value" FROM "PlanRevisions" r WHERE "InputHash"='legacy-projection-unknown'""").SingleAsync();
        var original=await LegacyBytes();await db.Database.MigrateAsync();db.ChangeTracker.Clear();var legacy=await db.PlanRevisions.SingleAsync();Check(await LegacyBytes()==original && legacy.ProjectionSnapshot==null && legacy.ProjectionSnapshotHash==null,"upgrade rewrote historical plan or invented provenance");
        async Task<Outbox> Append(bool modern,DateTimeOffset sourceTime)
        {
            var question=catalog.Questions[0];var task=new StudyTask{FamilyId=family.Id,StudentId=student.Id,ReleaseId=release.Id,QuestionId=question.Id};var session=new LearningSession{FamilyId=family.Id,StudentId=student.Id,TaskId=task.Id,ReleaseId=release.Id,QuestionId=question.Id};var attempt=new Attempt{FamilyId=family.Id,StudentId=student.Id,SessionId=session.Id,Number=1,ClientSubmissionId=Guid.NewGuid(),Answer="999",CreatedAt=sourceTime};var grade=new Grading{FamilyId=family.Id,AttemptId=attempt.Id,Number=1,Result="Incorrect"};
            await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);db.AddRange(task,session,attempt,grade);await db.SaveChangesAsync();Outbox source;
            if(modern){var e=await DomainEvents.Append(db,family.Id,student.Id,attempt.Id,"Attempt","AttemptSubmitted",new{attemptId=attempt.Id,gradingId=grade.Id},attempt.Id);await db.SaveChangesAsync();source=await db.Outbox.SingleAsync(o=>o.Id==e.Id);}
            else{source=new Outbox{FamilyId=family.Id,StudentId=student.Id,AttemptId=attempt.Id,CreatedAt=sourceTime};db.Add(source);await db.SaveChangesAsync();}
            await tx.CommitAsync();return source;
        }
        async Task<PlanRevision> Generate()
        {
            db.ChangeTracker.Clear();await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);var current=await db.Students.SingleAsync(s=>s.Id==student.Id);var revision=await Planning.Generate(db,current,day);await db.SaveChangesAsync();await tx.CommitAsync();return revision;
        }
        async Task<StudyTask[]> Tasks(PlanRevision revision)=>await (from p in db.Placements join t in db.Tasks on p.TaskId equals t.Id where p.RevisionId==revision.Id orderby p.Sequence select t).ToArrayAsync();
        var first=await Append(true,DateTimeOffset.UtcNow.AddDays(-3));await ProjectionWorker.Consume(db,first);db.ChangeTracker.Clear();student=await db.Students.SingleAsync(s=>s.Id==student.Id);var generation=await db.Generations.SingleAsync(g=>g.Id==student.ActiveGenerationId);var cursor=await db.Set<AssessmentConsumerCursor>().SingleAsync();db.Add(new Progress{FamilyId=family.Id,StudentId=student.Id,Date=day,LessonId=catalog.Lessons[0].Id,ReleaseId=release.Id});await db.SaveChangesAsync();
        var healthy=await Generate();var healthyPayload=healthy.ProjectionSnapshot!;var healthySnapshot=Json.Read<PlanProjectionSnapshot>(healthyPayload);Check(!healthySnapshot.Conservative && healthySnapshot.Pending.Length==0 && healthySnapshot.GenerationId==generation.Id && healthySnapshot.GenerationInputHash==generation.InputHash && healthySnapshot.GenerationAttemptCursor==generation.Cursor && healthySnapshot.AssessmentEventSequence==cursor.LastEventSequence && healthySnapshot.AssessmentAppliedEventId==cursor.LastAppliedEventId && healthy.ProjectionSnapshotHash==Content.Hash(healthyPayload),"normal plan did not capture its actual generation and distinct event boundary");Check((await Tasks(healthy)).Any(t=>t.ReasonCode=="WRONG_DUE"),"actual past wrong attempt did not produce a due review baseline");
        Check((await Generate()).Id==healthy.Id,"capture clock created a new logical revision");Console.WriteLine("PASS 新计划固定实际世代/摘要/作答游标及独立事件边界，正常到期复习仍安排；仅采集时间变化不生成新修订；迁移保留历史全部旧字段和未知NULL");
        var locked=(await Tasks(healthy)).First(t=>t.ReasonCode=="WRONG_DUE");locked.Locked=true;locked.Status="Ready";var activePlan=await db.Plans.SingleAsync(p=>p.Id==healthy.PlanId);activePlan.ActiveRevisionId=healthy.Id;activePlan.Status="Published";(await db.PlanRevisions.SingleAsync(r=>r.Id==healthy.Id)).Status="Published";await db.SaveChangesAsync();var lockedBytes=Json.Write(locked);
        var fresh=await Append(true,DateTimeOffset.UtcNow);var recent=await Generate();var recentSnapshot=Json.Read<PlanProjectionSnapshot>(recent.ProjectionSnapshot!);Check(!recentSnapshot.Conservative && recentSnapshot.Pending.Single().EventId==fresh.Id && Json.Read<string[]>(recent.Warnings).Any(w=>w.StartsWith("PROJECTION_PENDING")),"fresh result failed to invalidate same-input draft or was misclassified as lag");
        // A controlled old legacy source represents an actual backlog, never a forged modern event timestamp.
        var overdue=await Append(false,DateTimeOffset.UtcNow.AddMinutes(-1));var conservative=await Generate();var frozen=conservative.ProjectionSnapshot!;var snapshot=Json.Read<PlanProjectionSnapshot>(frozen);Check(snapshot.Conservative && snapshot.Pending.Length==2 && snapshot.Pending.Any(o=>o.EventId==overdue.Id && o.DomainEventId==null) && snapshot.FailedCount==0 && snapshot.GenerationId==generation.Id && Json.Read<string[]>(conservative.Warnings).Any(w=>w.StartsWith("PROJECTION_LAG")),"old real pending source did not produce a conservative draft");var safeTasks=await Tasks(conservative);Check(safeTasks.Length>1 && Json.Write(safeTasks.Single(t=>t.Id==locked.Id))==lockedBytes && safeTasks.Where(t=>t.Id!=locked.Id).All(t=>t.ReasonCode=="SCHOOL_CONSERVATIVE" && t.Type=="Practice" && t.ReviewTargetId==null),"conservative draft used stale review or mastery-based recommendations");Check((await Generate()).Id==conservative.Id,"unchanged lag generated repeated revisions");Check((await db.PlanRevisions.SingleAsync(r=>r.Id==healthy.Id)).ProjectionSnapshot==healthyPayload,"new lag rewrote the original captured plan");Console.WriteLine("PASS 新积压改变实际输入即产生新草稿；超过30秒保留原评估依据但不按旧掌握/复习自动推荐，学校基础练习继续，重复生成复用，原快照字节保持");
        // Actual completion catches up all pending sources and updates the same active generation.
        await ProjectionWorker.Consume(db,fresh);var settled=await Generate();var settledSnapshot=Json.Read<PlanProjectionSnapshot>(settled.ProjectionSnapshot!);Check(!settledSnapshot.Conservative && settledSnapshot.Pending.Length==0 && settled.Id!=conservative.Id && settledSnapshot.GenerationId==generation.Id && settledSnapshot.GenerationAttemptCursor>snapshot.GenerationAttemptCursor && settledSnapshot.AssessmentEventSequence>snapshot.AssessmentEventSequence && (await Tasks(settled)).Any(t=>t.Id!=locked.Id && t.ReasonCode is "SCHOOL_CURRENT" or "RECHECK" or "WEAK_CONFIRMED" or "LOW_EVIDENCE"),"actual catch-up failed to restore normal recommendations and captured source progress");Check((await db.PlanRevisions.SingleAsync(r=>r.Id==conservative.Id)).ProjectionSnapshot==frozen,"catch-up changed historical lag facts");Console.WriteLine("PASS 真实消费者追平后新草稿恢复正常学习推荐，作答和事件进度分别变化；旧保守计划/状态依据不改");
        var exhausted=await Append(false,DateTimeOffset.UtcNow);exhausted.Retries=3;exhausted.Error="CONTROLLED_TERMINAL_FAILURE";await db.SaveChangesAsync();var failed=await Generate();var failedSnapshot=Json.Read<PlanProjectionSnapshot>(failed.ProjectionSnapshot!);Check(failedSnapshot.Conservative && failedSnapshot.FailedCount==1,"terminal failure younger than30 seconds was treated as healthy");Console.WriteLine("PASS 未超过30秒但实际重试耗尽的来源也生成保守草稿，失败原因保留于生成依据");
        // A real failed receipt-repair job can stop before the raw queue counter reaches three.
        db.ChangeTracker.Clear();var invalid=await db.Outbox.SingleAsync(o=>o.Id==fresh.Id);invalid.ProcessedAt=null;invalid.DomainEventId=null;invalid.RetryRound=1;await db.SaveChangesAsync();
        try{await ProjectionWorker.Consume(db,invalid);throw new Exception("damaged original modern source accepted");}catch(ApiError error){Check(error.Code=="DOMAIN_EVENT_INVALID","unexpected actual repair failure");}
        var stoppedPlan=await Generate();var stoppedSnapshot=Json.Read<PlanProjectionSnapshot>(stoppedPlan.ProjectionSnapshot!);Check(stoppedSnapshot.Conservative && stoppedSnapshot.FailedCount==2 && stoppedSnapshot.Pending.Single(o=>o.EventId==fresh.Id).Retries==1 && stoppedSnapshot.FailedJobs.Single().EventId==fresh.Id && stoppedSnapshot.FailedJobs.Single().ErrorCode=="DOMAIN_EVENT_INVALID","actual Failed job below raw retry limit was ignored");Console.WriteLine("PASS 实际失败的回执修复任务即使队列仅重试1次仍按失败保护，并保存原任务/事件/错误依据，不仅依赖次数或年龄");
        try{await db.PlanRevisions.Where(r=>r.Id==conservative.Id).ExecuteUpdateAsync(u=>u.SetProperty(r=>r.ProjectionSnapshot,(string?)null).SetProperty(r=>r.ProjectionSnapshotHash,(string?)null));throw new Exception("saved plan provenance cleared");}catch(Npgsql.PostgresException error){Check(error.SqlState=="23514","provenance guard failed");}
        try{await db.PlanRevisions.Where(r=>r.Id==legacyId).ExecuteUpdateAsync(u=>u.SetProperty(r=>r.ProjectionSnapshot,frozen).SetProperty(r=>r.ProjectionSnapshotHash,Content.Hash(frozen)));throw new Exception("legacy provenance backfilled");}catch(Npgsql.PostgresException error){Check(error.SqlState=="23514","legacy unknown guard failed");}
        var changing=await db.PlanRevisions.SingleAsync(r=>r.Id==conservative.Id);changing.Budget++;await db.SaveChangesAsync();Check(changing.ProjectionSnapshot==frozen,"ordinary budget edit changed original facts");
        await db.Students.Where(s=>s.Id==student.Id).ExecuteDeleteAsync();Check(!await db.PlanRevisions.AnyAsync() && !await db.Set<AssessmentConsumerCursor>().AnyAsync(),"privacy deletion retained plan provenance");Console.WriteLine("PASS 数据库拒绝清空/修改实际依据或补造历史依据；预算调整保留原来源，隐私删除清理计划和消费链");
    }
}
