using Learning;
using Microsoft.EntityFrameworkCore;
public static class ProjectionReceiptCases
{
    static void Check(bool value,string message){if(!value)throw new Exception(message);}
    public static async Task Run(Database db)
    {
        await db.Database.MigrateAsync();var family=new Family();var catalog=Content.Fixture();var release=new Release{FamilyId=family.Id,Number=1,Payload=Json.Write(catalog),Hash=Content.Hash(Json.Write(catalog))};var student=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};db.AddRange(family,release,student);await db.SaveChangesAsync();await Publishing.Register(db,release);await db.SaveChangesAsync();var events=new List<Outbox>();
        foreach(var question in catalog.Questions.Take(2))
        {
            var task=new StudyTask{FamilyId=family.Id,StudentId=student.Id,ReleaseId=release.Id,QuestionId=question.Id};var session=new LearningSession{FamilyId=family.Id,StudentId=student.Id,TaskId=task.Id,ReleaseId=release.Id,QuestionId=question.Id};var attempt=new Attempt{FamilyId=family.Id,StudentId=student.Id,SessionId=session.Id,ClientSubmissionId=Guid.NewGuid(),Number=1,Answer="999"};var row=new Outbox{FamilyId=family.Id,StudentId=student.Id,AttemptId=attempt.Id};db.AddRange(task,session,attempt,new Grading{FamilyId=family.Id,AttemptId=attempt.Id,Number=1,Result="Incorrect"},row);events.Add(row);await db.SaveChangesAsync();
        }
        await ProjectionJobs.Ensure(db);var target=(await db.Set<BackgroundJob>().AsNoTracking().SingleAsync(j=>j.InputRef==events[0].Id)).TargetGenerationId;
        Check(await ProjectionWorker.Consume(db,events[0]),"first projection not applied");db.ChangeTracker.Clear();var receipts=await db.Set<ConsumerReceipt>().OrderBy(r=>r.EventId).ToArrayAsync();
        Check(receipts.Length==2 && receipts.All(r=>r.GenerationId==target) && await db.Generations.CountAsync()==1 && await db.Outbox.CountAsync(o=>o.ProcessedAt!=null)==2,"coalesced events lost separate receipts or fixed result");Console.WriteLine("PASS 两待处理事件一次追平，每事件独立消费回执，同一个预先固定世代");
        var bytes=Json.Write(receipts);Check(!await ProjectionWorker.Consume(db,await db.Outbox.SingleAsync(o=>o.Id==events[1].Id)),"already coalesced event rebuilt");db.ChangeTracker.Clear();Check(await db.Generations.CountAsync()==1 && Json.Write(await db.Set<ConsumerReceipt>().OrderBy(r=>r.EventId).ToArrayAsync())==bytes,"receipt or generation changed on duplicate consumption");
        var second=await db.Outbox.SingleAsync(o=>o.Id==events[1].Id);second.ProcessedAt=null;second.RetryRound=1;await db.SaveChangesAsync();Check(!await ProjectionWorker.Consume(db,second),"existing receipt was not used to repair queue marker");db.ChangeTracker.Clear();Check((await db.Outbox.SingleAsync(o=>o.Id==second.Id)).ProcessedAt!=null && await db.Generations.CountAsync()==1 && Json.Write(await db.Set<ConsumerReceipt>().OrderBy(r=>r.EventId).ToArrayAsync())==bytes,"queue marker repair changed source receipt");Console.WriteLine("PASS 合并后另一领取及受控完成标记缺口均复用原回执，不再建世代、不改原回执");
        var original=receipts[0];db.Add(new ConsumerReceipt{FamilyId=original.FamilyId,StudentId=original.StudentId,EventId=original.EventId,JobId=original.JobId,GenerationId=original.GenerationId,InputHash=original.InputHash});try{await db.SaveChangesAsync();throw new Exception("duplicate receipt accepted");}catch(DbUpdateException e){Check(e.InnerException is Npgsql.PostgresException p && p.SqlState=="23505","receipt uniqueness not enforced");db.ChangeTracker.Clear();}
        await db.Students.Where(s=>s.Id==student.Id).ExecuteDeleteAsync();Check(!await db.Set<ConsumerReceipt>().AnyAsync() && !await db.Set<BackgroundJob>().AnyAsync(j=>j.Type=="AssessmentProjection") && !await db.Set<JobLeaseAttempt>().AnyAsync(),"student deletion retained projection job/receipt");Console.WriteLine("PASS 数据库拒绝同消费者/事件重复回执，学生删除清除评估任务和领取/消费记录");
        var learner=new Student{FamilyId=family.Id,ActiveReleaseId=release.Id};var q=catalog.Questions[0];var controlledTask=new StudyTask{FamilyId=family.Id,StudentId=learner.Id,ReleaseId=release.Id,QuestionId=q.Id};var controlledSession=new LearningSession{FamilyId=family.Id,StudentId=learner.Id,TaskId=controlledTask.Id,ReleaseId=release.Id,QuestionId=q.Id};var controlledAttempt=new Attempt{FamilyId=family.Id,StudentId=learner.Id,SessionId=controlledSession.Id,ClientSubmissionId=Guid.NewGuid(),Number=1,Answer="999"};var controlledEvent=new Outbox{FamilyId=family.Id,StudentId=learner.Id,AttemptId=controlledAttempt.Id};db.AddRange(learner,controlledTask,controlledSession,controlledAttempt,controlledEvent,new Grading{FamilyId=family.Id,AttemptId=controlledAttempt.Id,Number=1,Result="Incorrect"});await db.SaveChangesAsync();await ProjectionJobs.Ensure(db);
        var stopped=await db.Set<BackgroundJob>().SingleAsync(j=>j.InputRef==controlledEvent.Id);var fixedId=stopped.TargetGenerationId;stopped.Status="Running";stopped.AttemptCount=3;stopped.LeaseOwner=Guid.NewGuid().ToString();stopped.HeartbeatAt=DateTimeOffset.UtcNow.AddSeconds(-10);stopped.LeaseExpiresAt=DateTimeOffset.UtcNow.AddSeconds(-5);db.Add(new JobLeaseAttempt{FamilyId=family.Id,JobId=stopped.Id,Number=3,LeaseOwner=stopped.LeaseOwner,StartedAt=stopped.HeartbeatAt.Value});await db.SaveChangesAsync();
        try{await ProjectionWorker.Consume(db,controlledEvent);throw new Exception("exhausted projection executed");}catch(ApiError error){Check(error.Code=="JOB_ATTEMPTS_EXHAUSTED","wrong exhaustion failure");}
        db.ChangeTracker.Clear();Check(!await db.Generations.AnyAsync(g=>g.StudentId==learner.Id) && !await db.Set<ConsumerReceipt>().AnyAsync() && (await db.Outbox.SingleAsync(o=>o.Id==controlledEvent.Id)).Retries==3 && (await db.Set<BackgroundJob>().SingleAsync(j=>j.Id==stopped.Id)).Status=="Failed","exhaustion generated result or failed to stop");
        var retry=await db.Outbox.SingleAsync(o=>o.Id==controlledEvent.Id);retry.Retries=0;retry.RetryRound=1;retry.Error=null;await db.SaveChangesAsync();Check(await ProjectionWorker.Consume(db,retry),"human round did not recover");db.ChangeTracker.Clear();Check((await db.Students.SingleAsync(x=>x.Id==learner.Id)).ActiveGenerationId==fixedId && (await db.Set<ConsumerReceipt>().SingleAsync()).GenerationId==fixedId && await db.Set<JobLeaseAttempt>().CountAsync(x=>x.Status=="LeaseExpired")==1,"human retry changed fixed target or lost old claim");Console.WriteLine("PASS 受控耗尽状态只失败清理、零证据/回执；人工新轮次沿原固定目标恢复并保留旧领取");
    }
}
