using Learning;
using Microsoft.EntityFrameworkCore;
public static class ReviewTargetConfirmationCases
{
    static void Check(bool value,string message){if(!value)throw new Exception(message);}
    public static async Task Run(Database db,string mode)
    {
        if(mode=="review-confirm-crash")
        {
            await using var crash=new Database(new DbContextOptionsBuilder<Database>().UseNpgsql(db.Database.GetConnectionString()).AddInterceptors(new CrashBeforeCommit()).Options);await ProjectionWorker.ProcessOne(crash);return;
        }
        if(mode=="review-confirm-recover")
        {
            await using var a=BackgroundJobs.Open(db);await using var b=BackgroundJobs.Open(db);await Task.WhenAll(ProjectionWorker.ProcessOne(a),ProjectionWorker.ProcessOne(b));db.ChangeTracker.Clear();var decision=await db.Set<ReviewTargetConfirmation>().SingleAsync();var learner=await db.Students.SingleAsync();var generation=await db.Generations.SingleAsync(g=>g.Id==learner.ActiveGenerationId);var job=await db.Set<BackgroundJob>().SingleAsync();
            Check(generation.Id==job.TargetGenerationId && generation.CalculationMode=="FullStreamChangedPrefix" && generation.ProcessedInputCount==21 && await db.Generations.CountAsync()==2 && await db.Set<AssessmentCheckpoint>().CountAsync()==2 && await db.Set<ConsumerReceipt>().CountAsync()==1,"actual confirmation recovery lost fixed target or duplicated results");
            var reviews=await db.Reviews.Where(r=>r.GenerationId==generation.Id && r.TargetType=="KC").ToArrayAsync();Check(reviews.Single(r=>r.TargetId==decision.OriginalTargetId).Stage=="R1" && reviews.Single(r=>r.TargetId==decision.ConfirmedTargetId).Stage=="LowFrequency","confirmation recovery used the wrong review target");Check(await db.Set<JobLeaseAttempt>().CountAsync(l=>l.Status=="LeaseExpired")==1 && await db.Set<JobLeaseAttempt>().CountAsync(l=>l.Status=="Succeeded")==1,"confirmation recovery lost historical expired claim");Console.WriteLine("PASS 确认来源真实提交前中断后，租约实际到期双消费者沿固定目标仅提交一份新状态/回执，原目标仍到期、实际目标复测生效，原确认及旧领取保留");return;
        }
        var modern=mode.Contains("modern",StringComparison.Ordinal) || Environment.GetEnvironmentVariable("REVIEW_CONFIRM_MODERN")=="1";await db.Database.MigrateAsync();var family=new Family();var account=new Account{FamilyId=family.Id,UserName=Environment.GetEnvironmentVariable("REVIEW_CONFIRM_USERNAME")??"review-confirm-"+Guid.NewGuid(),PasswordHash=Security.Password(Environment.GetEnvironmentVariable("REVIEW_CONFIRM_PASSWORD")??"isolated-review-confirm-password")};var baseCatalog=Content.Fixture();var first=baseCatalog.Kcs[0];var second=baseCatalog.Kcs.First(k=>k.Id!=first.Id);
        var questions=Enumerable.Range(0,21).Select(n=>baseCatalog.Questions[0] with{Id=Guid.NewGuid(),RevisionId=Guid.NewGuid(),VariantGroupId=null,Policy="SingleKC",Difficulty="Medium",Mappings=[new(n>=10 && n<20?second.Id:first.Id)]}).ToArray();var original=baseCatalog with{Questions=questions.Concat(baseCatalog.Questions).ToArray()};var corrected=original with{Questions=original.Questions.Select((q,n)=>n==20?q with{RevisionId=Guid.NewGuid(),Mappings=[new(second.Id)]}:q).ToArray()};var r1=new Release{FamilyId=family.Id,Number=1,Payload=Json.Write(original),Hash=Content.Hash(Json.Write(original))};var r2=new Release{FamilyId=family.Id,Number=2,Payload=Json.Write(corrected),Hash=Content.Hash(Json.Write(corrected))};var student=new Student{FamilyId=family.Id,Name="复习目标确认验收",ActiveReleaseId=r2.Id,TimeZone="UTC"};db.AddRange(family,account,new FamilyMembership{FamilyId=family.Id,AccountId=account.Id,Roles=modern?"Parent,ContentEditor,Publisher":"Parent"},r1,r2,student);await db.SaveChangesAsync();
        async Task Register(Release release)
        {
            if(!modern){await Publishing.Register(db,release);await db.SaveChangesAsync();return;}
            var reviewer=new Actor(Guid.NewGuid(),family.Id,account.Id,null,"Parent","Parent,ContentEditor,Publisher");var draft=new ContentDraft{FamilyId=family.Id,Payload=release.Payload,Title="受控现代审核发布夹具"};db.Add(draft);await db.SaveChangesAsync();await ContentReviews.Approve(db,reviewer,draft,new(draft.Version,"隔离验收实际整份审核"));await db.SaveChangesAsync();var review=await ContentReviews.ForPublish(db,draft);release.PublishedBy=account.Id;await Publishing.Register(db,release,review);review.PublishedReleaseId=release.Id;review.PublishedMappingVersion="mapping-container/1";draft.Status="Published";await db.SaveChangesAsync();
        }
        await Register(r1);await Register(r2);
        var time=new DateTimeOffset(2026,1,1,8,0,0,TimeSpan.Zero);Attempt? answer=null;StudyTask? reviewTask=null;
        for(var n=0;n<questions.Length;n++){var q=questions[n];var fixedMapping=await PublishedMappings.Resolve(db,r1,q);var task=new StudyTask{FamilyId=family.Id,StudentId=student.Id,ReleaseId=r1.Id,QuestionId=q.Id,Type=n==20?"Review":"Practice",ReviewTargetId=n==20?first.Id:null,Status="Completed",CompletedAt=time.AddDays(n==20?8:0).AddMinutes(n)};var session=new LearningSession{FamilyId=family.Id,StudentId=student.Id,TaskId=task.Id,ReleaseId=r1.Id,QuestionId=q.Id,QuestionRevisionId=q.RevisionId,MappingSetRevisionId=fixedMapping};var attempt=new Attempt{FamilyId=family.Id,StudentId=student.Id,SessionId=session.Id,QuestionRevisionId=q.RevisionId,MappingSetRevisionId=fixedMapping,Number=1,ClientSubmissionId=Guid.NewGuid(),Answer=q.Answer,CreatedAt=task.CompletedAt.Value};db.AddRange(task,session,attempt,new Grading{FamilyId=family.Id,AttemptId=attempt.Id,Number=1,Result="Correct"});await db.SaveChangesAsync();if(n==20){answer=attempt;reviewTask=task;}}
        var publishedPlan=new Plan{FamilyId=family.Id,StudentId=student.Id,Date=new(2026,1,9),Status="Published"};var publishedRevision=new PlanRevision{FamilyId=family.Id,PlanId=publishedPlan.Id,ReleaseId=r1.Id,Number=1,Budget=30,Status="Published",InputHash="controlled-original-published-plan"};db.AddRange(publishedPlan,publishedRevision,new Placement{FamilyId=family.Id,RevisionId=publishedRevision.Id,TaskId=reviewTask!.Id,Sequence=1});await db.SaveChangesAsync();publishedPlan.ActiveRevisionId=publishedRevision.Id;await db.SaveChangesAsync();
        // Controlled already-confirmed mapping and published-plan fixtures, not HTTP publication claims.
        var batch=new CorrectionBatch{FamilyId=family.Id,StudentId=student.Id,ReleaseId=r2.Id,Cause="Mapping",AffectedAttemptIds=Json.Write(new[]{answer!.Id}),ConfirmedBy=account.Id,Reason="隔离数据库受控映射更正"};db.AddRange(batch,new CorrectionItem{FamilyId=family.Id,BatchId=batch.Id,AttemptId=answer.Id,MappingReleaseId=r2.Id,QuestionRevisionId=corrected.Questions[20].RevisionId,MappingSetRevisionId=await PublishedMappings.Resolve(db,r2,corrected.Questions[20])});await db.SaveChangesAsync();
        await using(var tx=await db.Database.BeginTransactionAsync()){await db.Lock(family.Id);await Assessment.Rebuild(db,student);await tx.CommitAsync();}db.ChangeTracker.Clear();var actor=new Actor(Guid.NewGuid(),family.Id,account.Id,null,"Parent","Parent");
        if(mode=="review-confirm-api-seed"){Console.WriteLine(Json.Write(new{studentId=student.Id,attemptId=answer.Id,originalTarget=first.Id,actualTarget=second.Id,taskId=reviewTask!.Id,familyId=family.Id,mappingMode=modern?"FixedContainer":"LegacySnapshot"}));return;}
        var frozen=await Bytes(db,student.Id);var oldGeneration=student.ActiveGenerationId!.Value;var oldCheckpoint=Json.Write(await db.Set<AssessmentCheckpoint>().Where(c=>c.GenerationId==oldGeneration).ToArrayAsync());var oldEvidence=Json.Write(await db.Evidence.Where(e=>e.GenerationId==oldGeneration).OrderBy(e=>e.Id).ToArrayAsync());var oldReviews=Json.Write(await db.Reviews.Where(r=>r.GenerationId==oldGeneration).OrderBy(r=>r.Id).ToArrayAsync());
        var changes=await ReviewTargetConfirmations.Read(db,actor,student.Id);Check(changes.Length==1 && changes[0].Confirmation==null && changes[0].MeasuredTargets.Single().Id==second.Id,"actual change preview fabricated a confirmation");
        async Task<ReviewTargetConfirmation> Confirm(string action,Guid? target){var input=new ReviewTargetDecisionInput(action,target,"实际核对原任务与当前测量目标");var preview=await ReviewTargetConfirmations.Preview(db,actor,student.Id,answer.Id,input);await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);var row=await ReviewTargetConfirmations.Confirm(db,actor,student.Id,answer.Id,input with{PreviewHash=preview.PreviewHash});await db.SaveChangesAsync();await tx.CommitAsync();return row;}
        async Task Consume(){await ProjectionWorker.ProcessOne(db);db.ChangeTracker.Clear();}
        async Task Stages(bool adopted){var current=(await db.Students.SingleAsync(s=>s.Id==student.Id)).ActiveGenerationId;var reviews=await db.Reviews.Where(r=>r.GenerationId==current && r.TargetType=="KC").ToArrayAsync();Check(reviews.Single(r=>r.TargetId==first.Id).Stage=="R1" && reviews.Single(r=>r.TargetId==first.Id).DueDate==new DateOnly(2026,1,8),"original target was silently completed");Check(reviews.Single(r=>r.TargetId==second.Id).Stage==(adopted?"LowFrequency":"R1"),"actual target did not follow the confirmed choice");}
        if(modern){var (fixedInputs,_)=await Assessment.LoadInputs(db,await db.Students.SingleAsync(s=>s.Id==student.Id));Check(fixedInputs.All(i=>i.MappingSetRevisionId!=null),"modern fixture lost actual fixed mapping containers");Console.WriteLine("PASS 当前实际审核发布夹具的全部来源均固定准确映射容器，不借LegacySnapshot绕过现代引用门禁");}
        if(mode=="review-confirm-crash-seed")
        {
            await Confirm("AdoptMeasuredTarget",second.Id);await ProjectionJobs.Ensure(db);await db.Set<BackgroundJob>().ExecuteUpdateAsync(u=>u.SetProperty(j=>j.LeaseSeconds,3).SetProperty(j=>j.HeartbeatSeconds,1));return;
        }
        var kept=await Confirm("KeepOriginal",null);await Stages(false);Check(await db.Outbox.AnyAsync(o=>o.ProcessedAt==null),"confirmation pretended background completion");await Consume();await Stages(false);var keptBytes=Json.Write(await db.Set<ReviewTargetConfirmation>().AsNoTracking().SingleAsync(c=>c.Id==kept.Id));var report=await ReviewReporting.Read(db,student.Id,"UTC",new(2026,1,1),new(2026,1,10),default);Check(report.IndependentPasses==0 && report.Items.Single().Reason=="TARGET_RETAINED","kept target reported as passed");Console.WriteLine("PASS 实际家长保留原目标确认追加依据及真实待消费事件，后台完成后两个目标仍待复习，周报区分已确认保留");
        var adopted=await Confirm("AdoptMeasuredTarget",second.Id);await Stages(false);await Consume();await Stages(true);report=await ReviewReporting.Read(db,student.Id,"UTC",new(2026,1,1),new(2026,1,10),default);Check(report.IndependentPasses==1 && report.Items.Single().Reason=="TRUSTED_TARGET_CONFIRMED","actual target confirmation absent from report");Check(keptBytes==Json.Write(await db.Set<ReviewTargetConfirmation>().AsNoTracking().SingleAsync(c=>c.Id==kept.Id)) && await Bytes(db,student.Id)==frozen && oldCheckpoint==Json.Write(await db.Set<AssessmentCheckpoint>().Where(c=>c.GenerationId==oldGeneration).ToArrayAsync()) && oldEvidence==Json.Write(await db.Evidence.Where(e=>e.GenerationId==oldGeneration).OrderBy(e=>e.Id).ToArrayAsync()) && oldReviews==Json.Write(await db.Reviews.Where(r=>r.GenerationId==oldGeneration).OrderBy(r=>r.Id).ToArrayAsync()),"parent confirmation changed original task/answers/grading/history");Check(!await db.Set<EvidenceRevocation>().AnyAsync(),"review choice fabricated mathematical evidence revocations");Console.WriteLine("PASS 改为实际测量目标的明确确认经真实消费者才推进其到期复测；原目标/任务/作答/判分/检查点/证据/复习及上一选择原字节保持，无掌握证据转移");
        var staleInput=new ReviewTargetDecisionInput("KeepOriginal",null,"核对期间判分发生变化");var stalePreview=await ReviewTargetConfirmations.Preview(db,actor,student.Id,answer.Id,staleInput);db.Add(new Grading{FamilyId=family.Id,AttemptId=answer.Id,Number=2,Result="Incorrect",Method="ParentConfirmed",GradedBy=account.Id});await db.SaveChangesAsync();try{await using var tx=await db.Database.BeginTransactionAsync();await db.Lock(family.Id);await ReviewTargetConfirmations.Confirm(db,actor,student.Id,answer.Id,staleInput with{PreviewHash=stalePreview.PreviewHash});throw new Exception("stale grading preview accepted");}catch(ApiError ex){Check(ex.Code=="REVIEW_TARGET_PREVIEW_CHANGED","wrong stale preview rejection");}
        try{await ReviewTargetConfirmations.Preview(db,actor,student.Id,answer.Id,new("AdoptMeasuredTarget",first.Id,"未测量目标不能采用"));throw new Exception("unmeasured target accepted");}catch(ApiError ex){Check(ex.Code=="REVIEW_TARGET_NOT_MEASURED","wrong unmeasured target rejection");}
        try{await db.Set<ReviewTargetConfirmation>().Where(c=>c.Id==adopted.Id).ExecuteUpdateAsync(u=>u.SetProperty(c=>c.Reason,"覆盖原说明"));throw new Exception("immutable decision changed");}catch(Npgsql.PostgresException ex){Check(ex.SqlState=="23514","missing immutable decision guard");}Console.WriteLine("PASS 判分变化拒绝旧预览，未测量目标拒绝采用；数据库拒绝原地修改确认记录");
        var correctedAgain=corrected with{Questions=corrected.Questions.Select((q,n)=>n==20?q with{RevisionId=Guid.NewGuid(),Mappings=[new(first.Id)]}:q).ToArray()};var r3=new Release{FamilyId=family.Id,Number=3,Payload=Json.Write(correctedAgain),Hash=Content.Hash(Json.Write(correctedAgain))};db.Add(r3);await db.SaveChangesAsync();await Register(r3);var again=new CorrectionBatch{FamilyId=family.Id,StudentId=student.Id,ReleaseId=r3.Id,Cause="Mapping",AffectedAttemptIds=Json.Write(new[]{answer.Id}),ConfirmedBy=account.Id};db.AddRange(again,new CorrectionItem{FamilyId=family.Id,BatchId=again.Id,AttemptId=answer.Id,MappingReleaseId=r3.Id,QuestionRevisionId=correctedAgain.Questions[20].RevisionId,MappingSetRevisionId=await PublishedMappings.Resolve(db,r3,correctedAgain.Questions[20])});await db.SaveChangesAsync();var (sources,_)=await Assessment.LoadInputs(db,await db.Students.SingleAsync(s=>s.Id==student.Id));Check(sources.Single(i=>i.Attempt.Id==answer.Id).ReviewConfirmation==null && await db.Set<ReviewTargetConfirmation>().CountAsync()==2,"new mapping silently reused or erased old confirmation");Console.WriteLine("PASS 有效映射再次变化后旧确认不沿用，原两次确认仍保留，不回填新确认");
        await db.Families.Where(f=>f.Id==family.Id).ExecuteDeleteAsync();Check(!await db.Set<ReviewTargetConfirmation>().AnyAsync() && !await db.Outbox.AnyAsync(),"family privacy deletion left decisions or consumer sources");Console.WriteLine("PASS 家庭删除清理确认、相关实际事件及消费链");
    }
    static async Task<string> Bytes(Database db,Guid student)=>Json.Write(new{tasks=await db.Tasks.AsNoTracking().Where(t=>t.StudentId==student).OrderBy(t=>t.Id).ToArrayAsync(),attempts=await db.Attempts.AsNoTracking().Where(a=>a.StudentId==student).OrderBy(a=>a.Sequence).ToArrayAsync(),gradings=await db.Gradings.AsNoTracking().Where(g=>db.Attempts.Any(a=>a.Id==g.AttemptId && a.StudentId==student)).OrderBy(g=>g.Id).ToArrayAsync()});
}
