using Microsoft.EntityFrameworkCore;

namespace Learning;
public class Database(DbContextOptions<Database> options,IConfiguration? configuration=null) : DbContext(options)
{
    public IConfiguration RuntimeConfiguration {get;}=configuration??new ConfigurationBuilder().Build();
    public DbSet<Family> Families => Set<Family>();
    public DbSet<Account> Accounts => Set<Account>();
    public DbSet<AuthSession> AuthSessions => Set<AuthSession>();
    public DbSet<Student> Students => Set<Student>();
    public DbSet<Availability> Availabilities => Set<Availability>();
    public DbSet<Progress> Progresses => Set<Progress>();
    public DbSet<Goal> Goals => Set<Goal>();
    public DbSet<ContentDraft> Drafts => Set<ContentDraft>();
    public DbSet<Release> Releases => Set<Release>();
    public DbSet<Plan> Plans => Set<Plan>();
    public DbSet<PlanRevision> PlanRevisions => Set<PlanRevision>();
    public DbSet<StudyTask> Tasks => Set<StudyTask>();
    public DbSet<Placement> Placements => Set<Placement>();
    public DbSet<LearningSession> Sessions => Set<LearningSession>();
    public DbSet<Attempt> Attempts => Set<Attempt>();
    public DbSet<Grading> Gradings => Set<Grading>();
    public DbSet<Outbox> Outbox => Set<Outbox>();
    public DbSet<Generation> Generations => Set<Generation>();
    public DbSet<Evidence> Evidence => Set<Evidence>();
    public DbSet<Mastery> Masteries => Set<Mastery>();
    public DbSet<Review> Reviews => Set<Review>();
    public DbSet<Source> Sources => Set<Source>();
    public DbSet<Chunk> Chunks => Set<Chunk>();
    public DbSet<BuilderRun> BuilderRuns => Set<BuilderRun>();
    public DbSet<Candidate> Candidates => Set<Candidate>();
    public DbSet<Audit> Audits => Set<Audit>();
    public DbSet<CommandRecord> Commands => Set<CommandRecord>();
    protected override void OnModelCreating(ModelBuilder b)
    {
        // Each private entity has a concrete table and a mandatory family foreign key.
        foreach (var t in typeof(Row).Assembly.GetTypes().Where(t => t.IsSubclassOf(typeof(Row))))
        {
            var e = b.Entity(t);
            e.HasBaseType((Type?)null);
            e.HasKey("Id");
            e.HasOne(typeof(Family)).WithMany().HasForeignKey("FamilyId").OnDelete(DeleteBehavior.Cascade);
            e.HasIndex("FamilyId");
        }
        Foreign<Account,FileUploadTicket>(b,"OwnerAccountId");Foreign<PrivateFile,FileUploadTicket>(b,"CompletedFileId");
        b.Entity<FileUploadTicket>().HasIndex(t=>new{t.Status,t.ExpiresAt});
        b.Entity<FileUploadTicket>().ToTable(t=>{
            t.HasCheckConstraint("CK_UploadTicket_Declaration","\"Size\" BETWEEN 1 AND 10000000 AND length(\"Name\") BETWEEN 1 AND 200 AND \"Hash\" ~ '^[a-f0-9]{64}$' AND \"CredentialHash\" ~ '^[a-f0-9]{64}$' AND \"Purpose\" IN ('Attachment','LearningResource') AND \"ExpiresAt\">\"CreatedAt\" AND \"ExpiresAt\"<=\"CreatedAt\"+INTERVAL '15 minutes'");
            t.HasCheckConstraint("CK_UploadTicket_State","\"Status\" IN ('AwaitingBytes','Stored','Completed','Expired') AND ((\"Status\"='Stored' AND octet_length(\"StagedBytes\")=\"Size\") OR (\"Status\"<>'Stored' AND octet_length(\"StagedBytes\")=0)) AND ((\"Status\"='Completed' AND \"CompletedFileId\"=\"Id\" AND \"CompletedFileId\" IS NOT NULL) OR (\"Status\"<>'Completed' AND \"CompletedFileId\" IS NULL))");
        });
        b.Entity<Account>().HasIndex(x => x.UserName).IsUnique();
        b.Entity<AuthSession>().HasIndex(x => x.TokenHash).IsUnique();
        b.Entity<Availability>().HasIndex(x => new { x.StudentId, x.Date }).IsUnique();
        b.Entity<Progress>().HasIndex(x => new { x.StudentId, x.Date, x.LessonId }).IsUnique();
        b.Entity<Plan>().HasIndex(x => new { x.StudentId, x.Date }).IsUnique();
        b.Entity<PlanRevision>().Property(x=>x.RuleVersion).HasDefaultValue("legacy/unknown");
        b.Entity<PlanRevision>().ToTable(t=>t.HasCheckConstraint("CK_PlanRevision_ProjectionSnapshot","(\"ProjectionSnapshot\" IS NULL AND \"ProjectionSnapshotHash\" IS NULL) OR (\"ProjectionSnapshot\" IS NOT NULL AND length(\"ProjectionSnapshotHash\")=64 AND \"ProjectionSnapshotHash\" IS NOT NULL)"));
        b.Entity<PlanRevision>().HasIndex(x => new { x.PlanId, x.Number }).IsUnique();
        b.Entity<Placement>().HasIndex(x => new { x.RevisionId, x.TaskId }).IsUnique();
        b.Entity<Attempt>().HasIndex(x => new { x.StudentId, x.ClientSubmissionId }).IsUnique();
        b.Entity<Attempt>().HasIndex(x => new { x.SessionId, x.Number }).IsUnique();
        b.Entity<Attempt>().Property(x => x.Sequence).UseIdentityAlwaysColumn();
        b.Entity<Grading>().HasIndex(x => new { x.AttemptId, x.Number }).IsUnique();
        b.Entity<EvidenceRevocation>().HasIndex(r=>r.EvidenceId).IsUnique();
        Foreign<Student,EvidenceRevocation>(b,"StudentId");Foreign<Generation,EvidenceRevocation>(b,"ReplacementGenerationId");Foreign<Evidence,EvidenceRevocation>(b,"EvidenceId");Foreign<CorrectionBatch,EvidenceRevocation>(b,"CorrectionBatchId");
        Foreign<Grading,CorrectionBatch>(b,"SourceGradingRevisionId");Foreign<CorrectionBatch,Grading>(b,"CorrectionBatchId");Foreign<CorrectionBatch,AssessmentContext>(b,"GradingCorrectionBatchId");Foreign<CorrectionBatch,AssessmentContext>(b,"MappingCorrectionBatchId");
        b.Entity<AssessmentContext>().HasIndex(x=>new{x.GenerationId,x.AttemptId,x.GradingRevisionId,x.MappingSetRevisionId,x.EvidenceRuleVersion}).IsUnique();
        // One fixed latest grading per attempt in a complete generation also protects legacy NULL mappings.
        b.Entity<AssessmentContext>().HasIndex(x=>new{x.GenerationId,x.AttemptId}).IsUnique();
        b.Entity<AssessmentContext>().HasAlternateKey(x=>new{x.FamilyId,x.Id,x.GenerationId,x.StudentId,x.AttemptId,x.GradingRevisionId});
        b.Entity<Evidence>().HasOne<AssessmentContext>().WithMany().HasForeignKey("FamilyId","ContextId","GenerationId","StudentId","AttemptId","GradingId").HasPrincipalKey(x=>new{x.FamilyId,x.Id,x.GenerationId,x.StudentId,x.AttemptId,x.GradingRevisionId}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<Evidence>().HasIndex(x=>new{x.ContextId,x.KCId,x.Part,x.Positive}).IsUnique();
        Foreign<Student,AssessmentContext>(b,"StudentId");Foreign<Generation,AssessmentContext>(b,"GenerationId");Foreign<Attempt,AssessmentContext>(b,"AttemptId");Foreign<Grading,AssessmentContext>(b,"GradingRevisionId");Foreign<MappingSetRevision,AssessmentContext>(b,"MappingSetRevisionId");Foreign<ContentRevision,AssessmentContext>(b,"QuestionRevisionId");Foreign<Release,AssessmentContext>(b,"ContentReleaseId");Foreign<Release,AssessmentContext>(b,"MappingReleaseId");Foreign<CorrectionBatch,AssessmentContext>(b,"CorrectionBatchId");
        b.Entity<Evidence>().HasIndex(x => new { x.GenerationId, x.AttemptId, x.KCId, x.Part }).IsUnique();
        b.Entity<Mastery>().HasIndex(x => new { x.GenerationId, x.KCId }).IsUnique();
        b.Entity<Review>().HasIndex(x => new { x.GenerationId, x.TargetType, x.TargetId }).IsUnique();
        b.Entity<ReviewTargetConfirmation>().Property(x=>x.Sequence).UseIdentityAlwaysColumn();
        b.Entity<ReviewTargetConfirmation>().HasIndex(x=>new{x.AttemptId,x.Sequence}).IsUnique();
        b.Entity<ReviewTargetConfirmation>().ToTable(t=>t.HasCheckConstraint("CK_ReviewTargetConfirmation_Decision","\"Action\" IN ('KeepOriginal','AdoptMeasuredTarget') AND length(\"Reason\") BETWEEN 1 AND 1000 AND length(\"MeasurementHash\")=64 AND length(\"PreviewHash\")=64 AND jsonb_typeof(\"MeasurementSnapshot\"::jsonb)='object' AND ((\"Action\"='KeepOriginal' AND \"ConfirmedTargetId\"=\"OriginalTargetId\") OR (\"Action\"='AdoptMeasuredTarget' AND \"ConfirmedTargetId\"<>\"OriginalTargetId\"))"));
        b.Entity<Attempt>().HasAlternateKey(x=>new{x.FamilyId,x.Id,x.StudentId});
        b.Entity<StudyTask>().HasAlternateKey(x=>new{x.FamilyId,x.Id,x.StudentId});
        b.Entity<ReviewTargetConfirmation>().HasOne<Attempt>().WithMany().HasForeignKey(x=>new{x.FamilyId,x.AttemptId,x.StudentId}).HasPrincipalKey(x=>new{x.FamilyId,x.Id,x.StudentId}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<ReviewTargetConfirmation>().HasOne<StudyTask>().WithMany().HasForeignKey(x=>new{x.FamilyId,x.TaskId,x.StudentId}).HasPrincipalKey(x=>new{x.FamilyId,x.Id,x.StudentId}).OnDelete(DeleteBehavior.Cascade);
        Foreign<Student,ReviewTargetConfirmation>(b,"StudentId");Foreign<Account,ReviewTargetConfirmation>(b,"ConfirmedBy");Foreign<ContentIdentity,ReviewTargetConfirmation>(b,"OriginalTargetId");Foreign<ContentIdentity,ReviewTargetConfirmation>(b,"ConfirmedTargetId");Foreign<Release,ReviewTargetConfirmation>(b,"MappingReleaseId");Foreign<ContentRevision,ReviewTargetConfirmation>(b,"QuestionRevisionId");Foreign<MappingSetRevision,ReviewTargetConfirmation>(b,"MappingSetRevisionId");
        b.Entity<CommandRecord>().HasIndex(x => new { x.FamilyId, x.ActorId, x.Scope, x.Key }).IsUnique();
        b.Entity<Source>().HasIndex(x => new { x.FamilyId, x.Hash }).IsUnique();
        Foreign<Account, FamilyMembership>(b,"AccountId");
        b.Entity<FamilyMembership>().HasIndex(m=>new {m.FamilyId,m.AccountId}).IsUnique();
        b.Entity<Family>().HasOne<Account>().WithMany().HasForeignKey(f=>new {f.Id,f.OwnerAccountId}).HasPrincipalKey(a=>new {a.FamilyId,a.Id}).OnDelete(DeleteBehavior.Restrict);
        Foreign<Student, Audit>(b,"StudentId");
        Foreign<Student, ParentBurdenRecord>(b,"StudentId");
        Foreign<ParentBurdenRecord, ParentBurdenRecord>(b,"SupersedesId");
        b.Entity<ParentBurdenRecord>().HasIndex(r=>r.SupersedesId).IsUnique();
        b.Entity<ParentBurdenRecord>().HasIndex(r=>new{r.StudentId,r.Date});
        Foreign<Student, Goal>(b, "StudentId"); Foreign<Student, GoalChange>(b,"StudentId"); Foreign<Goal, GoalChange>(b,"GoalId");
        b.Entity<Goal>().Property(g=>g.Subject).HasDefaultValue("Unspecified");
        b.Entity<Goal>().Property(g=>g.GoalType).HasDefaultValue("Activity");
        b.Entity<Goal>().Property(g=>g.Period).HasDefaultValue("Daily");
        b.Entity<Goal>().Property(g=>g.ScheduleRule).HasDefaultValue("[1,2,3,4,5,6,0]");
        b.Entity<Goal>().Property(g=>g.TargetValue).HasDefaultValue(1);
        b.Entity<Goal>().Property(g=>g.Priority).HasDefaultValue(3);
        b.Entity<Goal>().Property(g=>g.Version).HasDefaultValue(1L);
        b.Entity<StudyTask>().Property(t=>t.GoalSnapshots).HasDefaultValue("[]");
        b.Entity<GoalChange>().HasIndex(x=>new{x.GoalId,x.Version}).IsUnique(); Foreign<Student, Availability>(b, "StudentId");
        Foreign<Student, Progress>(b, "StudentId"); Foreign<Release, Progress>(b,"ReleaseId"); Foreign<Student, ProgressChange>(b,"StudentId"); Foreign<Student, Plan>(b, "StudentId");
        Foreign<Student, StudyTask>(b, "StudentId"); Foreign<Student, LearningSession>(b, "StudentId");
        Foreign<Plan, PlanRevision>(b, "PlanId"); Foreign<PlanRevision, Placement>(b, "RevisionId");
        Foreign<StudyTask, Placement>(b, "TaskId"); Foreign<StudyTask, LearningSession>(b, "TaskId");
        Foreign<Release, LearningSession>(b, "ReleaseId"); Foreign<Release, StudyTask>(b, "ReleaseId");
        Foreign<ContentRevision, LearningSession>(b,"QuestionRevisionId"); Foreign<MappingSetRevision, LearningSession>(b,"MappingSetRevisionId");
        Foreign<ContentRevision, Attempt>(b,"QuestionRevisionId"); Foreign<MappingSetRevision, Attempt>(b,"MappingSetRevisionId");
        Foreign<MappingSetRevision, Evidence>(b,"MappingSetRevisionId");
        Foreign<ContentRevision, CorrectionItem>(b,"QuestionRevisionId"); Foreign<MappingSetRevision, CorrectionItem>(b,"MappingSetRevisionId");
        Foreign<LearningSession, Attempt>(b, "SessionId"); Foreign<Attempt, Grading>(b, "AttemptId");
        Foreign<Attempt, Outbox>(b, "AttemptId"); Foreign<Generation, Evidence>(b, "GenerationId");
        Foreign<Generation, Mastery>(b, "GenerationId"); Foreign<Generation, Review>(b, "GenerationId");
        Foreign<Attempt, Evidence>(b, "AttemptId"); Foreign<Grading, Evidence>(b, "GradingId");
        Foreign<Source, Chunk>(b, "SourceId"); Foreign<Source, BuilderRun>(b, "SourceId");
        Foreign<ContentDraft, ContentReviewRecord>(b,"DraftId"); Foreign<Account, ContentReviewRecord>(b,"ReviewerId"); Foreign<Release, ContentReviewRecord>(b,"PublishedReleaseId");
        b.Entity<ContentReviewRecord>().HasIndex(r=>new{r.DraftId,r.DraftVersion});
        Foreign<ContentDraft, IndependentMappingDraft>(b,"SourceDraftId");Foreign<MappingSetRevision, IndependentMappingDraft>(b,"SetRevisionId");Foreign<Release, IndependentMappingDraft>(b,"LibraryReleaseId");Foreign<Account, IndependentMappingDraft>(b,"SubmittedBy");
        b.Entity<IndependentMappingDraft>().HasIndex(d=>d.SetRevisionId).IsUnique();
        Foreign<Candidate,BuilderSemanticPreparation>(b,"CandidateId");Foreign<BuilderRun,BuilderSemanticPreparation>(b,"RunId");Foreign<BackgroundJob,BuilderSemanticPreparation>(b,"JobId");Foreign<Account,BuilderSemanticPreparation>(b,"RequestedBy");Foreign<Release,BuilderSemanticPreparation>(b,"LibraryReleaseId");
        b.Entity<BuilderSemanticPreparation>().HasIndex(p=>new{p.FamilyId,p.InputHash}).IsUnique();b.Entity<BuilderSemanticPreparation>().HasIndex(p=>p.JobId).IsUnique();b.Entity<BuilderSemanticPreparation>().ToTable(t=>t.HasCheckConstraint("CK_BuilderSemanticPreparation_Snapshot","jsonb_typeof(\"Snapshot\"::jsonb)='object' AND length(\"SnapshotHash\")=64 AND length(\"InputHash\")=64"));
        Foreign<ContentDraft,MappingPreparation>(b,"SourceDraftId");Foreign<Release,MappingPreparation>(b,"LibraryReleaseId");Foreign<Account,MappingPreparation>(b,"RequestedBy");Foreign<BackgroundJob,MappingPreparation>(b,"JobId");b.Entity<MappingPreparation>().HasIndex(p=>new{p.FamilyId,p.InputHash}).IsUnique();b.Entity<MappingPreparation>().HasIndex(p=>p.JobId).IsUnique();b.Entity<MappingPreparation>().HasIndex(p=>p.RunId).IsUnique();b.Entity<MappingPreparation>().ToTable(t=>t.HasCheckConstraint("CK_MappingPreparation_Snapshot","jsonb_typeof(\"Snapshot\"::jsonb)='object' AND length(\"SnapshotHash\")=64 AND length(\"InputHash\")=64 AND \"RunId\"<>'00000000-0000-0000-0000-000000000000'::uuid"));
        Foreign<ContentDraft, MappingRun>(b,"SourceDraftId"); Foreign<Release, MappingRun>(b,"LibraryReleaseId");
        b.Entity<MappingRun>().HasIndex(r=>new{r.FamilyId,r.InputHash}).IsUnique();
        Foreign<MappingRun, MappingSuggestion>(b,"RunId");
        b.Entity<MappingSuggestion>().HasIndex(s=>new{s.RunId,s.OwnerType,s.OwnerId}).IsUnique();
        b.Entity<MappingSuggestion>().ToTable(t=>t.HasCheckConstraint("CK_MappingSuggestion_ModelResult", "\"ModelResultPayload\" IS NULL OR (jsonb_typeof(\"ModelResultPayload\"::jsonb)='object' AND COALESCE((\"ModelResultPayload\"::jsonb->>'decision') IN ('Propose','NeedsReview'),false))"));
        Foreign<MappingSuggestion, MappingReviewDecision>(b,"SuggestionId"); Foreign<Account, MappingReviewDecision>(b,"ReviewerId"); Foreign<ContentDraft, MappingReviewDecision>(b,"CreatedDraftId");
        b.Entity<MappingReviewDecision>().HasIndex(d=>d.SuggestionId).IsUnique();
        Foreign<ContentDraft, MappingSetRevision>(b,"DraftId"); Foreign<MappingReviewDecision, MappingSetRevision>(b,"ReviewDecisionId"); Foreign<ContentReviewRecord, MappingSetRevision>(b,"ContentReviewRecordId");
        b.Entity<MappingSetRevision>().Property(s=>s.CoverageOrigin).HasDefaultValue("HumanReviewed");
        b.Entity<MappingSetRevision>().ToTable(t=>t.HasCheckConstraint("CK_MappingSetRevision_ReviewSource","(\"ReviewStatus\" = 'Draft' AND \"ReviewDecisionId\" IS NULL AND \"ContentReviewRecordId\" IS NULL) OR (\"ReviewStatus\" IN ('ReviewedDraft','ReviewedCatalog') AND ((\"ReviewDecisionId\" IS NOT NULL) <> (\"ContentReviewRecordId\" IS NOT NULL)))"));
        b.Entity<MappingSetRevision>().HasIndex(s=>new{s.FamilyId,s.OwnerType,s.OwnerRevisionId});
        Foreign<Release, ReleaseMappingSet>(b,"ReleaseId"); Foreign<MappingSetRevision, ReleaseMappingSet>(b,"SetRevisionId");
        b.Entity<ReleaseMappingSet>().HasIndex(s=>new{s.ReleaseId,s.OwnerType,s.OwnerId}).IsUnique();
        Foreign<MappingSetRevision, MappingSetItem>(b,"SetRevisionId"); Foreign<ContentIdentity, MappingSetItem>(b,"KCId"); Foreign<ContentRevision, MappingSetItem>(b,"KCRevisionId");
        b.Entity<MappingSetItem>().HasIndex(i=>new{i.SetRevisionId,i.Sequence}).IsUnique();
        b.Entity<BuilderBudgetPolicy>().HasIndex(p=>p.FamilyId).IsUnique();b.Entity<BuilderBudgetPolicy>().Property(p=>p.DailyCostLimit).HasPrecision(16,6);b.Entity<BuilderBudgetPolicy>().Property(p=>p.PerCallCostLimit).HasPrecision(16,6);b.Entity<BuilderCall>().Property(c=>c.ReservedCost).HasPrecision(16,6);
        b.Entity<BackgroundJob>().HasIndex(j=>new{j.FamilyId,j.Type,j.InputRef}).IsUnique();b.Entity<BackgroundJob>().HasIndex(j=>new{j.FamilyId,j.Type,j.IdempotencyKey}).IsUnique();b.Entity<BackgroundJob>().HasIndex(j=>new{j.Status,j.NextRunAt,j.LeaseExpiresAt});
        b.Entity<BackgroundJob>().ToTable(t=>{t.HasCheckConstraint("CK_BackgroundJob_Status","\"Status\" IN ('Queued','Running','Succeeded','Retrying','Failed','Cancelled')");t.HasCheckConstraint("CK_BackgroundJob_Limits","\"AttemptCount\">=0 AND \"AttemptCount\"<=\"MaxAttempts\" AND \"MaxAttempts\" BETWEEN 1 AND 10 AND \"RetryRound\">=0 AND \"LeaseSeconds\" BETWEEN 3 AND 300 AND \"HeartbeatSeconds\">=1 AND \"HeartbeatSeconds\"*2<=\"LeaseSeconds\"");t.HasCheckConstraint("CK_BackgroundJob_Lease","(\"Status\"='Running' AND \"LeaseOwner\" IS NOT NULL AND \"LeaseExpiresAt\" IS NOT NULL AND \"HeartbeatAt\" IS NOT NULL) OR (\"Status\"<>'Running' AND \"LeaseOwner\" IS NULL AND \"LeaseExpiresAt\" IS NULL)");});
        Foreign<BackgroundJob,JobLeaseAttempt>(b,"JobId");b.Entity<JobLeaseAttempt>().HasIndex(a=>new{a.JobId,a.LeaseOwner}).IsUnique();b.Entity<JobLeaseAttempt>().HasIndex(a=>new{a.JobId,a.RetryRound,a.Number}).IsUnique();
        Foreign<Student,BackgroundJob>(b,"StudentId");b.Entity<BackgroundJob>().HasIndex(j=>j.TargetGenerationId).IsUnique();
        Foreign<Student,AssessmentCheckpoint>(b,"StudentId");b.Entity<Generation>().HasAlternateKey(g=>new{g.FamilyId,g.Id,g.StudentId});b.Entity<AssessmentCheckpoint>().HasOne<Generation>().WithMany().HasForeignKey(c=>new{c.FamilyId,c.GenerationId,c.StudentId}).HasPrincipalKey(g=>new{g.FamilyId,g.Id,g.StudentId}).OnDelete(DeleteBehavior.Cascade);b.Entity<AssessmentCheckpoint>().HasIndex(c=>new{c.GenerationId,c.InputCount}).IsUnique();b.Entity<AssessmentCheckpoint>().ToTable(t=>t.HasCheckConstraint("CK_AssessmentCheckpoint_State","\"InputCount\">=0 AND length(\"PrefixHash\")=64 AND length(\"PayloadHash\")=64 AND jsonb_typeof(\"Payload\"::jsonb)='object'"));
        b.Entity<AssessmentCheckpoint>().HasAlternateKey(c=>new{c.FamilyId,c.Id,c.StudentId,c.GenerationId});
        b.Entity<AssessmentCheckpoint>().HasOne<AssessmentCheckpoint>().WithMany().HasForeignKey(c=>new{c.FamilyId,c.BaseCheckpointId,c.StudentId,c.GenerationId}).HasPrincipalKey(c=>new{c.FamilyId,c.Id,c.StudentId,c.GenerationId}).OnDelete(DeleteBehavior.NoAction);
        b.Entity<AssessmentCheckpoint>().ToTable(t=>t.HasCheckConstraint("CK_AssessmentCheckpoint_Storage","(\"StorageVersion\" IS NULL AND \"BaseCheckpointId\" IS NULL AND \"DeltaDepth\" IS NULL AND \"StatePayloadHash\" IS NULL) OR (\"StorageVersion\" IS NOT NULL AND \"StorageVersion\"='checkpoint-storage/1' AND \"StatePayloadHash\" IS NOT NULL AND length(\"StatePayloadHash\")=64 AND \"DeltaDepth\" IS NOT NULL AND ((\"DeltaDepth\"=0 AND \"BaseCheckpointId\" IS NULL) OR (\"DeltaDepth\" BETWEEN 1 AND 31 AND \"BaseCheckpointId\" IS NOT NULL AND \"BaseCheckpointId\"<>\"Id\")))"));
        b.Entity<ConsumerReceipt>().HasOne<AssessmentCheckpoint>().WithMany().HasForeignKey(r=>new{r.FamilyId,r.CheckpointId,r.StudentId,r.GenerationId}).HasPrincipalKey(c=>new{c.FamilyId,c.Id,c.StudentId,c.GenerationId}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<AssessmentRebuildResult>().HasOne<AssessmentCheckpoint>().WithMany().HasForeignKey(r=>new{r.FamilyId,r.CheckpointId,r.StudentId,r.GenerationId}).HasPrincipalKey(c=>new{c.FamilyId,c.Id,c.StudentId,c.GenerationId}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<AssessmentCheckpoint>().ToTable(t=>t.HasCheckConstraint("CK_AssessmentCheckpoint_Application","(\"InputHash\" IS NULL AND \"Cursor\" IS NULL AND \"CalculationMode\" IS NULL AND \"ProcessedInputCount\" IS NULL) OR (\"InputHash\" IS NOT NULL AND length(\"InputHash\")=64 AND \"Cursor\" IS NOT NULL AND \"Cursor\">=0 AND \"CalculationMode\" IS NOT NULL AND \"CalculationMode\" IN ('FullStream','FullStreamChangedPrefix','IncrementalAppend','OnlineAppend') AND \"ProcessedInputCount\" IS NOT NULL AND \"ProcessedInputCount\">=0 AND \"ProcessedInputCount\"<=\"InputCount\")"));
        b.Entity<Generation>().HasOne<Generation>().WithMany().HasForeignKey(g=>new{g.FamilyId,g.IncrementalBaseGenerationId,g.StudentId}).HasPrincipalKey(g=>new{g.FamilyId,g.Id,g.StudentId}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<Generation>().ToTable(t=>t.HasCheckConstraint("CK_Generations_Incremental","(\"CalculationMode\" IS NULL AND \"ProcessedInputCount\" IS NULL AND \"IncrementalBaseGenerationId\" IS NULL) OR (\"CalculationMode\" IS NOT NULL AND \"CalculationMode\" IN ('FullStream','FullStreamChangedPrefix','IncrementalAppend','OnlineAppend') AND \"ProcessedInputCount\" IS NOT NULL AND \"ProcessedInputCount\">=0 AND ((\"CalculationMode\"='IncrementalAppend' AND \"IncrementalBaseGenerationId\" IS NOT NULL AND \"IncrementalBaseGenerationId\"<>\"Id\") OR (\"CalculationMode\"<>'IncrementalAppend' AND \"IncrementalBaseGenerationId\" IS NULL)))"));
        Foreign<Student,AssessmentRebuildRequest>(b,"StudentId");Foreign<Account,AssessmentRebuildRequest>(b,"RequestedBy");Foreign<BackgroundJob,AssessmentRebuildRequest>(b,"JobId");b.Entity<AssessmentRebuildRequest>().HasIndex(r=>r.JobId).IsUnique();b.Entity<AssessmentRebuildRequest>().HasIndex(r=>r.TargetGenerationId).IsUnique();b.Entity<AssessmentRebuildRequest>().ToTable(t=>t.HasCheckConstraint("CK_AssessmentRebuildRequest_Snapshot","jsonb_typeof(\"Snapshot\"::jsonb)='object' AND length(\"SnapshotHash\")=64 AND length(\"Reason\") BETWEEN 1 AND 4000"));
        Foreign<Student,AssessmentRebuildResult>(b,"StudentId");Foreign<AssessmentRebuildRequest,AssessmentRebuildResult>(b,"RequestId");Foreign<BackgroundJob,AssessmentRebuildResult>(b,"JobId");Foreign<Generation,AssessmentRebuildResult>(b,"GenerationId");Foreign<DomainEvent,AssessmentRebuildResult>(b,"AppliedEventId");b.Entity<AssessmentRebuildResult>().HasIndex(r=>r.RequestId).IsUnique();b.Entity<AssessmentRebuildResult>().HasIndex(r=>r.AppliedEventId).IsUnique();
        b.Entity<BackgroundJob>().HasIndex(j=>new{j.FamilyId,j.StudentId});
        b.Entity<BackgroundJob>().HasIndex(j=>new{j.FamilyId,j.StudentId,j.Type}).IsUnique().HasFilter("\"Type\"='AssessmentRebuild' AND \"Status\" IN ('Queued','Running','Retrying')");
        Foreign<Student,DomainEvent>(b,"StudentId");Foreign<DomainEvent,Outbox>(b,"DomainEventId");Foreign<DomainEvent,ConsumerReceipt>(b,"DomainEventId");
        b.Entity<Outbox>().HasIndex(e=>e.DomainEventId).IsUnique();
        b.Entity<DomainEvent>().Property(e=>e.EventSequence).UseIdentityByDefaultColumn();b.Entity<DomainEvent>().HasIndex(e=>e.EventSequence).IsUnique();b.Entity<DomainEvent>().HasIndex(e=>new{e.FamilyId,e.StudentId,e.EventSequence});
        b.Entity<DomainEvent>().ToTable(t=>t.HasCheckConstraint("CK_DomainEvent_Envelope","\"EventSequence\">0 AND \"PayloadVersion\"=1 AND \"AggregateId\"<>'00000000-0000-0000-0000-000000000000'::uuid AND \"AggregateType\"<>'' AND \"EventType\" IN ('AttemptSubmitted','GradingConfirmed','AssessmentApplied','CorrectionConfirmed','TaskTransitioned','ProgressChanged','ContentReleasePublished') AND jsonb_typeof(\"Payload\"::jsonb)='object' AND length(\"PayloadHash\")=64 AND (\"DispatchTarget\" IS NULL OR \"DispatchTarget\"='assessment/1')"));
        Foreign<Student,AssessmentConsumerCursor>(b,"StudentId");Foreign<DomainEvent,AssessmentConsumerCursor>(b,"LastEventId");Foreign<DomainEvent,AssessmentConsumerCursor>(b,"LastAppliedEventId");
        b.Entity<ConsumerReceipt>().HasAlternateKey(r=>new{r.FamilyId,r.Id,r.StudentId,r.EventId,r.GenerationId,r.InputHash});
        b.Entity<AssessmentConsumerCursor>().HasOne<ConsumerReceipt>().WithMany().HasForeignKey(c=>new{c.FamilyId,c.LastReceiptId,c.StudentId,c.LastEventId,c.GenerationId,c.InputHash}).HasPrincipalKey(r=>new{r.FamilyId,r.Id,r.StudentId,r.EventId,r.GenerationId,r.InputHash}).OnDelete(DeleteBehavior.Cascade);
        b.Entity<AssessmentConsumerCursor>().HasIndex(c=>new{c.StudentId,c.ConsumerName}).IsUnique();b.Entity<AssessmentConsumerCursor>().Property(c=>c.LastEventSequence).IsConcurrencyToken();
        b.Entity<AssessmentConsumerCursor>().ToTable(t=>t.HasCheckConstraint("CK_AssessmentConsumerCursor_Progress","\"ConsumerName\"='assessment/1' AND \"LastEventSequence\">0 AND length(\"InputHash\")=64"));
        Foreign<Student,ConsumerReceipt>(b,"StudentId");Foreign<Outbox,ConsumerReceipt>(b,"EventId");Foreign<BackgroundJob,ConsumerReceipt>(b,"JobId");Foreign<Generation,ConsumerReceipt>(b,"GenerationId");b.Entity<ConsumerReceipt>().HasIndex(r=>new{r.ConsumerName,r.EventId}).IsUnique();
        Foreign<MappingPreparation,MappingModelCall>(b,"PreparationId");b.Entity<MappingModelCall>().HasIndex(c=>new{c.ExecutionId,c.CallNumber}).IsUnique();b.Entity<MappingModelCall>().Property(c=>c.ChargedCost).HasPrecision(16,6);
        Foreign<MappingModelCall,MappingCallReconciliation>(b,"CallId");Foreign<Account,MappingCallReconciliation>(b,"ActorId");b.Entity<MappingCallReconciliation>().HasIndex(r=>r.CallId).IsUnique();
        b.Entity<MappingModelCall>().ToTable(t=>{t.HasCheckConstraint("CK_MappingModelCall_Status","\"Status\" IN ('Started','Returned','Failed','Cancelled','Denied') AND \"BudgetState\" IN ('Reserved','Settled','Unresolved','Denied')");t.HasCheckConstraint("CK_MappingModelCall_Local","\"Currency\" IS NULL AND (\"ChargedCost\" IS NULL OR \"ChargedCost\"=0) AND \"BillingStatus\" IN ('Unknown','LocalMeasured','LocalNoCharge') AND (\"InputTokens\" IS NULL OR \"InputTokens\">=0) AND (\"OutputTokens\" IS NULL OR \"OutputTokens\">=0)");t.HasCheckConstraint("CK_MappingModelCall_Lifecycle","((\"Status\"='Started' AND \"FinishedAt\" IS NULL AND \"BudgetState\"='Reserved') OR (\"Status\"<>'Started' AND \"FinishedAt\" IS NOT NULL AND \"FinishedAt\">=\"StartedAt\")) AND (\"ElapsedMilliseconds\" IS NULL OR \"ElapsedMilliseconds\">=0) AND (\"BudgetState\"<>'Settled' OR (\"Status\"='Returned' AND \"ChargedCost\"=0 AND \"BillingStatus\" IN ('LocalMeasured','LocalNoCharge'))) AND ((\"Status\"='Denied')=(\"BudgetState\"='Denied'))");t.HasCheckConstraint("CK_MappingModelCall_Payload","jsonb_typeof(\"InputPayload\"::jsonb)='object' AND jsonb_typeof(\"ModelConfigPayload\"::jsonb)='object' AND jsonb_typeof(\"BudgetSnapshot\"::jsonb)='object'");t.HasCheckConstraint("CK_MappingModelCall_Input","length(\"InputHash\")=64 AND length(\"ModelConfigHash\")=64 AND \"AttemptNumber\">=1 AND \"RetryRound\">=0 AND \"CallNumber\">=1");});
        Foreign<BuilderCall,BuilderBudgetReconciliation>(b,"CallId");Foreign<Account,BuilderBudgetReconciliation>(b,"ActorId");b.Entity<BuilderBudgetReconciliation>().HasIndex(r=>r.CallId).IsUnique();b.Entity<BuilderBudgetReconciliation>().Property(r=>r.ChargedCost).HasPrecision(16,6);
        Foreign<BuilderRun,BuilderCall>(b,"RunId");b.Entity<BuilderCall>().HasIndex(c=>new{c.ExecutionId,c.CallNumber}).IsUnique();b.Entity<BuilderCall>().Property(c=>c.ChargedCost).HasPrecision(16,6);
        Foreign<BuilderRun, BuilderAttempt>(b,"RunId");b.Entity<BuilderAttempt>().HasIndex(a=>new{a.RunId,a.RetryRound,a.Number}).IsUnique();
        Foreign<Release, BuilderRun>(b,"LibraryReleaseId"); Foreign<ContentDraft, Candidate>(b,"CreatedDraftId"); Foreign<BuilderRun, Candidate>(b, "RunId"); Foreign<Chunk, Candidate>(b, "ChunkId");
        b.Entity<ContentIdentity>().HasIndex(x => new {x.FamilyId,x.EntityType,x.Code}).IsUnique();
        b.Entity<ReleaseItem>().HasIndex(x => new {x.ReleaseId,x.EntityType,x.IdentityId}).IsUnique();
        Foreign<ContentIdentity, ContentRevision>(b,"IdentityId");
        Foreign<Release, ReleaseItem>(b,"ReleaseId");
        Foreign<ContentIdentity, ReleaseItem>(b,"IdentityId");
        Foreign<ContentRevision, ReleaseItem>(b,"RevisionId");
        Foreign<Student, Attempt>(b,"StudentId"); Foreign<Student, Generation>(b,"StudentId");
        Foreign<Student, Outbox>(b,"StudentId"); Foreign<Student, Review>(b,"StudentId");
        Foreign<Student, Mastery>(b,"StudentId"); Foreign<Student, Evidence>(b,"StudentId");
        Foreign<Student, PaperWrong>(b,"StudentId"); Foreign<PrivateFile, PaperWrong>(b,"FileId"); Foreign<ContentDraft, PaperWrong>(b,"DraftId"); Foreign<Release, PaperWrong>(b,"ReleaseId"); Foreign<Attempt, PaperWrong>(b,"AttemptId");
        b.Entity<PaperWrong>().HasIndex(x=>x.AttemptId).IsUnique();
        b.Entity<Embedding>().HasIndex(e=>new {e.FamilyId,e.EntityRevisionId,e.Space}).IsUnique();
        b.Entity<Alias>().HasIndex(a=>new {a.FamilyId,a.KCId,a.Normalized}).IsUnique();
        Foreign<Release, KCChangeProposal>(b,"FromReleaseId"); Foreign<Release, KCChangeProposal>(b,"EffectiveReleaseId");
        Foreign<KCChangeProposal, KCChangeProposalItem>(b,"ProposalId"); Foreign<ContentIdentity, KCChangeProposalItem>(b,"KCId"); Foreign<ContentRevision, KCChangeProposalItem>(b,"ProposedRevisionId");
        Foreign<KCChangeProposal, KCProposalEvent>(b,"ProposalId"); b.Entity<KCProposalEvent>().HasIndex(e=>new{e.ProposalId,e.Version}).IsUnique();
        b.Entity<KCChangeProposalItem>().HasIndex(i=>new{i.ProposalId,i.Side,i.KCId}).IsUnique();
        Foreign<KCChangeProposal, KnowledgeMigration>(b,"ProposalId"); Foreign<ContentIdentity, KnowledgeMigration>(b,"FromKCId"); Foreign<ContentIdentity, KnowledgeMigration>(b,"ToKCId");
        Foreign<ContentRevision, KnowledgeMigration>(b,"FromRevisionId"); Foreign<ContentRevision, KnowledgeMigration>(b,"ToRevisionId"); Foreign<Release, KnowledgeMigration>(b,"EffectiveReleaseId");
        b.Entity<KnowledgeMigration>().HasIndex(m=>new{m.ProposalId,m.FromKCId,m.ToKCId}).IsUnique();
        Foreign<ContentIdentity, Alias>(b,"KCId"); Foreign<Candidate, Alias>(b,"CandidateId");
        Foreign<PrivateFile, Source>(b,"FileId");
        Foreign<Student, CorrectionBatch>(b,"StudentId"); Foreign<Release, CorrectionBatch>(b,"ReleaseId");
        Foreign<CorrectionBatch, CorrectionItem>(b,"BatchId"); Foreign<Attempt, CorrectionItem>(b,"AttemptId");
        Foreign<Release, CorrectionItem>(b,"MappingReleaseId");
        b.Entity<CorrectionItem>().HasIndex(i=>new {i.BatchId,i.AttemptId}).IsUnique();
        b.Entity<CorrectionItem>().Property(i=>i.Sequence).UseIdentityAlwaysColumn();
        foreach (var type in b.Model.GetEntityTypes())
            foreach (var p in type.GetProperties().Where(p => p.ClrType == typeof(decimal))) p.SetPrecision(16);
        foreach (var type in b.Model.GetEntityTypes())
            foreach (var p in type.GetProperties().Where(p => p.ClrType == typeof(decimal))) p.SetScale(6);
    }
    static void Foreign<TParent, TChild>(ModelBuilder b, string fk) where TParent : Row where TChild : Row
    {
        b.Entity<TParent>().HasAlternateKey(x => new { x.FamilyId, x.Id });
        b.Entity<TChild>().HasOne<TParent>().WithMany().HasForeignKey("FamilyId", fk)
            .HasPrincipalKey(x => new { x.FamilyId, x.Id }).OnDelete(DeleteBehavior.Cascade);
    }
    public async Task Lock(Guid familyId, CancellationToken ct = default)
        => await Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({familyId.ToString()}, 0))", ct);
}
