<script setup lang="ts">
import {onMounted,ref,watch} from 'vue';
import {api} from '../api';
type Item=Record<string,any>;
const props=defineProps<{studentId:string,refreshVersion?:number}>();const data=ref<Item|null>(null),error=ref(''),generation=ref(''),offset=ref(0),busy=ref(false);
const admissions:Record<string,string>={Pending:'待判分，不产生证据',RetryExcluded:'重试排除，不替换首次作答',NoEvidence:'关联内容，不产生能力证据',ObservedSteps:'仅采用已观察的步骤',Eligible:'按正式题目规则评估'};
let loadVersion=0;
async function load(){const version=++loadVersion;busy.value=true;error.value='';try{const response=await api(`/students/${props.studentId}/assessment-contexts?offset=${offset.value}&limit=20${generation.value?'&generation='+generation.value:''}`);if(version===loadVersion)data.value=response}catch(e){if(version===loadVersion)error.value=(e as Error).message}finally{if(version===loadVersion)busy.value=false}}
function select(){offset.value=0;load()}
onMounted(load);watch(()=>props.studentId,()=>{generation.value='';offset.value=0;load()});watch(()=>props.refreshVersion,load);
</script>
<template><section class="card" aria-label="评估版本记录"><h2>评估版本记录</h2><p class="muted">每次评估保留实际判分、题目映射和规则依据。更正产生新评估，旧记录可回看；重试和待判分记录不会补造能力证据。</p><p v-if="error" role="alert" class="warning">{{error}}</p><template v-if="data"><label>选择评估版本（最近50版）<select v-model="generation" @change="select" :disabled="busy"><option value="">当前评估</option><option v-for="g in data.generations" :value="g.id">{{new Date(g.createdAt).toLocaleString('zh-CN')}} · {{g.status==='Active'?'当前':'历史'}}</option></select></label><p v-if="!data.generation">尚无已完成评估。</p><template v-else><p>{{data.generation.status==='Active'?'当前生效':'历史保留'}} · {{data.total}} 条评估上下文</p><p v-if="data.legacyEvidenceCount" class="warning">此版本有 {{data.legacyEvidenceCount}} 条旧证据未记录独立上下文，保留原记录，没有补造历史版本。</p><article v-for="c in data.contexts" :key="c.id" class="content-editor-row"><p>{{admissions[c.admissionStatus]||c.admissionStatus}} · {{c.mappingSource==='FixedContainer'?'固定映射版本':'原发布快照（未记录独立映射）'}}</p><p>{{c.gradingCorrectionBatchId&&c.mappingCorrectionBatchId?'采用已确认判分与映射更正':c.gradingCorrectionBatchId?'采用已确认判分更正':c.mappingCorrectionBatchId?'采用已确认映射更正':c.correctionBatchId?'已确认更正后重放':'采用原会话判分与映射'}} · 规则 {{c.evidenceRuleVersion}}</p><details><summary>核对本条版本引用</summary><p>题目修订：{{c.questionRevisionId}}</p><p>判分修订：{{c.gradingRevisionId}}</p><p>映射修订：{{c.mappingSetRevisionId||'历史未记录'}}</p><p>原发布：{{c.contentReleaseId}}</p><p>归因发布：{{c.mappingReleaseId}}</p><p>原始作答：{{c.attemptId}}</p></details></article><p v-if="!data.total&&!data.legacyEvidenceCount">此评估没有作答记录。</p><button @click="offset-=20;load()" :disabled="busy||offset===0">上一页评估记录</button><span> 第 {{Math.floor(offset/20)+1}} 页 </span><button @click="offset+=20;load()" :disabled="busy||offset+20>=data.total">下一页评估记录</button></template></template></section></template>
<style scoped>p{overflow-wrap:anywhere}select{max-width:100%;min-width:0}</style>
