<script setup lang="ts">
import {onMounted,onUnmounted,ref,watch} from 'vue';import {api} from '../api';
const emit=defineEmits<{applied:[]}>();const props=defineProps<{studentId:string}>();const rows=ref<any[]>([]),reason=ref(''),busy=ref(false),error=ref(''),notice=ref('');let timer:ReturnType<typeof setInterval>|undefined;
const labels:Record<string,string>={Queued:'等待处理',Running:'处理中',Retrying:'等待重试',Failed:'已停止，待核对',Succeeded:'已完成',Cancelled:'已取消'};
const errors:Record<string,string>={JOB_CANCELLED_BY_USER:'已按家长依据取消，可明确核对后恢复原请求。',JOB_REQUESTER_FORBIDDEN:'家长权限已变化，可由有权限的家长核对后恢复。',REBUILD_RULE_CHANGED:'原规则已变化，请重新准备。',REBUILD_STUDENT_CONFIG_CHANGED:'学生时区已变化，请重新准备。',JOB_ATTEMPTS_EXHAUSTED:'多次处理中断，已停止自动重试。',REBUILD_PROCESSING_FAILED:'本次处理未完成，可核对后恢复。'};
async function run(action:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await action()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function load(){const id=props.studentId;const response=await api(`/students/${id}/rebuild-requests`);if(id===props.studentId){const completed=response.some((r:any)=>r.status==='Succeeded' && rows.value.some(old=>old.id===r.id && old.status!=='Succeeded'));rows.value=response;if(completed)emit('applied');}}
async function prepare(){await run(async()=>{const created=await api(`/students/${props.studentId}/mastery:rebuild`,{reason:reason.value.trim()});if(!rows.value.some(r=>r.id===created.id))rows.value=[created,...rows.value];await load();reason.value='';notice.value='已提交后台重建。完成前保留当前评估，处理时会包含已提交的新作答和更正。';});}
async function retry(row:any){const text=window.prompt('填写恢复依据，原规则和重试目标保持不变。');if(!text?.trim())return;await run(async()=>{await api(`/students/${props.studentId}/rebuild-requests/${row.id}:retry`,{reason:text.trim()});await load();notice.value='已按原请求重新排队，本轮恢复依据已保存。';});}
async function cancel(row:any){const text=window.prompt('填写取消重建的依据。当前评估将继续保留。');if(!text?.trim())return;await run(async()=>{const result=await api(`/background-jobs/${row.jobId}:cancel`,{reason:text.trim()});await load();notice.value=result.executionStopConfirmed?'已取消重建，当前评估保留。':'已取消重建的提交权限，等待处理停止确认。';});}
onMounted(()=>{void run(load);timer=setInterval(()=>{if(rows.value.some(r=>['Queued','Running','Retrying'].includes(r.status)))void run(load);},1500)});onUnmounted(()=>{if(timer)clearInterval(timer)});watch(()=>props.studentId,()=>{rows.value=[];reason.value='';notice.value='';void run(load)});
</script>
<template><section class="card" aria-label="后台评估重建"><h2>重新评估已有记录</h2><p class="muted">需要核对评估结果时，可在后台重建。依据原始作答与已确认更正重新计算，处理期间保留当前结果；相同输入可复用已有评估，不制造重复证据。</p><form @submit.prevent="prepare"><label>重建依据<textarea v-model="reason" maxlength="4000" :disabled="busy" placeholder="例如：核对已确认更正是否完整应用。" required></textarea></label><button :disabled="busy||!reason.trim()">提交后台重建</button></form><button @click="run(load)" :disabled="busy">刷新重建进度</button><p v-if="notice" role="status">{{notice}}</p><p v-if="error" role="alert">{{error}}</p><article v-for="r in rows" :key="r.id"><p>{{new Date(r.createdAt).toLocaleString('zh-CN')}} · {{labels[r.status]||r.status}}</p><p v-if="r.error">{{errors[r.error]||'原请求需要核对，请查看后台记录。'}}</p><p v-if="r.result">{{r.result.reusedGeneration?'已核对并复用已有评估':'已完成并应用重建结果'}}。结果回执已保存，可刷新评估版本记录查看。</p><button v-if="['Queued','Running','Retrying'].includes(r.status)" @click="cancel(r)" :disabled="busy">取消重建</button><button v-if="['Failed','Cancelled'].includes(r.status) && ['REBUILD_PROCESSING_FAILED','JOB_ATTEMPTS_EXHAUSTED','JOB_REQUESTER_FORBIDDEN','JOB_CANCELLED_BY_USER'].includes(r.error)" @click="retry(r)" :disabled="busy">核对后恢复重建</button></article><p v-if="!rows.length">暂无后台重建请求。</p></section></template>
