<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue';import {api} from '../api';
const data=ref<any>({jobs:[],attempts:[],total:0}),page=ref(1),busy=ref(false),error=ref(''),notice=ref('');
const labels:Record<string,string>={Queued:'等待处理',Running:'处理中',Succeeded:'已完成',Retrying:'等待重试',Failed:'已停止，待人工核对',Cancelled:'已取消',LeaseExpired:'处理中断，保护期已到期'};
const cursors=ref<(string|null)[]>([null]);let alive=true;onUnmounted(()=>{alive=false});
async function load(next=page.value,refresh=false){busy.value=true;error.value='';try{
 const cursor=refresh?null:cursors.value[next-1];const value=await api(`/background-jobs/window?pageSize=20${cursor?'&cursor='+encodeURIComponent(cursor):''}`);
 if(!alive)return;if(refresh)cursors.value=[null];data.value=value;page.value=refresh?1:next;
 cursors.value=cursors.value.slice(0,page.value);if(value.nextCursor)cursors.value.push(value.nextCursor);
}catch(e){if(alive)error.value=(e as Error).message}finally{if(alive)busy.value=false}}

async function cancel(job:any){const reason=window.prompt('填写取消依据。取消会阻止结果提交；已开始的模型调用仍须核对费用。');if(!reason?.trim()||busy.value)return;busy.value=true;error.value='';try{const result=await api(`/background-jobs/${job.id}:cancel`,{reason:reason.trim()});notice.value=result.executionStopConfirmed?'已取消，任务不会自动恢复。':'已取消提交权限，正在等待处理停止确认；调用账本和未知费用继续保留。';}catch(e){error.value=(e as Error).message}finally{busy.value=false}await load();}
onMounted(()=>load());
</script>
<template><section class="card" aria-label="后台任务保护"><h2>后台任务与中断保护</h2><p class="muted">建库、PDF解析、学习评估与映射准备会保存领取和续期记录。处理中断后可接替，旧进程失去领取权时不能提交结果；接替仍检查原输入及调用预算。</p><button :disabled="busy" @click="load(1,true)">刷新后台任务</button><p v-if="notice" role="status">{{notice}}</p><p v-if="error" role="alert">{{error}}</p><article v-for="job in data.jobs" :key="job.id" class="content-editor-row"><h3>{{job.type==='ParsePDF'?'PDF解析':job.type==='BuilderCandidates'?'候选建库':job.type==='AssessmentProjection'?'学习评估':job.type==='MappingSuggestions'?'映射建议':job.type==='AssessmentRebuild'?'评估重建':job.type}} · {{labels[job.status]||job.status}}</h3><button v-if="['Queued','Running','Retrying'].includes(job.status)&&['BuilderCandidates','ParsePDF','MappingSuggestions','AssessmentRebuild'].includes(job.type)" :disabled="busy" @click="cancel(job)">取消任务</button><p v-if="job.status==='Cancelled'&&data.attempts.some((a:any)=>a.jobId===job.id&&a.status==='Running')">提交权限已取消，处理停止尚待确认。</p><p>本轮领取 {{job.attemptCount}} / {{job.maxAttempts}} 次（包含处理中断）</p><p v-if="job.heartbeatAt">最近续期：{{new Date(job.heartbeatAt).toLocaleString()}}</p><p v-if="job.status==='Running'&&job.leaseExpiresAt">当前处理保护至：{{new Date(job.leaseExpiresAt).toLocaleString()}}</p><p v-if="job.nextRunAt">下次处理不早于：{{new Date(job.nextRunAt).toLocaleString()}}</p><p v-if="job.lastErrorCode">停止或重试编号：{{job.lastErrorCode}}</p><details><summary>查看领取记录</summary><p v-for="attempt in data.attempts.filter((a:any)=>a.jobId===job.id)" :key="attempt.id">第 {{attempt.retryRound}} 轮 · 第 {{attempt.number}} 次 · {{labels[attempt.status]||attempt.status}}<span v-if="attempt.errorCode"> · {{attempt.errorCode}}</span></p></details></article><p v-if="!data.total">尚无新后台任务记录；已完成的旧任务不会补造领取历史。</p><p>{{data.total}} 条 · 第 {{page}} 页</p><button :disabled="busy||page===1" @click="load(page-1)">上一页</button><button :disabled="busy||!data.nextCursor" @click="load(page+1)">下一页</button></section></template>
