<script setup lang="ts">
import {ref,watch,onUnmounted} from 'vue';
import {api} from '../api';
type Item=Record<string,any>;
const props=defineProps<{candidate:Item;owner:boolean;disabled:boolean}>();
const items=ref<Item[]>([]),selected=ref(''),detail=ref<Item|null>(null),calls=ref<Item>({calls:[],reconciliations:[],responses:[],total:0}),busy=ref(false),error=ref(''),notice=ref(''),reason=ref(''),forms=ref<Record<string,Item>>({}),raw=ref<Record<string,string>>({});
const page=ref(1),total=ref(0),callPage=ref(1);let alive=true,epoch=0,timer:ReturnType<typeof setTimeout>|undefined;
const states:Record<string,string>={Queued:'等待处理',Running:'正在处理',Retrying:'等待恢复',Succeeded:'建议已准备',Failed:'处理停止',Cancelled:'已取消等待'};
const decisions:Record<string,string>={LinkExisting:'建议关联已有能力',CreateDraft:'建议新建待审能力',Reject:'建议拒绝',NeedsReview:'需要人工核对'};
function targetName(){const d=detail.value;return d?.input.matches.find((m:Item)=>m.definition.id===d?.result?.kcId)?.definition.name||'原固定能力';}
function form(call:Item){return forms.value[call.id]??(forms.value[call.id]={providerFinished:false,inputTokens:'',outputTokens:'',reason:'',receiptReference:''});}
function resolved(call:Item){return calls.value.reconciliations.some((r:Item)=>r.callId===call.id);}
function active(){return ['Queued','Running','Retrying'].includes(detail.value?.preparation.status)||items.value.some(i=>['Queued','Running','Retrying'].includes(i.status));}
function schedule(){clearTimeout(timer);if(alive&&active())timer=setTimeout(()=>void load(),4000);}
async function load(next=page.value){if(busy.value)return;const current=epoch;busy.value=true;error.value='';try{const data=await api(`/builder/semantic-preparations?candidateId=${props.candidate.id}&page=${next}&pageSize=20`);if(!alive||current!==epoch)return;items.value=data.items;total.value=data.total;page.value=next;if(!selected.value&&items.value.length)selected.value=items.value[0].id;if(selected.value){const result=await api(`/builder/semantic-preparations/${selected.value}`);if(!alive||current!==epoch)return;detail.value=result;await loadCalls(callPage.value,current);}}catch(e){if(alive&&current===epoch)error.value=(e as Error).message}finally{if(alive&&current===epoch){busy.value=false;schedule();}}}
async function loadCalls(next=1,current=epoch){if(!selected.value)return;const result=await api(`/builder/semantic-calls?preparationId=${selected.value}&page=${next}&pageSize=20`);if(alive&&current===epoch){calls.value=result;callPage.value=next;}}
async function changeCallPage(next:number){if(busy.value||props.disabled)return;busy.value=true;error.value='';try{await loadCalls(next);}catch(e){error.value=(e as Error).message}finally{busy.value=false;}}
async function choose(){detail.value=null;callPage.value=1;await load();}
async function prepare(){if(busy.value||props.disabled)return;busy.value=true;error.value='';notice.value='';try{const result=await api(`/builder/candidates/${props.candidate.id}/semantic-preparations`,{});selected.value=result.id;notice.value='已保存本机语义任务，原候选和你填写的审核内容保留。';}catch(e){error.value=(e as Error).message}finally{busy.value=false;}if(!error.value)await load(1);}
async function retry(){if(!selected.value||busy.value||props.disabled||!reason.value.trim())return;busy.value=true;error.value='';try{await api(`/builder/semantic-preparations/${selected.value}:retry`,{reason:reason.value.trim()});reason.value='';notice.value='已记录本次人工重试依据，继续使用原固定输入。';}catch(e){error.value=(e as Error).message}finally{busy.value=false;}if(!error.value)await load();}
async function cancel(){if(!detail.value||busy.value||props.disabled||!reason.value.trim())return;busy.value=true;error.value='';try{await api(`/background-jobs/${detail.value.preparation.jobId}:cancel`,{reason:reason.value.trim()});reason.value='';notice.value='已取消结果提交；本机模型是否结束仍需核对。';}catch(e){error.value=(e as Error).message}finally{busy.value=false;}if(!error.value)await load();}
function token(value:unknown){if(value==='')return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw new Error('用量须为非负整数，未知请留空。');return n;}
async function reconcile(call:Item){if(busy.value||props.disabled)return;busy.value=true;error.value='';try{const f=form(call);await api(`/builder/semantic-calls/${call.id}:reconcile`,{providerFinished:f.providerFinished,inputTokens:call.inputTokens??token(f.inputTokens),outputTokens:call.outputTokens??token(f.outputTokens),reason:f.reason.trim(),receiptReference:f.receiptReference.trim()});notice.value='已追加调用结束依据，原未知用量保留。';}catch(e){error.value=(e as Error).message}finally{busy.value=false;}if(!error.value)await load();}
async function inspect(id:string){const current=epoch;try{const response=await api(`/builder/semantic-responses/${id}`);if(alive&&current===epoch)raw.value[id]=response.outputPayload;}catch(e){if(current===epoch)error.value=(e as Error).message}}
watch(()=>props.candidate.id,()=>{epoch++;clearTimeout(timer);items.value=[];selected.value='';detail.value=null;calls.value={calls:[],reconciliations:[],responses:[],total:0};page.value=1;callPage.value=1;forms.value={};raw.value={};reason.value='';notice.value='';busy.value=false;void load(1);},{immediate:true});
onUnmounted(()=>{alive=false;epoch++;clearTimeout(timer)});
</script>
<template><section class="card" aria-label="候选语义建议"><h4>本机语义建议</h4><p class="muted">对照原来源和固定能力定义，参考模型对行为与边界的判断。全部等待人工审核，有限召回不能证明没有重复能力；不会自动关联、拒绝或发布。当前召回仍使用原模拟排序。</p><p v-if="error" role="alert" class="warning">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><button v-if="candidate.status==='Pending'" @click="prepare" :disabled="busy||disabled||!candidate.protocolPayload">用本机模型准备语义建议</button><button @click="load()" :disabled="busy||disabled">刷新语义建议</button><p class="muted">准备或恢复任务不会提交你填写的候选审核内容。审核保存若提示记录已变化，请先保留填写内容再重新读取候选。</p><p v-if="!total">还没有语义准备记录。</p><label v-if="items.length">查看原语义任务<select v-model="selected" @change="choose" :disabled="busy||disabled"><option v-for="item in items" :key="item.id" :value="item.id">{{new Date(item.createdAt).toLocaleString()}} · {{states[item.status]||item.status}} · 第{{item.retryRound+1}}轮</option></select></label><div v-if="total>20"><button @click="selected='';load(page-1)" :disabled="busy||page===1">上一页语义任务</button><span>{{total}}条 · 第{{page}}页</span><button @click="selected='';load(page+1)" :disabled="busy||page*20>=total">下一页语义任务</button></div>
<article v-if="detail"><p>{{states[detail.preparation.status]||detail.preparation.status}} · {{detail.model.model}} · 第{{detail.preparation.retryRound+1}}轮 / 第{{detail.preparation.attemptCount}}次领取</p><p v-if="detail.preparation.error" class="warning">停止编号：{{detail.preparation.error}}</p><div v-if="detail.result" role="region" aria-label="原模型语义建议"><h5>{{decisions[detail.result.decision]}}</h5><p>{{detail.result.reason}}</p><template v-if="detail.result.kcId"><p>原建议目标：{{targetName()}} · 修订 {{detail.result.kcRevisionId}}</p></template><h5>原候选逐字引用</h5><blockquote v-for="(quote,index) in detail.result.candidateQuotes" :key="index">{{quote.text}}</blockquote><h5 v-if="detail.result.definitionQuotes.length">原目标定义引用</h5><blockquote v-for="(quote,index) in detail.result.definitionQuotes" :key="index">{{quote}}</blockquote><p class="muted">原模型理由和引用保持原样，不代表语义准确率或人工审核结论。请在候选审核区填写自己的依据。</p></div><details><summary>查看本次固定候选和召回定义</summary><p>{{detail.input.candidate.name}} · {{detail.input.candidate.measurableBehavior}} · {{detail.input.candidate.boundary}}</p><div v-for="match in detail.input.matches" :key="match.definition.id"><h5>{{match.definition.name}}</h5><p>{{match.definition.behavior}}</p><p>边界：{{match.definition.boundary}}</p><p>修订：{{match.definition.revisionId}}</p><p v-for="(example,index) in match.supportExamples" :key="index">{{example}}</p></div><p v-if="!detail.input.matches.length">原固定库没有召回项，无法据此排除已有能力。</p></details><template v-if="['Queued','Running','Retrying','Failed','Cancelled'].includes(detail.preparation.status)"><label>本次停止或重试依据<textarea v-model="reason" maxlength="4000" :disabled="busy||disabled"></textarea></label><button v-if="['Failed','Cancelled'].includes(detail.preparation.status)" @click="retry" :disabled="busy||disabled||!reason.trim()">按原输入人工重试</button><button v-else @click="cancel" :disabled="busy||disabled||!reason.trim()">取消语义等待</button></template></article>
<details v-if="selected"><summary>原调用与返回记录</summary><p>建库、映射和语义建议共用家庭名额。取消等待或任务中断不能证明本机模型已结束；未知用量不当作零。</p><article v-for="call in calls.calls" :key="call.id"><h5>{{call.model}} · {{call.status}} · 第{{call.retryRound+1}}轮</h5><p>输入 / 输出 Token：{{call.inputTokens??'未记录'}} / {{call.outputTokens??'未记录'}} · {{call.errorCode||''}}</p><div v-for="response in calls.responses.filter((r:Item)=>r.callId===call.id)" :key="response.id"><p>{{response.outputComplete?'已返回完整内容':'已返回截断内容'}}</p><button @click="inspect(response.id)" :disabled="busy||disabled">查看原模型返回</button><pre v-if="raw[response.id]!==undefined">{{raw[response.id]}}</pre></div><p v-if="resolved(call)">已追加负责人结束核对，原调用事实保留。</p><form v-if="owner&&!resolved(call)&&['Reserved','Unresolved'].includes(call.budgetState)" @submit.prevent="reconcile(call)"><label><input type="checkbox" v-model="form(call).providerFinished" required :disabled="busy||disabled">已实际确认本机模型调用结束</label><label v-if="call.inputTokens==null">实际输入 Token（未知可留空）<input v-model="form(call).inputTokens" type="number" min="0" step="1" :disabled="busy||disabled"></label><label v-if="call.outputTokens==null">实际输出 Token（未知可留空）<input v-model="form(call).outputTokens" type="number" min="0" step="1" :disabled="busy||disabled"></label><label>核对原因<textarea v-model="form(call).reason" required maxlength="4000" :disabled="busy||disabled"></textarea></label><label>实际结束依据<input v-model="form(call).receiptReference" required maxlength="500" :disabled="busy||disabled"></label><button :disabled="busy||disabled||!form(call).providerFinished">追加语义调用核对</button></form><p v-else-if="!owner&&!resolved(call)&&['Reserved','Unresolved'].includes(call.budgetState)">需家庭负责人核对调用是否实际结束。</p></article><p>{{calls.total}}条 · 第{{callPage}}页</p><button @click="changeCallPage(callPage-1)" :disabled="busy||callPage===1">上一页语义调用</button><button @click="changeCallPage(callPage+1)" :disabled="busy||callPage*20>=calls.total">下一页语义调用</button></details></section></template>
<style scoped>pre,blockquote{white-space:pre-wrap;overflow-wrap:anywhere}pre{max-height:24rem;overflow:auto}h5{font-size:1rem}article{border-top:1px solid var(--border,#ddd);padding-top:1rem}</style>
