<script setup lang="ts">
import {ref} from 'vue';
import {api,apiWithVersion} from '../api';
type Item=Record<string,any>;
const props=defineProps<{candidates:Item[];disabled:boolean}>(),emit=defineEmits<{refresh:[];openDraft:[candidate:Item];provenance:[candidate:Item]}>();
const selected=ref(''),context=ref<Item|null>(null),version=ref(''),busy=ref(false),error=ref(''),notice=ref('');
const form=ref({name:'',behavior:'',boundary:'',reason:''});
const statuses:Record<string,string>={Pending:'待审核',Accepted:'已接受',Rejected:'已拒绝'};
const actions:Record<string,string>={NeedsReview:'需要人工审核',CreateDraft:'建议新建草稿',LinkExisting:'建议关联已有能力',Reject:'建议拒绝'};
function resetFields(candidate:Item){form.value={name:candidate.name,behavior:candidate.behavior,boundary:candidate.boundary,reason:''};}
async function load(id:string){if(busy.value||props.disabled)return;busy.value=true;error.value='';notice.value='';try{const response=await apiWithVersion<Item>(`/builder/candidates/${id}/review-context`);selected.value=id;context.value=response.data;version.value=response.version;resetFields(response.data.candidate);}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function decide(decision:string,target?:string){if(!context.value||busy.value||props.disabled||!form.value.reason.trim())return;busy.value=true;error.value='';notice.value='';try{const candidate=await api(`/builder/candidates/${selected.value}:decide`,{decision,reason:form.value.reason,name:form.value.name,behavior:form.value.behavior,boundary:form.value.boundary,...(target?{existingKCId:target}:{})},'POST',undefined,version.value);context.value={...context.value,candidate};resetFields(candidate);notice.value=decision==='CreateDraft'?'已保存审核依据并生成待审核草稿；仍需补充题目、审核及发布。':decision==='LinkExisting'?'已保存关联和审核依据；原候选、正式内容与来源保留。':'已保存拒绝依据，原候选保留。';emit('refresh');}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function retrieval(){try{return context.value?.run.modelConfigPayload?JSON.parse(context.value.run.modelConfigPayload).retrieval:null}catch{return null}}
function quote(fragment:Item){const protocol=context.value?.protocol;const index=protocol?.sourceChunkIds.indexOf(fragment.id)??-1;return index>=0?protocol.supportingQuotes[index]:context.value?.candidate.quote;}
</script>
<template>
<section class="card" aria-label="候选逐项审核"><h2>逐项审核</h2><p class="muted">先打开一项核对来源与测量范围，再填写本次审核依据。稍后处理可保留待审核状态；未确认的内容不会发布。</p><p v-if="error" class="warning" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<div v-for="candidate in candidates" :key="candidate.id" class="content-row"><div><h3>{{candidate.name}}</h3><span class="tag">{{statuses[candidate.status]||candidate.status}}</span></div><button @click="load(candidate.id)" :disabled="busy||disabled">核对此候选</button></div><p v-if="!candidates.length" class="empty">还没有候选。</p>
<article v-if="context" class="candidate" aria-label="当前候选核对"><h3>核对 {{context.candidate.name}}</h3><p>{{context.run.provider}} / {{context.run.model}} · 提示版本 {{context.run.promptVersion}}</p><p>{{actions[context.candidate.suggestedAction]||context.candidate.suggestedAction}} · {{statuses[context.candidate.status]||context.candidate.status}}</p><p v-if="context.protocol" class="muted">学科 {{context.protocol.subject}} · 类型 {{context.protocol.kcType}} · 适用年级 {{context.protocol.gradeMin}}～{{context.protocol.gradeMax}} · 原输出分数 {{context.protocol.modelScore}}（不作为质量概率）</p><p class="muted">{{context.notice}}</p><p v-if="context.libraryNumber">创建时固定正式内容第 {{context.libraryNumber}} 版{{context.libraryWithdrawn?'（现已撤回，关联前需核对仍可用的正式能力）':''}}</p><p v-else>创建时没有固定正式内容库，不能推定相近能力的历史定义。</p>
<h4>来源与原始片段</h4><p>{{context.source.title}} · {{context.source.usageScope}}</p><div v-for="fragment in context.source.fragments" :key="fragment.id"><p>{{fragment.locator}}</p><blockquote>{{quote(fragment)}}</blockquote><details><summary>查看完整片段</summary><p class="source-fragment">{{fragment.text}}</p></details></div>
<label>{{context.candidate.status==='Pending'?'候选名称':'原始候选名称'}}<input v-model="form.name" maxlength="100" :disabled="context.candidate.status!=='Pending'||busy"></label><label>{{context.candidate.status==='Pending'?'可测行为':'原始候选行为'}}<textarea v-model="form.behavior" maxlength="4000" :disabled="context.candidate.status!=='Pending'||busy"></textarea></label><label>{{context.candidate.status==='Pending'?'能力边界':'原始候选边界'}}<textarea v-model="form.boundary" maxlength="4000" :disabled="context.candidate.status!=='Pending'||busy"></textarea></label>
<p v-if="retrieval()" class="muted">本次固定检索：候选名称、行为与边界 · 同能力类型 · 最多 {{retrieval().topK}} 项。为空时需人工核对，不能自动创建正式能力。</p><p v-else class="muted">旧检索沿用原来源片段和最多10项的兼容方式，不补造创建时未保存的检索设置。</p><p v-if="retrieval()?.version==='builder-retrieval/2'||retrieval()?.version==='builder-retrieval/3'" class="muted">本次固定 {{retrieval().aliases.length}} 项已审核别名；名称规范化后完全匹配的同类型能力优先列出，仍需人工核对。</p><p v-if="retrieval()?.version==='builder-retrieval/3'" class="muted">本次综合关键词与模拟相似排序，保留各自命中依据。</p><details><summary>相近能力与支持题目（模拟排序）</summary><p v-if="!context.matches.length">原运行没有检索结果，不自动判断应新建还是关联。</p><div v-for="item in context.matches" :key="item.match.kcId" class="content-editor-row"><h4>{{item.match.name}}</h4><p>原模拟相似分数 {{item.match.score}} · 仅供人工参考</p><p v-if="item.match.matchedAliases?.length" class="muted">命中已审核别名，优先列出：<span v-for="alias in item.match.matchedAliases" :key="alias.id">{{alias.text}}（来源候选 {{alias.candidateId}}） </span></p><p v-if="item.match.retrievalEvidence" class="muted">关键词匹配：{{item.match.retrievalEvidence.matchedTerms.join('、')||'无'}}；关键词排序 {{item.match.retrievalEvidence.keywordRank||'未进入前列'}} · 模拟相似排序 {{item.match.retrievalEvidence.vectorRank||'未进入前列'}}。综合排序仅供人工参考。</p><template v-if="item.definition"><p>{{item.definition.behavior}}</p><p>测量边界：{{item.definition.boundary}}</p><p class="muted">固定能力修订 {{item.definition.revisionId}}</p><h5>支持测量题目（显示 {{item.supportQuestions.length}} / {{item.supportCount}}）</h5><p v-if="!item.supportCount">该固定正式内容没有实际测量此能力的题目，不能推定已具备测量支持。</p><details v-for="question in item.supportQuestions" :key="question.id"><summary>{{question.stem}}</summary><p>参考答案：{{question.answer}}</p><p>{{question.explanation}}</p><p>判分方式 {{question.policy}} · 固定题目修订 {{question.revisionId}}</p></details><details v-if="item.contrastQuestions.length"><summary>不同测量目标的对照题</summary><p>以下正式题目测量其他目标，用于比较边界，不计作当前能力证据。</p><div v-for="question in item.contrastQuestions" :key="question.id"><p>{{question.stem}}</p><p>{{question.explanation}}</p></div></details></template><p v-else class="warning">原固定库中无法找到此能力定义；不补造支持题目。</p><button v-if="context.candidate.status==='Pending'&&item.definition" @click="decide('LinkExisting',item.match.kcId)" :disabled="busy||disabled||!form.reason.trim()">关联已有能力</button></div></details>
<template v-if="context.candidate.status==='Pending'"><label>本次审核依据<textarea v-model="form.reason" maxlength="4000" placeholder="说明核对了哪些来源、测量题与边界，以及新建、关联或拒绝的理由"></textarea></label><div><button @click="decide('CreateDraft')" :disabled="busy||disabled||!form.reason.trim()">接受为新草稿</button><button @click="decide('Reject')" :disabled="busy||disabled||!form.reason.trim()">拒绝</button><button @click="load(selected)" :disabled="busy||disabled">重新读取此候选</button></div><p class="muted">其他页面写入导致版本变化时保存会被拒绝，当前编辑和依据继续保留；重新读取会采用当前记录并清空未提交改动。</p></template><p v-else>审核依据：{{context.candidate.reviewReason}}</p>
<div v-if="context.candidate.createdDraftId"><button @click="emit('openDraft',context.candidate)">继续编辑审核草稿</button><button @click="emit('provenance',context.candidate)">查看引用与审核</button></div>
</article>
</section>
</template>
<style scoped>.source-fragment{white-space:pre-wrap;overflow-wrap:anywhere}.candidate{overflow-wrap:anywhere}.candidate h5{font-size:1rem}.candidate summary{white-space:normal}</style>
