<script setup lang="ts">
import {ref,watch,onMounted,onUnmounted} from 'vue';import {api} from '../api';import BuilderRecord from './BuilderRecord.vue';import ReviewDialog from './ReviewDialog.vue';import SourceEvidence from './SourceEvidence.vue';
type Item=Record<string,any>;
const props=defineProps<{refreshSignal?:object}>();
const stages=ref<Item[]>([]),stage=ref('extraction'),tasks=ref<Item>({items:[],total:0,page:1}),detail=ref<Item|null>(null),busy=ref(false),error=ref('');let alive=true,epoch=0;
const statuses:Record<string,string>={Imported:'来源已保存',NoText:'尚无可用文字',Queued:'等待处理',Running:'处理中',Retrying:'等待重试',Completed:'处理完成',Succeeded:'处理成功',Failed:'处理停止',Cancelled:'已取消',NeedsOCR:'需要文字识别',Pending:'待人工审核',Accepted:'已人工接受',Rejected:'已人工拒绝',Draft:'待审草稿',Reviewed:'已审核',Published:'已发布',Withdrawn:'已撤回',Saved:'完整索引已保存'};
const providers:Record<string,string>={Mock:'模拟流程',LocalOmlx:'本机模型',LocalParser:'本地解析',Local:'本地保存',Manual:'手工维护',Content:'内容记录',Preparation:'后台准备',Unknown:'旧记录未保存处理方式'};
async function load(next=1,counts=false){const current=++epoch;busy.value=true;error.value='';try{if(counts){const summary=await api('/builder/stages');if(!alive||current!==epoch)return;stages.value=summary;}const value=await api(`/builder/stages/${stage.value}/tasks?page=${next}&pageSize=20`);if(alive&&current===epoch)tasks.value=value;}catch(e){if(alive&&current===epoch)error.value=(e as Error).message;}finally{if(alive&&current===epoch)busy.value=false;}}
async function choose(id:string){stage.value=id;detail.value=null;tasks.value={items:[],total:0,page:1};await load();}
function closeDetail(){detail.value=null;epoch++;busy.value=false;}
async function inspect(id:string){const current=++epoch;busy.value=true;error.value='';detail.value=null;try{const value=await api(`/builder/stages/${stage.value}/tasks/${id}`);if(alive&&current===epoch)detail.value=value;}catch(e){if(alive&&current===epoch)error.value=(e as Error).message;}finally{if(alive&&current===epoch)busy.value=false;}}
async function dataPage(part:Item,next:number){if(!detail.value)return;const current=++epoch,id=detail.value.id;busy.value=true;error.value='';try{const value=await api(`/builder/stages/${stage.value}/tasks/${id}?related=${encodeURIComponent(part.id)}&relatedPage=${next}`);if(alive&&current===epoch&&detail.value?.id===id){const replacement=value.data.find((d:Item)=>d.id===part.id);detail.value.data=detail.value.data.map((d:Item)=>d.id===part.id?replacement:d);}}catch(e){if(alive&&current===epoch)error.value=(e as Error).message;}finally{if(alive&&current===epoch)busy.value=false;}}
async function refresh(){await load(tasks.value.page,true);if(!error.value&&detail.value){const id=detail.value.id;await inspect(id);}}
watch(()=>props.refreshSignal,()=>{if(!busy.value)void load(tasks.value.page,true);});
onMounted(()=>void load(1,true));onUnmounted(()=>{alive=false;epoch++;});
</script>
<template><section id="builder-stage-tasks" class="card" aria-label="建库阶段任务">
<h2>每个阶段的任务与数据</h2><p class="muted">按阶段查看全部真实记录，包含历史失败和模拟流程。列表随工作台刷新更新，展开的数据以读取时保存记录为准，可手动刷新。每条记录可展开原输入、输出、调用、领取与人工审核依据；未记录的数据不推算补齐。这里的查看和翻页不会启动模型或改变审核内容。</p>
<button :disabled="busy" @click="refresh">刷新阶段记录</button><p v-if="error" class="warning" role="alert">{{error}}</p>
<nav class="stage-tabs" aria-label="建库阶段"><button v-for="s in stages" :key="s.id" :disabled="busy" :aria-pressed="stage===s.id" @click="choose(s.id)">{{s.title}} · {{s.total}}</button></nav>
<h3>{{stages.find(s=>s.id===stage)?.title}}</h3><p class="muted">{{stages.find(s=>s.id===stage)?.notice}}</p><p v-if="busy" role="status">正在读取阶段记录…</p>
<article v-for="task in tasks.items" :key="task.id" class="stage-task"><div><h4>{{task.title}}</h4><p>{{statuses[task.status]||task.status}} · {{providers[task.provider]||task.provider}} · {{new Date(task.createdAt).toLocaleString('zh-CN')}}</p><small>记录编号 {{task.id}}</small></div><button :disabled="busy" @click="inspect(task.id)">查看任务数据</button></article>
<p v-if="!busy&&!tasks.items.length" class="empty">这个阶段尚无记录。</p><p>{{tasks.total}} 条 · 第 {{tasks.page}} 页</p><button :disabled="busy||tasks.page<=1" @click="load(tasks.page-1)">上一页任务</button><button :disabled="busy||tasks.page*20>=tasks.total" @click="load(tasks.page+1)">下一页任务</button>
<ReviewDialog v-if="detail" title="任务数据与原图复核" @close="closeDetail"><p v-if="error" class="warning" role="alert">{{error}}</p><div class="task-review-grid"><article class="task-data" aria-label="当前阶段任务数据"><button @click="closeDetail">收起任务数据</button><h3>原任务记录</h3><BuilderRecord :key="detail.id" :value="detail.record"/><section v-for="part in detail.data" :key="part.id"><h3>{{part.title}} · {{part.total}} 条</h3><p v-if="!part.total" class="muted">没有保存这类记录；旧历史不补造。</p><details v-for="(row,i) in part.items" :key="row.id||i"><summary>{{row.name||row.title||row.ownerTitle||row.model||row.locator||row.type||'记录'}} · {{statuses[row.status]||row.status||row.id}}</summary><BuilderRecord :value="row"/></details><div v-if="part.total>20"><span>第 {{part.page}} 页 </span><button :disabled="busy||part.page<=1" @click="dataPage(part,part.page-1)">上一页{{part.title}}</button><button :disabled="busy||part.page*20>=part.total" @click="dataPage(part,part.page+1)">下一页{{part.title}}</button></div></section></article><aside class="task-image"><SourceEvidence :stage="stage" :task-id="detail.id" :show-text="false"/></aside></div></ReviewDialog>
</section></template>
<style scoped>.stage-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}.stage-tabs button[aria-pressed=true]{background:#22624d;color:white}.stage-task{display:flex;align-items:center;gap:12px;border-bottom:1px solid #e5ebdf;padding:14px 0}.stage-task>div{flex:1;min-width:0}.stage-task h4{margin:0}.stage-task p{font-size:13px;margin:6px 0}.stage-task small{overflow-wrap:anywhere}.task-review-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;height:100%;min-height:0}.task-data,.task-image{min-width:0;overflow:auto;height:100%;padding-right:8px}.task-data h3{margin-top:12px}.task-data section{margin:24px 0}.task-data details{margin:10px 0;overflow-wrap:anywhere}.task-data summary{cursor:pointer}.stage-task button{flex-shrink:0}@media(max-width:760px){.task-review-grid{grid-template-columns:minmax(0,1fr);height:auto}.task-data,.task-image{height:auto;max-height:65dvh}.stage-task{flex-wrap:wrap}.stage-task>div{flex-basis:100%}}</style>
