<script setup lang="ts">
import {computed,ref} from 'vue';
const props=defineProps<{value:any}>();const page=ref(1),expanded=ref<Record<string,boolean>>({});
const labels:Record<string,string>={action:'操作类型',actorId:'操作成员',details:'原操作依据',id:'记录编号',familyId:'所属家庭',createdAt:'保存时间',title:'标题',name:'名称',text:'保存的文字',sourceId:'来源编号',fileId:'原文件编号',hash:'内容摘要',usageScope:'使用范围',allowExternalAI:'允许外部模型',locator:'原文位置',status:'原记录状态',type:'类型',provider:'处理方式',model:'模型',promptVersion:'提示版本',inputVersion:'输入版本',inputHash:'输入摘要',modelConfigPayload:'固定模型配置',modelConfigHash:'配置摘要',libraryReleaseId:'正式能力库编号',sourcePayload:'固定来源内容',sourceHash:'来源摘要',snapshot:'固定输入快照',snapshotHash:'快照摘要',inputPayload:'实际调用输入',outputPayload:'原模型返回',resultPayload:'原建议',protocolPayload:'原候选结构',matches:'创建时召回结果',behavior:'可测行为',boundary:'能力边界',quote:'原文引用',sourceChunkIds:'引用片段编号',supportingQuotes:'逐字引用',decision:'原决定',reason:'理由',reviewReason:'人工审核依据',reviewedAt:'审核时间',reviewedBy:'审核成员',createdDraftId:'生成的草稿编号',createdKCId:'生成的能力编号',existingKCId:'关联能力编号',runId:'运行编号',jobId:'后台任务编号',preparationId:'准备编号',responseId:'返回记录编号',callId:'调用编号',inputRef:'原任务对象编号',retryRound:'人工重试轮次（从0开始）',attemptCount:'本轮实际领取次数',attemptNumber:'处理尝试次数',number:'原记录序号',maxAttempts:'最多领取次数',callNumber:'物理调用序号',repair:'是否修复调用',retries:'本轮自动重试次数',error:'错误编号',errorCode:'错误编号',lastErrorCode:'最近错误编号',startedAt:'开始时间',finishedAt:'结束时间',completedAt:'完成时间',elapsedMilliseconds:'耗时（毫秒）',inputTokens:'实际输入 Token',outputTokens:'实际输出 Token',chargedCost:'实际费用',currency:'币种',billingStatus:'用量确认状态',budgetState:'预算状态',budgetSnapshot:'当时预算依据',outputComplete:'原返回是否完整',outputHash:'输出摘要',receiptReference:'实际结束依据',heartbeatAt:'最近续期',leaseExpiresAt:'当前保护到期时间',leaseOwner:'领取身份',nextRunAt:'下次处理时间',nextAttemptAt:'下次尝试时间',suggestedItems:'原映射建议',modelResultPayload:'原模型映射理由与引用',validationFlags:'核对提示',ownerType:'对象类型',ownerTitle:'对象标题',ownerId:'对象编号',ownerRevisionId:'对象修订编号',version:'版本',payload:'保存的内容',spaceId:'向量空间',configurationPayload:'固定模型配置',libraryPayload:'固定能力定义',vectorsPayload:'保存的向量',count:'数量',withdrawn:'是否撤回',publishedBy:'发布成员',publishedReleaseId:'实际发布编号',sourceTitle:'原来源标题',sourceDraftId:'原草稿编号',sourceDraftVersion:'原草稿版本',suggestionId:'建议编号',reviewerId:'审核成员',correctedPayload:'人工校正后的数据',libraryHash:'正式库摘要',entityType:'内容类型',identityId:'稳定内容编号',revisionId:'内容修订编号',space:'向量空间',dimensions:'向量维度',textHash:'实际输入文字摘要',scope:'审核范围',reasonSource:'审核依据来源',sourcePayloadHash:'来源摘要'};
const object=computed(()=>props.value!==null&&typeof props.value==='object'&&!Array.isArray(props.value));
function parsed(value:any){if(typeof value!=='string'||!['{','['].includes(value.trim()[0]||''))return null;try{const data=JSON.parse(value);return data&&typeof data==='object'?data:null}catch{return null}}
function structured(value:any){return value!==null&&typeof value==='object'||parsed(value)!==null}
function nested(value:any){return parsed(value)??value;}
function brief(value:any){const data=nested(value);return Array.isArray(data)?`${data.length} 项数据`:'展开相关字段';}
</script>
<template>
<div class="builder-record">
 <template v-if="object"><div v-for="(v,k) in value" :key="k" class="record-field"><strong>{{labels[String(k)]||k}}</strong><details v-if="structured(v)" @toggle="expanded[String(k)]=($event.target as HTMLDetailsElement).open"><summary>{{brief(v)}}</summary><BuilderRecord v-if="expanded[String(k)]" :value="nested(v)"/><details v-if="typeof v==='string'"><summary>查看原保存文字</summary><pre>{{v}}</pre></details></details><pre v-else>{{v===null?'未记录':typeof v==='boolean'?(v?'是':'否'):v}}</pre></div></template>
 <template v-else-if="Array.isArray(value)"><article v-for="(row,i) in value.slice((page-1)*20,page*20)" :key="i"><p class="muted">第 {{(page-1)*20+i+1}} 项</p><BuilderRecord :value="row"/></article><div v-if="value.length>20"><span>{{value.length}} 项 · 第 {{page}} 页 </span><button :disabled="page===1" @click="page--">前20项</button><button :disabled="page*20>=value.length" @click="page++">后20项</button></div></template>
 <pre v-else>{{value===null?'未记录':value}}</pre>
</div>
</template>
<style scoped>.builder-record{min-width:0}.record-field{display:grid;grid-template-columns:minmax(100px,180px) minmax(0,1fr);gap:12px;border-bottom:1px solid #e5ebdf;padding:10px 0}.record-field>strong{font-size:13px}.builder-record pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:24rem;overflow:auto;margin:0;font-size:13px}.builder-record details{min-width:0}.builder-record summary{cursor:pointer}.builder-record article{border:1px solid #e5ebdf;padding:12px;margin:10px 0;border-radius:8px}@media(max-width:760px){.record-field{grid-template-columns:minmax(0,1fr);gap:6px}}</style>
