<script setup lang="ts">
import {ref} from 'vue';import {api} from '../api';
type Item=Record<string,any>;
const props=defineProps<{studentId:string,goals:Item[],catalog:Item|null}>();const emit=defineEmits<{saved:[]}>();
const weekdays=[[1,'一'],[2,'二'],[3,'三'],[4,'四'],[5,'五'],[6,'六'],[0,'日']] as const;
function blank(){return {title:'每天阅读',minutes:10,paperReference:'自选图书',active:true,subject:'Reading',goalType:'Reading',kcId:null as string|null,period:'Daily',targetValue:1,days:[1,2,3,4,5,6,0],priority:3,startDate:'',endDate:'',reason:'家长设定学习目标'}}
const input=ref(blank()),editing=ref(''),busy=ref(false),error=ref(''),notice=ref('');
function fromGoal(g:Item){return {...blank(),...g,days:JSON.parse(g.scheduleRule),startDate:g.startDate||'',endDate:g.endDate||'',reason:'家长调整目标安排'}}
function template(type:string){editing.value='';input.value=blank();input.value.goalType=type;if(type==='Listening'){input.value.subject='English';input.value.title='英语听力';input.value.paperReference='家长准备的英语音频';}if(type==='Practice'){input.value.subject='Math';input.value.title='能力小练习';input.value.minutes=5;input.value.paperReference='使用已审核的正式题目';}}
async function run(action:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await action()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function payload(value:Item){return {...value,kcId:value.goalType==='Practice'?value.kcId:null,startDate:value.startDate||null,endDate:value.endDate||null,targetValue:value.period==='Daily'?1:value.targetValue};}
async function save(){await run(async()=>{await api(editing.value?`/goals/${editing.value}`:`/students/${props.studentId}/goals`,payload(input.value),editing.value?'PUT':'POST');editing.value='';input.value=blank();emit('saved');notice.value='目标已保存；重新生成草稿时采用新安排，已发布计划保留。';});}
async function toggle(g:Item){await run(async()=>{await api(`/goals/${g.id}`,payload({...fromGoal(g),active:!g.active,reason:g.active?'家长暂停目标':'家长恢复目标'}),'PUT');emit('saved');});}
function description(g:Item){return `${g.period==='Weekly'?`每周 ${g.targetValue} 次`:'每天一次'} · 星期${JSON.parse(g.scheduleRule).map((n:number)=>weekdays.find(([d])=>d===n)?.[1]).join('、')} · ${g.startDate||'不限开始'} 至 ${g.endDate||'不限结束'}`;}
</script>
<template><section class="card"><h2>固定学习目标</h2><p v-if="error" role="alert" class="warning">{{error}}</p><p v-if="notice">{{notice}}</p><div v-for="g in goals" class="content-row"><div><h3>{{g.title}}</h3><p>{{g.minutes}} 分钟 · {{g.paperReference}} · {{g.active?'启用':'暂停'}}</p><p>{{description(g)}} · 第 {{g.version}} 版</p><p v-if="g.kcId">范围：{{catalog?.kcs.find((k:Item)=>k.id===g.kcId)?.name||'该能力不在当前内容版本中'}}</p></div><button @click="editing=g.id;input=fromGoal(g)" :disabled="busy">编辑目标</button><button @click="toggle(g)" :disabled="busy">{{g.active?'暂停目标':'恢复目标'}}</button></div><p><button @click="template('Reading')">阅读模板</button><button @click="template('Listening')">听力模板</button><button @click="template('Practice')">能力练习模板</button></p><form class="form-grid" @submit.prevent="save"><label>目标名称<input v-model="input.title" required></label><label>每次分钟<input v-model.number="input.minutes" type="number" min="3" max="60" required></label><label>目标学科<select v-model="input.subject"><option value="Reading">阅读</option><option value="English">英语</option><option value="Math">数学</option><option value="Other">其他</option><option value="Unspecified">历史未记录</option></select></label><label>目标类型<select v-model="input.goalType"><option value="Reading">阅读</option><option value="Listening">听力</option><option value="Practice">能力练习</option><option value="Activity">其他活动</option></select></label><label v-if="input.goalType==='Practice'">目标能力范围<select v-model="input.kcId" required><option :value="null">选择正式能力</option><option v-for="k in catalog?.kcs||[]" :value="k.id">{{k.name}}</option></select></label><label>目标周期<select v-model="input.period"><option value="Daily">每天一次</option><option value="Weekly">每周指定次数</option></select></label><label v-if="input.period==='Weekly'">每周完成次数<input v-model.number="input.targetValue" type="number" min="1" :max="input.days.length" required></label><fieldset><legend>安排星期</legend><label v-for="[n,title] in weekdays" style="display:inline-flex;margin-right:12px"><input type="checkbox" v-model="input.days" :value="n">{{title}}</label></fieldset><label>目标开始日期<input v-model="input.startDate" type="date"></label><label>目标结束日期<input v-model="input.endDate" type="date"></label><label>目标优先级<select v-model.number="input.priority"><option :value="1">低</option><option :value="2">较低</option><option :value="3">通常</option><option :value="4">较高</option><option :value="5">高</option></select></label><label>纸质资源说明<input v-model="input.paperReference" required></label><label>目标调整依据<input v-model="input.reason" required></label><p class="muted">每天最多一次。每周按学生当地时间的周一至周日统计完成次数；跳过不算完成。阅读与听力只记录行为，能力练习还需提交作答。</p><button :disabled="busy">{{editing?'保存目标修改':'添加目标'}}</button><button v-if="editing" type="button" @click="template('Reading')">取消编辑</button></form></section></template>
