<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue';
import {api} from '../api';
type Item=Record<string,any>;
const props=defineProps<{owner:boolean;preparationId:string;preparations:Item[]}>();
const data=ref<Item>({calls:[],reconciliations:[],total:0}),page=ref(1),busy=ref(false),error=ref(''),notice=ref(''),forms=ref<Record<string,Item>>({});let alive=true;let requestNumber=0;
const labels:Record<string,string>={Started:'调用尝试已登记，返回尚未确认',Returned:'已收到真实返回',Failed:'未确认成功返回',Cancelled:'已取消等待，模型结束尚需核对',Denied:'名额或预算拒绝，未开始模型调用'};
function form(call:Item){return forms.value[call.id]??=({providerFinished:false,inputTokens:'',outputTokens:'',reason:'',receiptReference:''});}
function resolved(call:Item){return data.value.reconciliations.find((r:Item)=>r.callId===call.id);}
function title(call:Item){return props.preparations.find(p=>p.id===call.preparationId)?.sourceTitle||'原映射准备任务';}
async function load(next=1){const number=++requestNumber;busy.value=true;error.value='';try{const result=await api(`/builder/mapping-calls?page=${next}&pageSize=20${props.preparationId?'&preparationId='+encodeURIComponent(props.preparationId):''}`);if(!alive||number!==requestNumber)return;data.value=result;page.value=next;}catch(e){if(alive&&number===requestNumber)error.value=(e as Error).message;}finally{if(alive&&number===requestNumber)busy.value=false;}}
function token(value:unknown){if(value==='')return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<0)throw new Error('实际用量须为非负整数；未记录时请留空。');return n;}
async function reconcile(call:Item){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{const d=form(call);await api(`/builder/mapping-calls/${call.id}:reconcile`,{providerFinished:d.providerFinished,inputTokens:call.inputTokens==null?token(d.inputTokens):null,outputTokens:call.outputTokens==null?token(d.outputTokens):null,reason:d.reason.trim(),receiptReference:d.receiptReference.trim()});notice.value='已追加负责人核对，原调用记录及未知值保留。';await load(page.value);}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
watch(()=>props.preparationId,()=>{notice.value='';void load();});onMounted(()=>load());onUnmounted(()=>{alive=false;requestNumber++;});
</script>
<template><section class="card" aria-label="映射模型调用记录"><h3>映射模型调用记录</h3><p class="muted">{{preparationId?'当前任务':'全部映射任务'}} · 模型与辅助建库共用家庭名额。开始记录只表示调用尝试，不证明服务已收到请求；取消等待或后台停止不等于本机模型已结束。未知用量不当作零。</p><button @click="load(1)" :disabled="busy">刷新映射调用记录</button><p v-if="error" role="alert" class="warning">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><article v-for="call in data.calls" :key="call.id" class="content-editor-row"><h4>{{title(call)}} · {{labels[call.status]||call.status}}</h4><p>{{call.model}} · {{new Date(call.startedAt).toLocaleString('zh-CN')}} · 第 {{call.retryRound+1}} 轮 / 第 {{call.attemptNumber}} 次领取</p><p>输入 / 输出 Token：{{call.status==='Denied'?'不适用':`${call.inputTokens??'未记录'} / ${call.outputTokens??'未记录'}`}} · {{call.status==='Denied'?'未发生提供者调用':call.billingStatus==='LocalMeasured'||call.billingStatus==='LocalNoCharge'?'本机调用，无外部账单':'返回与用量未确认'}}</p><p v-if="call.elapsedMilliseconds!=null">本次等待 {{(call.elapsedMilliseconds/1000).toFixed(1)}} 秒</p><p v-if="call.errorCode">停止编号：{{call.errorCode}}</p><p v-if="resolved(call)">已追加负责人核对：{{resolved(call).reason}} · 依据：{{resolved(call).receiptReference}}。原调用事实保留。</p><form v-if="owner&&call.status!=='Denied'&&call.budgetState!=='Settled'&&!resolved(call)" @submit.prevent="reconcile(call)"><p class="muted">请先检查本机模型任务或进程是否确实结束，再追加核对。该操作释放已确认结束的名额，不将未知用量改为零，也不修改已有用量。</p><label class="mapping-call-check"><input type="checkbox" v-model="form(call).providerFinished" required :disabled="busy"><span>已实际确认本机模型调用结束</span></label><label v-if="call.inputTokens==null">实际输入 Token（未知可留空）<input v-model="form(call).inputTokens" type="number" min="0" max="9007199254740991" step="1" :disabled="busy"></label><label v-if="call.outputTokens==null">实际输出 Token（未知可留空）<input v-model="form(call).outputTokens" type="number" min="0" max="9007199254740991" step="1" :disabled="busy"></label><label>核对原因<textarea v-model="form(call).reason" maxlength="4000" required :disabled="busy"></textarea></label><label>本机任务或进程结束依据<input v-model="form(call).receiptReference" maxlength="500" required :disabled="busy"></label><button type="submit" :disabled="busy||!form(call).providerFinished||!form(call).reason.trim()||!form(call).receiptReference.trim()">追加映射调用核对</button></form><p v-else-if="!owner&&call.status!=='Denied'&&call.budgetState!=='Settled'&&!resolved(call)" class="muted">需要家庭负责人确认本机模型结束后核对。</p></article><p v-if="!data.total">还没有映射模型调用记录。模拟、手工维护及隔离诊断不会补造正式家庭调用。</p><p>{{data.total}} 条 · 第 {{page}} 页</p><button @click="load(page-1)" :disabled="busy||page===1">上一页调用</button><button @click="load(page+1)" :disabled="busy||page*20>=data.total">下一页调用</button></section></template>
<style scoped>.mapping-call-check{display:flex;gap:10px;align-items:flex-start}.mapping-call-check input{width:20px;flex:0 0 20px}p,h4{overflow-wrap:anywhere}input,textarea{max-width:100%;min-width:0}</style>
