<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {api} from '../api';
type Item=Record<string,any>;
const props=defineProps<{wrong:Item,releases:Item[]}>();
const emit=defineEmits<{saved:[],close:[],editDraft:[id:string]}>();
const record=ref({...props.wrong}),busy=ref(false),error=ref(''),notice=ref(''),preview=ref<Item|null>(null);
const releaseId=ref(props.releases.find(r=>!r.withdrawn)?.id||''),questionId=ref(props.wrong.questionId||'');
const catalog=computed(()=>{const r=props.releases.find(r=>r.id===releaseId.value);return r?JSON.parse(r.payload):null});
const question=computed(()=>catalog.value?.questions.find((q:Item)=>q.id===questionId.value));
const draft=ref({kcId:'',answer:'',explanation:'',type:'ShortAnswer'});
const result=ref('Incorrect'),reason=ref(''),same=ref(false),hintLevel=ref(0),answerShown=ref(false),steps=ref<Item[]>([]);
watch(question,q=>{preview.value=null;same.value=false;steps.value=(q?.mappings||[]).filter((m:Item)=>m.mode==='StepObserved').map((m:Item)=>({step:m.step,result:'Unknown',hintLevel:0}));},{immediate:true});
watch([result,reason,same,hintLevel,answerShown,steps,record],()=>preview.value=null,{deep:true});
async function run(action:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await action()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function save(){record.value=await api(`/paper-wrongs/${record.value.id}`,{stem:record.value.stem,answer:record.value.answer,fileId:record.value.fileId,errorType:record.value.errorType},'PUT');emit('saved');}
async function createDraft(){await run(async()=>{await save();const response=await api(`/paper-wrongs/${record.value.id}/draft`,{releaseId:releaseId.value,...draft.value});record.value.draftId=response.draft.id;emit('saved');emit('editDraft',response.draft.id);});}
function input(){return {releaseId:releaseId.value,questionId:questionId.value,result:result.value,reason:reason.value,sameQuestionConfirmed:same.value,hintLevel:hintLevel.value,answerShown:answerShown.value,steps:steps.value.map(s=>({step:s.step,result:s.result,hintLevel:s.hintLevel}))};}
async function review(){await run(async()=>{await save();const value=input();preview.value={...await api(`/paper-wrongs/${record.value.id}/preview`,value),input:value};});}
async function confirm(){await run(async()=>{const p=preview.value!;await api(`/paper-wrongs/${record.value.id}/confirm`,{...p.input,previewHash:p.previewHash});emit('saved');emit('close');});}
const errorTypes=[['Unknown','未知'],['Concept','概念'],['Calculation','计算'],['Reading','阅读'],['Unit','单位'],['Expression','表达'],['Careless','家长确认的粗心']];
</script>
<template>
<section class="card"><h2>审核纸质结果</h2><p v-if="error" role="alert" class="warning">{{error}}</p><p v-if="notice">{{notice}}</p><img v-if="record.fileId" :src="`/api/v1/files/${record.fileId}`" style="max-width:100%;max-height:260px" alt="纸质原题私有图片">
<form @submit.prevent="run(async()=>{await save();notice='待校正信息已保存，尚未产生能力证据。'})"><label>纸质原题正文<textarea v-model="record.stem" rows="3"></textarea></label><label>纸质原始答案<input v-model="record.answer"></label><label>错误类型<select v-model="record.errorType"><option v-for="[value,label] in errorTypes" :value="value">{{label}}</option></select></label><button :disabled="busy">保存待校正信息</button></form>
<p class="muted">新原题发布后，请在“内容与发布”绑定包含该题的版本，后续计划才能安排原题复习。</p><label>核对正式内容版本<select v-model="releaseId"><option value="">选择正式版本</option><option v-for="r in releases.filter(r=>!r.withdrawn)" :value="r.id">内容版本 {{r.number}}</option></select></label>
<details v-if="!record.draftId"><summary>原题尚未入库：创建审核草稿</summary><p class="muted">保存原题后新增独立题目。草稿要核对答案与映射、审核发布，才能确认纸质结果；步骤题可继续在内容编辑器补齐观察点。</p><form @submit.prevent="createDraft"><label>纸质题测量能力<select v-model="draft.kcId" required><option value="">选择能力</option><option v-for="k in catalog?.kcs||[]" :value="k.id">{{k.name}}</option></select></label><label>纸质题参考答案<input v-model="draft.answer" required></label><label>纸质题解析<textarea v-model="draft.explanation" required></textarea></label><label>纸质题题型<select v-model="draft.type"><option value="ShortAnswer">家长判分</option><option value="Numeric">数值精确判分</option></select></label><button :disabled="busy||!releaseId">创建原题审核草稿</button></form></details><button v-else @click="emit('editDraft',record.draftId)" :disabled="busy">继续编辑原题草稿</button>
<form @submit.prevent="review"><label>对应的正式原题<select v-model="questionId" required><option value="">选择已发布的原题</option><option v-for="q in catalog?.questions||[]" :value="q.id">{{q.stem}}</option></select></label><div v-if="question"><p>正式题干：{{question.stem}}</p><p>参考答案：{{question.answer}} · {{question.explanation}}</p><p>测量能力：{{question.mappings.filter((m:Item)=>m.mode!=='None').map((m:Item)=>catalog.kcs.find((k:Item)=>k.id===m.kcId)?.name).join('、')||'仅记录，不产生能力证据'}}</p></div><label><input v-model="same" type="checkbox" required>已核对这是同一道原题，题干与条件一致</label><label>纸质整题结果<select v-model="result"><option value="Incorrect">错误</option><option value="Correct">正确</option><option value="Partial">部分正确</option><option value="Unscorable">不可评分</option></select></label><label>整题提示程度<select v-model.number="hintLevel"><option :value="0">独立完成</option><option :value="1">轻提示</option><option :value="2">步骤提示</option><option :value="3">已展示答案</option></select></label><label><input v-model="answerShown" type="checkbox">作答前已经看过答案</label><div v-for="s in steps" class="form-grid"><label>{{s.step}} · 纸质观察<select v-model="s.result"><option value="Unknown">未知 / 未观察</option><option value="Correct">正确</option><option value="Incorrect">错误</option></select></label><label>步骤提示程度<select v-model.number="s.hintLevel"><option :value="0">独立完成</option><option :value="1">轻提示</option><option :value="2">步骤提示</option><option :value="3">已展示答案</option></select></label></div><label>纸质判分与归因依据<textarea v-model="reason" required></textarea></label><button :disabled="busy||!question">预览纸质结果归因</button></form>
<div v-if="preview" class="warning"><h3>确认前核对</h3><p>原始答案：{{preview.answer}} · {{result==='Incorrect'?'错误':result==='Correct'?'正确':result==='Partial'?'部分正确':'不可评分'}}</p><p>{{preview.input.reason}}</p><p v-for="s in preview.input.steps">{{s.step}}：{{s.result==='Unknown'?'未知 / 未观察':s.result==='Correct'?'正确':'错误'}} · 提示 {{s.hintLevel}}</p><p>{{preview.notice}}</p><button class="primary" @click="confirm" :disabled="busy">确认并代录纸质结果</button></div><button @click="emit('close')" :disabled="busy">关闭审核</button>
</section>
</template>
