<script setup lang="ts">
import {ref,watch} from 'vue';
import {localDate} from '../api';
const props=defineProps<{summary:any,busy:boolean,timeZone:string}>();const emit=defineEmits<{select:[date:string]}>();
const end=ref(props.summary?.end||localDate(props.timeZone));watch(()=>props.summary?.end,v=>{if(v)end.value=v;});
function shift(days:number){const value=new Date((props.summary?.end||localDate(props.timeZone))+'T12:00:00Z');value.setUTCDate(value.getUTCDate()+days);const date=value.toISOString().slice(0,10);emit('select',date>localDate(props.timeZone)?localDate(props.timeZone):date);}
const confidenceNames:Record<string,string>={Low:'低',Medium:'中',High:'高'};
const coverageName=(value:string)=>value==='Basic'?'基础题':value;
const masteryNames:Record<string,string>={Unknown:'未知',Learning:'学习中',CanDo:'初步会做',Mastered:'已掌握',Stable:'稳定保持'};
const reviewReasons:Record<string,string>={TARGET_RETAINED:'家长确认保留原目标，本次未测量该目标',TRUSTED_TARGET_CONFIRMED:'家长确认实际目标的独立通过，原目标仍待复习',TARGET_CHANGED:'测量目标已变化，请家长核对；本次未计原目标通过',PENDING_GRADING:'待判分，未进入分母',NOT_CORRECT:'首次答案未独立答对',ASSISTED:'使用提示或看过答案',ROLLING_24H:'24小时内重复原题',TRUSTED_INDEPENDENT:'已判分且独立通过'};
const names:Record<string,string>={Planned:'待发布',Ready:'准备开始',InProgress:'进行中',Completed:'已完成',Skipped:'已跳过',Deferred:'已延期',Abandoned:'已结束'};
</script>
<template>
  <div class="page-heading"><div><p class="eyebrow">WEEK / 每周回顾</p><h1>一周的小步，累积成进步</h1><p class="muted">调整计划保留原始分母，未完成的任务不会被隐藏。</p></div></div>
  <form class="week-selector" @submit.prevent="emit('select',end)"><label>周报结束日期<input type="date" v-model="end" :max="localDate(timeZone)" min="2000-01-07" required :disabled="busy"></label><button :disabled="busy">查看所选一周</button><button type="button" @click="shift(-7)" :disabled="busy">前一周</button><button type="button" @click="shift(7)" :disabled="busy||(summary?.end||end)>=localDate(timeZone)">后一周</button><button type="button" @click="emit('select',localDate(timeZone))" :disabled="busy">返回最近一周</button></form>
  <p v-if="summary" class="muted" role="status">统计日期：{{summary.start}} 至 {{summary.end}} · {{summary.timeZone}} · 任务状态更新至本次查看</p>
  <div v-if="summary" class="summary-grid"><section class="card"><p>最初发布任务</p><h2>{{summary.original.completed}} / {{summary.original.total}}</h2><span>完成数 / 原始任务数</span></section><section class="card"><p>调整后任务</p><h2>{{summary.adjusted.completed}} / {{summary.adjusted.total}}</h2><span>完成数 / 最终活动任务数</span></section><section class="card"><p>当前到期复习</p><h2>{{summary.dueReviews}}</h2><span>{{summary.pending}} 个事件等待后台处理；不是往周覆盖率</span></section></div>
  <section v-if="summary?.budgetExecutability" class="card" aria-label="预算可执行率"><h2>预算可执行率</h2><p class="stat">{{summary.budgetExecutability.eligibleTasks}} / {{summary.budgetExecutability.publishedTasks}} · {{summary.budgetExecutability.rate===null?'暂无已发布任务':`${Math.round(summary.budgetExecutability.rate*100)}%`}}</p><p>预计时长内完成 {{summary.budgetExecutability.completedWithinEstimate}} 项，明确家长顺延 {{summary.budgetExecutability.confirmedDeferredTasks}} 项；重叠只计一次。</p><p v-if="summary.budgetExecutability.unknownCompletedDuration" class="muted">{{summary.budgetExecutability.unknownCompletedDuration}} 项已完成但缺少可核对的时长，未计入预计时长内完成项。</p><p class="muted">{{summary.budgetExecutability.note}}</p><details v-if="summary.budgetExecutability.tasks.length"><summary>查看逐项预算依据</summary><div v-for="t in summary.budgetExecutability.tasks" :key="t.taskId" class="content-row"><div><h3>{{t.title}} · {{t.eligible?'已计入':'未计入'}}</h3><p>{{names[t.status]||t.status}} · 预计 {{t.estimatedMinutes}} 分钟 · {{t.actualMinutes===null?'实际耗时未知':`实际 ${t.actualMinutes} 分钟`}}</p><p v-if="t.completedWithinEstimate">已在任务预计时长内完成。</p><p v-if="t.unknownCompletedDuration">完成时长无法核对，保留缺口。</p><p v-for="(d,index) in t.deferrals" :key="index">家长确认顺延至 {{d.targetDate}}：{{d.reason}} · {{new Date(d.confirmedAt).toLocaleString('zh-CN',{timeZone})}}</p></div></div></details></section>
  <section v-if="summary?.reviewPass" class="card" aria-label="复习通过率"><h2>复习通过率</h2><p class="stat">{{summary.reviewPass.independentPasses}} / {{summary.reviewPass.gradedEncounters}} · {{summary.reviewPass.rate===null?'暂无已判分复习':`${Math.round(summary.reviewPass.rate*100)}%`}}</p><p>实际复习遇题 {{summary.reviewPass.encounters}} 次，待判分 {{summary.reviewPass.pendingEncounters}} 次。</p><p class="muted">{{summary.reviewPass.note}}</p><details v-if="summary.reviewPass.items.length"><summary>查看逐次复习判分依据</summary><div v-for="r in summary.reviewPass.items" :key="r.attemptId" class="content-row"><div><h3>{{reviewReasons[r.reason]||r.reason}}</h3><p>{{new Date(r.occurredAt).toLocaleString('zh-CN',{timeZone})}} · {{({Correct:'正确',Incorrect:'错误',Partial:'部分正确',Pending:'待判分'} as Record<string,string>)[r.result]||r.result}}</p><p v-if="r.gradedAt" class="muted">最新判分：{{new Date(r.gradedAt).toLocaleString('zh-CN',{timeZone})}}</p></div></div></details></section>
  <section v-if="summary?.reviewCoverage" class="card" aria-label="复习覆盖率"><h2>复习覆盖率</h2><p class="stat">{{summary.reviewCoverage.executedSchedules}} / {{summary.reviewCoverage.dueSchedules}} · {{summary.reviewCoverage.rate===null?'暂无到期日程':`${Math.round(summary.reviewCoverage.rate*100)}%`}}</p><p>期初未做逾期 {{summary.reviewCoverage.overdueAtStart}} 项，本周未执行 {{summary.reviewCoverage.unexecutedSchedules}} 项。</p><p class="muted">{{summary.reviewCoverage.note}}</p><details v-if="summary.reviewCoverage.items.length"><summary>查看到期与未做依据</summary><div v-for="r in summary.reviewCoverage.items" :key="r.schedule.id" class="content-row"><div><h3>{{r.schedule.targetType==='WrongQuestion'?'错题复习':'能力复测'}} · {{r.schedule.stage}} · {{r.executedInPeriod?'本周已执行':'本周未执行'}}</h3><p>到期 {{r.schedule.dueDate}}<span v-if="r.overdueAtStart"> · 期初未做逾期</span></p><p v-if="r.schedule.executedAt">实际作答 {{new Date(r.schedule.executedAt).toLocaleString('zh-CN',{timeZone})}}<span v-if="!r.executedInPeriod"> · 在所选周之后</span></p><p v-else>尚未提交首次复习答案。</p></div></div></details></section>
  <section v-if="summary?.masteryChanges" class="card" aria-label="掌握变化"><h2>掌握变化</h2><p>新增证据 {{summary.masteryChanges.evidenceParts}} 条，来自 {{summary.masteryChanges.encounters}} 次遇题；其中 {{summary.masteryChanges.suppressedParts}} 条权重为零。</p><p>状态变化 {{summary.masteryChanges.statusChanges}} 次，待复核变化 {{summary.masteryChanges.recheckChanges}} 次，覆盖变化 {{summary.masteryChanges.coverageChanges}} 次。</p><p class="muted">{{summary.masteryChanges.note}}</p><details v-if="summary.masteryChanges.items.length"><summary>查看能力变化与证据依据</summary><div v-for="m in summary.masteryChanges.items" :key="m.kcId" class="content-row"><div><h3>{{m.name}}</h3><p>{{m.before?(masteryNames[m.before.status]||m.before.status):'期初暂无记录'}} → {{masteryNames[m.after.status]||m.after.status}} · {{m.after.needsRecheck?'需要复核':'无待复核标记'}}</p><p>本周 {{m.evidenceParts}} 条证据 / {{m.encounters}} 次遇题 · 正证据权重 {{Number(m.positiveWeight).toFixed(2)}} · 负证据权重 {{Number(m.negativeWeight).toFixed(2)}}</p><p>期末有效证据 {{Number(m.after.effectiveEvidence).toFixed(2)}} · {{m.after.distinctQuestions}} 道不同题 · 可信度 {{confidenceNames[m.after.confidence]||m.after.confidence}} · 尚缺覆盖：{{m.after.requiredCoverage.filter((v:string)=>!m.after.coveredCoverage.includes(v)).map(coverageName).join('、')||'已覆盖规定情境'}}</p><p>7天延迟复测 {{m.after.delay7?'已具备':'尚缺'}} · 30天保持复测 {{m.after.delay30?'已具备':'尚缺'}}</p><details v-if="m.changes.length"><summary>逐次状态与覆盖变化（{{m.changes.length}}条）</summary><p v-for="(c,index) in m.changes" :key="index">{{new Date(c.occurredAt).toLocaleString('zh-CN',{timeZone})}} · {{c.before?(masteryNames[c.before.status]||c.before.status):'暂无记录'}} → {{masteryNames[c.after.status]||c.after.status}} · {{c.after.needsRecheck?'需要复核':'无待复核标记'}} · 已覆盖 {{c.after.coveredCoverage.map(coverageName).join('、')||'暂无'}} · 7天 {{c.after.delay7?'已具备':'尚缺'}} / 30天 {{c.after.delay30?'已具备':'尚缺'}}</p></details><details v-if="m.evidence.length"><summary>本周证据部分（{{m.evidence.length}}条）</summary><p v-for="(e,index) in m.evidence" :key="index">{{new Date(e.occurredAt).toLocaleString('zh-CN',{timeZone})}} · {{e.part==='WholeItem'?'整题':e.part}} · {{e.positive?'正证据':'负证据'}} · 权重 {{Number(e.weight).toFixed(2)}}{{e.weight===0?'（不增加掌握证据）':''}}</p></details></div></div></details><p v-else class="empty">所选期末之前尚无可回看的能力记录。</p></section>
  <section v-if="summary" class="card"><h2>本周计划与调整依据</h2><p class="muted">{{summary.historyNote}}</p>
    <details v-if="summary.tasks.length"><summary>查看原始、最终及中间版本任务（{{summary.tasks.length}}项）</summary><div v-for="t in summary.tasks" :key="t.taskId" class="content-row"><div><h3>{{t.title}} · {{names[t.status]||t.status}}</h3><p v-for="p in t.placements" :key="p.revisionId">{{p.date}} · 发布版本 {{p.revision}} · {{p.original?'最初计划':''}} {{p.current?'最终活动计划':''}} {{!p.original&&!p.current?'中间发布版本':''}}</p><p>预计 {{t.estimatedMinutes}} 分钟 · {{t.actualMinutes===null?'实际耗时未记录':`当前已知实际耗时 ${t.actualMinutes} 分钟`}}</p></div></div></details><p v-else class="empty">所选日期没有已发布任务，不计入完成率。</p>
    <details v-if="summary.adjustments.length"><summary>查看家长调整原因（{{summary.adjustments.length}}条）</summary><div v-for="a in summary.adjustments" :key="a.id" class="content-row"><div><p>{{new Date(a.recordedAt).toLocaleString('zh-CN',{timeZone})}} · {{a.details.reason}}<span v-if="a.details.kind==='TaskDeferral'"> · 顺延至 {{a.details.deferredTo}}</span> · {{a.published?'该修订已发布':'仅草稿调整，未计入完成率'}}</p><p>调整前 {{a.details.beforeTaskIds.length}} 项，调整后 {{a.details.afterTaskIds.length}} 项，移除 {{a.details.removedTaskIds.length}} 项</p></div></div></details><p v-else class="muted">所选计划尚无可回看的具体调整原因；旧摘要不能恢复原说明。</p>
    <details v-if="summary.transitions.length"><summary>查看执行与跳过说明（{{summary.transitions.length}}条）</summary><div v-for="a in summary.transitions" :key="a.id" class="content-row"><div><p>{{summary.tasks.find((t:any)=>t.taskId===a.details.taskId)?.title}} · {{names[a.details.from]||a.details.from}} → {{names[a.details.to]||a.details.to}}</p><p>{{a.details.reason||'未填写原因'}} · {{new Date(a.recordedAt).toLocaleString('zh-CN',{timeZone})}}</p></div></div></details>
  </section>
</template>
<style scoped>.week-selector{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-bottom:16px}.week-selector label{margin:0}.week-selector button{margin-bottom:0}</style>
